### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by jacobstr** [bazelbuild/rules_go#1116] opened 2017-12-07 20:29 UTC
In the process of updating to Bazel 0.8.1.

```
git_repository(
    name='io_bazel_rules_go',
    remote='https://github.com/bazelbuild/rules_go',
    tag = "0.8.0",
)
load("@io_bazel_rules_go//go:def.bzl", "go_repository", "go_rules_dependencies", "go_register_toolchains")
go_rules_dependencies()
go_register_toolchains()

git_repository(
    name='org_pubref_rules_protobuf',
    remote='https://github.com/pubref/rules_protobuf',
    commit='563b674a2ce6650d459732932ea2bc98c9c9a9bf',
)

```

```
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
cmd/link/internal/ld.decodetypePtrdata(0x6f7060, 0xc42398af98, 0xc4205e4659)
	/usr/local/go/src/cmd/link/internal/ld/decodesym.go:83 +0x9c
cmd/link/internal/ld.(*GCProg).AddSym(0xc424ac2000, 0xc425726938)
	/usr/local/go/src/cmd/link/internal/ld/data.go:1260 +0x76
cmd/link/internal/ld.(*Link).dodata(0xc420508000)
	/usr/local/go/src/cmd/link/internal/ld/data.go:1573 +0x1932
cmd/link/internal/ld.Main()
	/usr/local/go/src/cmd/link/internal/ld/main.go:219 +0x9fd
main.main()
	/usr/local/go/src/cmd/link/main.go:58 +0xac
2017/12/07 20:10:40 error running linker: exit status 1
```

The failing command is quite dense:

```
bazel-out/host/bin/external/io_bazel_rules_go/go/tools/builders/linux_amd64_stripped/link -go bazel-out/host/bin/external/go_stdlib_linux_amd64_cgo/bin/go -root_file bazel-out/host/bin/external/go_stdlib_linux_amd64_cgo/ROOT -goos linux -goarch amd64 '-cgo=1' -- -L . -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/golang.org/x/sys/unix~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/golang.org/x/crypto/ssh/terminal~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/github.com/Sirupsen/logrus~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/pkg/logging/linux_amd64_stripped/go_default_library~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/github.com/jmoiron/sqlx/reflectx~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/github.com/jmoiron/sqlx~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/github.com/lib/pq/oid~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/github.com/lib/pq~/' -L 'bazel-out/k8-fastbuild/bin/external/org_golang_x_net/context/linux_amd64_stripped/go_default_library~/' -L 'bazel-out/k8-fastbuild/bin/external/com_github_mattn_go_sqlite3/linux_amd64_stripped/go_default_library~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/pkg/db/linux_amd64_stripped/go_default_library~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/cloud.google.com/go/internal/version~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/golang.org/x/net/context~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/github.com/golang/protobuf/proto~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/golang.org/x/net/http2/hpack~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/golang.org/x/text/transform~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/golang.org/x/text/unicode/bidi~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/golang.org/x/text/secure/bidirule~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/golang.org/x/text/unicode/norm~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/golang.org/x/net/idna~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/golang.org/x/net/lex/httplex~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/golang.org/x/net/http2~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/golang.org/x/net/internal/timeseries~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/golang.org/x/net/trace~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/google.golang.org/grpc/codes~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/google.golang.org/grpc/credentials~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/google.golang.org/grpc/grpclb/grpc_lb_v1~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/google.golang.org/grpc/grpclog~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/google.golang.org/grpc/internal~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/google.golang.org/grpc/keepalive~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/google.golang.org/grpc/metadata~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/google.golang.org/grpc/naming~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/google.golang.org/grpc/peer~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/google.golang.org/grpc/stats~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/github.com/golang/protobuf/ptypes/any~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/google.golang.org/genproto/googleapis/rpc/status~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/google.golang.org/grpc/status~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/google.golang.org/grpc/tap~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/google.golang.org/grpc/transport~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/google.golang.org/grpc~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/github.com/googleapis/gax-go~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/google.golang.org/api/iterator~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/golang.org/x/net/context/ctxhttp~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/golang.org/x/oauth2/internal~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/golang.org/x/oauth2~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/cloud.google.com/go/compute/metadata~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/golang.org/x/oauth2/jws~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/golang.org/x/oauth2/jwt~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/golang.org/x/oauth2/google~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/google.golang.org/api/internal~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/google.golang.org/api/option~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/google.golang.org/grpc/credentials/oauth~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/google.golang.org/api/transport/grpc~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/google.golang.org/api/googleapi/transport~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/google.golang.org/api/transport/http~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/google.golang.org/api/transport~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/github.com/golang/protobuf/ptypes/empty~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/github.com/golang/protobuf/ptypes/timestamp~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/github.com/golang/protobuf/protoc-gen-go/descriptor~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/google.golang.org/genproto/googleapis/api/annotations~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/google.golang.org/genproto/googleapis/devtools/cloudtrace/v1~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/cloud.google.com/go/trace/apiv1~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/github.com/gogo/protobuf/proto~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/github.com/opentracing/basictracer-go/wire~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/github.com/opentracing/opentracing-go/log~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/github.com/opentracing/opentracing-go~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/github.com/opentracing/opentracing-go/ext~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/github.com/opentracing/basictracer-go~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/golang.org/x/sync/semaphore~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/google.golang.org/api/support/bundler~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/github.com/lovoo/gcloud-opentracing~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/github.com/opentracing/opentracing-go/mocktracer~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/code.earth.planet.com/product/uno/lib/golang/opentracingutil~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/pkg/client/common/linux_amd64_stripped/go_default_library~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/pkg/client/task/linux_amd64_stripped/go_default_library~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/pkg/client/workload/linux_amd64_stripped/go_default_library~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/pkg/jsonlang/linux_amd64_stripped/go_default_library~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/pkg/workload_store/linux_amd64_stripped/go_default_library~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/github.com/segmentio/ksuid~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/pkg/programlang/linux_amd64_stripped/go_default_library~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/cmd/render-program/linux_amd64_stripped/render-program~/' -o bazel-out/k8-fastbuild/bin/services/g4/cmd/render-program/linux_amd64_stripped/render-program -w -extld /usr/bin/gcc -extldflags '-U_FORTIFY_SOURCE -fstack-protector -Wall -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -D_FORTIFY_SOURCE=1 -DNDEBUG -ffunction-sections -fdata-sections -g0 -fno-canonical-system-headers -Wno-builtin-macro-redefined -D__DATE__="redacted" -D__TIMESTAMP__="redacted" -D__TIME__="redacted" -lstdc++ -lm -fuse-ld=gold -Wl,-no-as-needed -Wl,-z,relro,-z,now -B/usr/bin -B/usr/bin -pass-exit-codes -Wl,--gc-sections -Wl,-rpath,$ORIGIN/../../../../../' 'bazel-out/k8-fastbuild/bin/services/g4/cmd/render-program/linux_amd64_stripped/render-program~/code.earth.planet.com/product/uno/services/g4/cmd/render-program.a'
```

Interestingly, I removed a dependency on github.com/mattn/sqlite3 from one of our packages. I had some suspicions because it's a cgo package. I didn't actually end up removing it entirely, but it did have the effect of changing the build the command subtly:

```
bazel-out/host/bin/external/io_bazel_rules_go/go/tools/builders/linux_amd64_stripped/link -go bazel-out/host/bin/external/go_stdlib_linux_amd64_cgo/bin/go -root_file bazel-out/host/bin/external/go_stdlib_linux_amd64_cgo/ROOT -goos linux -goarch amd64 '-cgo=1' -- -L . -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/golang.org/x/sys/unix~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/golang.org/x/crypto/ssh/terminal~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/github.com/Sirupsen/logrus~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/pkg/logging/linux_amd64_stripped/go_default_library~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/github.com/jmoiron/sqlx/reflectx~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/github.com/jmoiron/sqlx~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/github.com/lib/pq/oid~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/github.com/lib/pq~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/pkg/db/linux_amd64_stripped/go_default_library~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/cloud.google.com/go/internal/version~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/golang.org/x/net/context~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/github.com/golang/protobuf/proto~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/golang.org/x/net/http2/hpack~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/golang.org/x/text/transform~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/golang.org/x/text/unicode/bidi~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/golang.org/x/text/secure/bidirule~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/golang.org/x/text/unicode/norm~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/golang.org/x/net/idna~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/golang.org/x/net/lex/httplex~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/golang.org/x/net/http2~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/golang.org/x/net/internal/timeseries~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/golang.org/x/net/trace~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/google.golang.org/grpc/codes~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/google.golang.org/grpc/credentials~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/google.golang.org/grpc/grpclb/grpc_lb_v1~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/google.golang.org/grpc/grpclog~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/google.golang.org/grpc/internal~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/google.golang.org/grpc/keepalive~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/google.golang.org/grpc/metadata~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/google.golang.org/grpc/naming~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/google.golang.org/grpc/peer~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/google.golang.org/grpc/stats~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/github.com/golang/protobuf/ptypes/any~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/google.golang.org/genproto/googleapis/rpc/status~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/google.golang.org/grpc/status~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/google.golang.org/grpc/tap~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/google.golang.org/grpc/transport~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/google.golang.org/grpc~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/github.com/googleapis/gax-go~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/google.golang.org/api/iterator~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/golang.org/x/net/context/ctxhttp~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/golang.org/x/oauth2/internal~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/golang.org/x/oauth2~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/cloud.google.com/go/compute/metadata~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/golang.org/x/oauth2/jws~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/golang.org/x/oauth2/jwt~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/golang.org/x/oauth2/google~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/google.golang.org/api/internal~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/google.golang.org/api/option~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/google.golang.org/grpc/credentials/oauth~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/google.golang.org/api/transport/grpc~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/google.golang.org/api/googleapi/transport~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/google.golang.org/api/transport/http~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/google.golang.org/api/transport~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/github.com/golang/protobuf/ptypes/empty~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/github.com/golang/protobuf/ptypes/timestamp~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/github.com/golang/protobuf/protoc-gen-go/descriptor~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/google.golang.org/genproto/googleapis/api/annotations~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/google.golang.org/genproto/googleapis/devtools/cloudtrace/v1~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/cloud.google.com/go/trace/apiv1~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/github.com/gogo/protobuf/proto~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/github.com/opentracing/basictracer-go/wire~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/github.com/opentracing/opentracing-go/log~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/github.com/opentracing/opentracing-go~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/github.com/opentracing/opentracing-go/ext~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/github.com/opentracing/basictracer-go~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/golang.org/x/sync/semaphore~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/google.golang.org/api/support/bundler~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/github.com/lovoo/gcloud-opentracing~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/github.com/opentracing/opentracing-go/mocktracer~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/code.earth.planet.com/product/uno/lib/golang/opentracingutil~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/pkg/client/common/linux_amd64_stripped/go_default_library~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/pkg/client/task/linux_amd64_stripped/go_default_library~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/pkg/client/workload/linux_amd64_stripped/go_default_library~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/pkg/jsonlang/linux_amd64_stripped/go_default_library~/' -L 'bazel-out/k8-fastbuild/bin/external/org_golang_x_net/context/linux_amd64_stripped/go_default_library~/' -L 'bazel-out/k8-fastbuild/bin/external/com_github_mattn_go_sqlite3/linux_amd64_stripped/go_default_library~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/pkg/workload_store/linux_amd64_stripped/go_default_library~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/github.com/segmentio/ksuid~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/pkg/programlang/linux_amd64_stripped/go_default_library~/' -L 'bazel-out/k8-fastbuild/bin/services/g4/cmd/render-program/linux_amd64_stripped/render-program~/' -o bazel-out/k8-fastbuild/bin/services/g4/cmd/render-program/linux_amd64_stripped/render-program -w -extld /usr/bin/gcc -extldflags '-U_FORTIFY_SOURCE -fstack-protector -Wall -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -D_FORTIFY_SOURCE=1 -DNDEBUG -ffunction-sections -fdata-sections -g0 -fno-canonical-system-headers -Wno-builtin-macro-redefined -D__DATE__="redacted" -D__TIMESTAMP__="redacted" -D__TIME__="redacted" -lstdc++ -lm -fuse-ld=gold -Wl,-no-as-needed -Wl,-z,relro,-z,now -B/usr/bin -B/usr/bin -pass-exit-codes -Wl,--gc-sections -Wl,-rpath,$ORIGIN/../../../../../' 'bazel-out/k8-fastbuild/bin/services/g4/cmd/render-program/linux_amd64_stripped/render-program~/code.earth.planet.com/product/uno/services/g4/cmd/render-program.a'
```

The arguments are nearly identical, except now `org_golang_x_net/context` and `com_github_mattn_go_sqlite3` occur closer to the end of the argument list rather than near the beginning. This command `exits 0`! 

I'm not certain how to reproduce this, ideally it's an interaction between the open source packages so that I could publish some reproducible test case.

**Comment by jacobstr** [comment] 2017-12-07 21:57
Relevant, perhaps: https://go-review.googlesource.com/c/go/+/22744

> lib2.so will contain a type symbol for T in its symbol table, but no
definition. If, when linking lib3.so the linker reads the symbols from lib2.so
before libBase.so, the linker didn't read the type data and later crashed.

**Comment by jayconrod** [comment] 2017-12-07 22:30
Very strange. The issue you pointed to certainly seems like the same problem. The fix for that should have been in the toolchain a long time ago.

The order of the link search paths probably changed because these deps are reachable along a different path than they were before. I doubt the order matters, but whatever caused the order to change probably also triggered this.

I'll look at this tomorrow, but I'm not at all familiar with the linker, so I'll likely end up reaching out to other folks on the Go team.

Anything you can do to help us reproduce this would be very helpful. I don't know whether we'll be able to make much progress on this without more information.

**Comment by jacobstr** [comment] 2017-12-07 23:05
Some more details that might shed some light:
- `org_golang_x_net/context/...` appears to be the culprit. Moving it's associated `-L flag` around causes the issue to surface or go away.

I can perhaps try bisecting the issue by moving the flag around until it fails - that might reveal which other dependency it's having a bad interaction with and lead to something reproducible.

We're using a rather old, customized fork of gazelle to generate our BUILD files. I tried re-ordering the deps in the build file and this also appeared to address the issue but that's quite brittle and I believe the philosophy behind `dep` ordering is clean diffs via alphabetical sorting instead of ordering for correctness.

**Comment by jayconrod** [comment] 2017-12-08 19:18
I noticed in both command lines you posted, there are multiple paths for golang.org/x/net/context.

```
-L 'bazel-out/k8-fastbuild/bin/external/org_golang_x_net/context/linux_amd64_stripped/go_default_library~/'
-L 'bazel-out/k8-fastbuild/bin/services/g4/vendor/linux_amd64_stripped/golang.org/x/net/context~/'
```

So you may have multiple copies of that library (external and vendored) being pulled into the build. I don't think we check for that explicitly (we probably should). Maybe that's triggering this issue?

**Comment by memoleaf** [comment] 2018-02-06 08:30
I encountered the same issue and it looks it's indeed caused by two copies of `golang.org/x/net/context`.

We use gRPC and Spanner in our project.

`go_proto_repositories()` in `@org_pubref_rules_protobuf//go:rules.bzl` adds `@org_golang_x_net` as an external repository.

Spanner's repo is not a bazel workspace, so we use `go get -u cloud.google.com/go/spanner/...` to download all the dependencies and store them into `vendor` folder. Then we use gazelle to generate the BUILD files in `vendor` folder. Since spanner also depends on `x/net/context`, a second copy ends up being stored in `vendor` as well.

I manually changed all the BUILD files in `vendor` folder, replacing all `//vendor/golang.org/x/net/context` with `@org_golang_x_net/context`. Then the error goes away.

I don't think this is a good solution, since gazelle will overwrite my changes next time I run it. And similar issue may happen for `@org_golang_x_text` and `@org_golang_google_grpc` as well.

Any suggestions?

**Comment by jayconrod** [comment] 2018-02-06 15:53
@memoleaf There are a couple options here, but this workflow isn't as ergonomic as I would like yet.

Your simplest option is probably to remove `vendor/golang.org/x/net` from vendor. Since a locally vendored library will no longer visible, Gazelle will resolve dependencies to `@org_golang_x_net`.

A more complete solution is to use Spanner through an external repository instead of vendoring it. (This may not be practical, depending on your other requirements and whether Spanner or its dependencies need any customization, but I mention it as an option). You can add individual `go_repository` rules to `WORKSPACE` using `gazelle update-repos cloud.google.com/go/spanner`. This may be a little tedious, since you'll also need to add transitive dependencies, too. Another way to do this is to import repository rules from dep's Gopkg.lock using `gazelle update-repos -from_file Gopkg.lock`. `go_repository` rules will automatically depend on libraries in other external repositories, not vendor.

One other thing to be aware of: if you have a build that actually needs two copies of a library, you can rename the import path for one of them using the `importmap` attribute on `go_library`. This is how `go build` handles vendored libraries.

**Comment by jayconrod** [comment] 2018-02-08 18:36
Marking this as a bug. At minimum, we should report a comprehensible error during analysis when multiple packages have the same import path at link time.

I don't think we can automatically rename packages using `importmap`, since this effect would be visible through reflection. Perhaps Gazelle can add `importmap` attributes to libraries in vendor directories (which is basically what go build does).

**Comment by jayconrod** [comment] 2018-08-02 21:39
Closing old issues. We report warnings during analysis if there are multiple packages with the same name. Gazelle mostly avoids this with `importmap` attributes automatically added for vendored packages.

**Closed by jayconrod** 2018-08-02 21:39 UTC
Labels: bug, go
