### ISSUE TITLE
cycle dependency in nogo and go_context_data

### ISSUE THREAD

**Issue by linzhp** [bazelbuild/rules_go#2479] opened 2020-05-07 21:01 UTC
### What version of rules_go are you using?

745de507d7f7e8837eba01dd5ff9d4ef7edf31c7

### What version of gazelle are you using?

7e93b118efcdfe63f43057a88711762e0b5d7267

### What version of Bazel are you using?

3.0.0

### Does this issue reproduce with the latest releases of all the above?

yes

### What operating system and processor architecture are you using?

Darwin amd 64

### What did you do?

```bash
git clone git@github.com:linzhp/bazel_examples.git
cd bazel_examples
git checkout 510e7a2798ab0f3e9cf2b93b06a28a92dad539fd
bazel build //:gazelle
```

### What did you expect to see?

Build completed successfully

### What did you see instead?
```
ERROR: /private/var/tmp/_bazel_zplin/1b23f78923ad6c0028e8aab1a0a6d5fb/external/io_bazel_rules_go/BUILD.bazel:71:1: in go_context_data rule @io_bazel_rules_go//:go_context_data: cycle in dependency graph:
    //:gazelle
    //:gazelle-runner
    @bazel_gazelle//cmd/gazelle:gazelle (host)
.-> @io_bazel_rules_go//:go_context_data (host)
|   @io_bazel_rules_go//:nogo_alias (host)
|   @io_bazel_rules_go//go/config:nogo (host)
|   @io_bazel_rules_nogo//:nogo (host)
|   //:default_nogo (host)
`-- @io_bazel_rules_go//:go_context_data (host)
This cycle occurred because of a configuration option
ERROR: Analysis of target '//:gazelle' failed; build aborted
INFO: Elapsed time: 2.653s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (71 packages loaded, 7044 targets configured)
```

**Comment by jayconrod** [comment] 2020-05-08 16:55
Thanks for reporting. It looks like my workaround for bazelbuild/bazel#11291 won't work.

I'll roll back #2374 and #2374. Which is very disappointing. I was really looking forward to getting rid of `go_tool_library`.

**Comment by rickystewart** [comment] 2021-06-25 17:22
We've stumbled across an instance of this bug which, for some reason, seems to manifest when we upgrade `golang.org/x/tools`. [This](https://github.com/cockroachdb/cockroach/pull/66880) is the original PR that uncovered the issue, but I've pushed a minimal repro (latest versions of `gazelle`/`rules_go`/`bazel`) to the `gazelle_circular` branch [here](https://github.com/rickystewart/repro/tree/gazelle_circular) -- `bazel build :gazelle` to repro. Updating these dependencies causes Gazelle, and apparently any `go_binary`, to fail to build with the cyclic dependency through `@io_bazel_rules_go//:go_context_data` above. The error isn't stable, but it looks something like this:

```
ERROR: /private/var/tmp/_bazel_ricky/b12fe6cd3e6e067332cc17cd9865b32d/external/io_bazel_rules_go/BUILD.bazel:73:16: in go_context_data rule @io_bazel_rules_go//:go_context_data: cycle in dependency graph:
    //:gazelle
    //:gazelle-runner
    @bazel_gazelle//cmd/gazelle:gazelle
    @bazel_gazelle//cmd/gazelle:gazelle_lib
    @bazel_gazelle//language:language
    @bazel_gazelle//resolve:resolve
    @bazel_gazelle//label:label
.-> @io_bazel_rules_go//:go_context_data
|   @io_bazel_rules_nogo//:nogo
|   @io_bazel_rules_go//:default_nogo
|   @io_bazel_rules_go//go/tools/builders:nogo_srcs
|   @org_golang_x_tools//go/analysis:go_tool_library
|   @org_golang_x_tools//internal/analysisinternal:go_tool_library
|   @org_golang_x_tools//go/ast/astutil:go_tool_library
|   @org_golang_x_tools//internal/typeparams:typeparams
`-- @io_bazel_rules_go//:go_context_data
```

I've also confirmed that using a lower version of `x/tools` fixes the issue and allows `bazel build :gazelle` to succeed (apply the following patch to my repro to demonstrate):

```
diff --git a/WORKSPACE b/WORKSPACE
index bf53938..a27b7e8 100644
--- a/WORKSPACE
+++ b/WORKSPACE
@@ -30,8 +30,8 @@ go_repository(
     name = "org_golang_x_tools",
     build_file_proto_mode = "disable_global",
     importpath = "golang.org/x/tools",
-    sum = "h1:L69ShwSZEyCsLKoAxDKeMvLDZkumEe8gXUZAjab0tX8=",
-    version = "v0.1.3",
+    sum = "h1:kRBLX7v7Af8W7Gdbbc908OJcdgtK8bOz9Uaj8/F1ACA=",
+    version = "v0.1.2",
 )
 
 go_repository(
```

Since this reliably breaks Gazelle, the dependency update is blocked. I haven't been able to find a workaround -- any guidance y'all have would be very helpful.

**Comment by nazufel** [comment] 2021-06-29 13:20
This issue is affecting me as well.

**Comment by tarrencev** [comment] 2021-07-02 04:30
Running into this issue too. Applying the x/tools downgrade does avoid the issue but is not really viable

**Comment by NikBisht** [comment] 2021-08-03 21:26
Also experiencing this issue attempting to update golang.org/x/tools from v0.1.0 to v0.1.5

**Comment by dtbartle** [comment] 2021-09-03 19:46
Should be fixed by https://github.com/bazelbuild/bazel-gazelle/commit/9f72eed9f79bfc18a04e8ac6204751998c7cba4a

**Closed** 2023-11-03 16:09 UTC
Labels: bug, nogo
