### ISSUE TITLE
embedded go_source are not detected by Intellij Bazel Plugin

### ISSUE THREAD

**Issue by wingsofovnia** [bazelbuild/rules_go#2246] opened 2019-10-15 10:43 UTC
### What version of rules_go are you using?
792fc6d3ec0

### What version of gazelle are you using?
https://github.com/jayconrod/bazel-gazelle/commit/67c9ddf12d8a044cb1f9dde0c5c03da2390a2571

### What version of Bazel are you using?
0.28.1

The issue is described in details here: https://github.com/bazelbuild/intellij/issues/1265

It is most likely the issue is purely plugin related, but I open this issue here as well to investigate possible reasons for embedded sources to sneak out from the plugin.

**Comment by jayconrod** [comment] 2019-10-15 14:32
Sorry, I don't really know anything about the intellij plugin and can't provide support for it.

#512 is the main issue for supporting tools and IDEs, so I'll close this as a duplicate of that one.

**Closed by jayconrod** 2019-10-15 14:32 UTC
