### ISSUE TITLE
gotags can't be a result of a select({})

### ISSUE THREAD

**Issue by Mythra** [bazelbuild/rules_go#2694] opened 2020-10-27 15:44 UTC
### What version of rules_go are you using?

v0.24.5

### What version of gazelle are you using?

v0.22.2

### What version of Bazel are you using?

3.6.0

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

Linux, x86_64

### What did you do?

I have a `go_library` rule which has files that are dependent on `gotags` in order to be built, most specifically a SQL Driver flag. Here is the cquery result of the rule (to remove any macro magic):

```
bazelisk cquery '//pkg/db/pool:go_lib' --output build --noimplicit_deps
<...>
go_library(
  name = "go_lib",
  visibility = ["//visibility:public"],
  generator_name = "go_lib",
  generator_function = "tgo_package",
  generator_location = "pkg/db/pool/BUILD:3:12",
  srcs = ["//pkg/db/pool:dbpool_bazel.go", "//pkg/db/pool:postgres.go", "//pkg/db/pool:sqlite.go"],
  importpath = "github.com/tetrateio/tetrate/pkg/db/pool",
  embed = ["@tetrate_resolve_deps//pkg/db/pool:regular_deps", "@tetrate_resolve_deps//pkg/db/pool:sql_driver_sqlite_deps"],
  x_defs = {"build": "{STABLE_VERSION_STRING}"},
  cgo = True,
)
<...>
```

`dbpool_bazel.go` has a build tag called: `bazel` (to not interfere with the other dbpool implementation in another build system that needs to be supported.) `postgres.go` has a buildtag constraint on "postgres", `sqlite.go` has a buildtag constraint on "sqlite". CGO is required because of sqlite. When trying to `depend` on this with a go_test rule, this fails to build <https://gist.github.com/Mythra/614c390c9c61bd50247931c9b78dba2a>. I believe this is because dbpool never gets the `bazel` tag, or `sqlite` tag and thus believes there's nothing to import. The go_test rule for reference:

```
<...>
go_transition_test(
  name = "go_test",
  generator_name = "go_test",
  generator_function = "tgo_package",
  generator_location = "pkg/db/pool/BUILD:3:12",
  size = "small",
  srcs = ["//pkg/db/pool:dbpool_test.go"],
  embed = ["@tetrate_resolve_deps//pkg/db/pool:test_deps", "@tetrate_resolve_deps//pkg/db/pool:sql_driver_sqlite_test_deps"],
  importpath = "github.com/tetrateio/tetrate/pkg/db/pool_test",
  x_defs = {"build": "{STABLE_VERSION_STRING}"},
  cgo = True,
  pure = "off",
  static = "on",
  gotags = ["bazel", "sqlite"],
)
<...>
```

As you can see both the gotags are specific in the go_test. The library gets pulled in through the embed of: `@tetrate_resolve_deps//pkg/db/pool:test_deps` which is an autogenerated `go_source` rule which has a "deps" of the actual library (we generate these with a repository rule so engineers don't have to manually list their dependencies in source files, and their build files. we don't wanna introduce too many workflow change :sweat_smile: ):

```
go_source(
  name = "test_deps",
  visibility = ["//visibility:public"],
  deps = ["@tetrate//pkg/db/pool:go_lib"],
)
```

When specifying the tags manually with the command line, the test passes:

```
bazelisk test //pkg/db/pool:go_test --define gotags=bazel,sqlite
INFO: Build option --define has changed, discarding analysis cache.
INFO: Analyzed target //pkg/db/pool:go_test (0 packages loaded, 7483 targets configured).
INFO: Found 1 test target...
INFO: From GoLink pkg/db/pool/go_test_/go_test:
/tmp/go-link-796005831/000010.o:sqlite3-binding.c:function unixDlOpen: warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
cgo-gcc-prolog:58: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
cgo-gcc-prolog:113: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
Target //pkg/db/pool:go_test up-to-date:
  bazel-out/k8-fastbuild-ST-d17813c235ce/bin/pkg/db/pool/go_test_/go_test
INFO: Elapsed time: 4.925s, Critical Path: 4.71s
INFO: 40 processes: 1 internal, 39 linux-sandbox.
INFO: Build completed successfully, 40 total actions
//pkg/db/pool:go_test                                           (cached) PASSED in 0.1s
```

### What did you expect to see?

That my build succeeds, either I can specify gotags on a `go_library`, or the gotags from a go_test rule will flow through to the dependencies triggering a rebuild thus allowing the test to pass. As specified in the <https://github.com/bazelbuild/rules_go/blob/master/go/core.rst#go_library> ` Files may be filtered at build time using Go build constraints.`

### What did you see instead?

Go tags seem to not be passed down to a go_library, and thus the build fails.

**Comment by Mythra** [comment] 2020-10-28 17:49
cc: @jayconrod as you seemed to have added the gotags attribute for `go_binary`/`go_test`. Perhaps you can shed some light on why `go_library` doesn't have that attribute and how we can configure multiple buildsettings to be exposed as tags.

**Comment by jayconrod** [comment] 2020-10-28 20:40
`gotags` is meant to apply to a binary and everything it depends on. It's meant to be analogous to `go build -tags`, which works the same way. There shouldn't be a way to specify tags per-package, so `go_library` doesn't have its own `gotags` attribute.

It sounds though like you have `gotags` set in `go_test`, and that's not showing up in a `go_library` dependency of `go_test`. That may be a bug. Could you post a more minimal example that reproduces that?

One small thing to note: when specifying tags on the command line, use `--@io_bazel_rules_go//go/config:tags` instead. `--define gotags` is deprecated and will be removed soon.

**Comment by Mythra** [comment] 2020-10-29 01:49
Okay that's what we thought, but after playing around with it more. It actually appears the issue _is_ with the select statement. <https://github.com/Mythra/rules_go_repro> is the smallest reproduction I could create. If you make the gotags just specified on the test rule, it does properly pass.  _I was originally thinking it wasn't this since cquery shows the tags being expanded correctly (and added together)._

So I guess this come comes to another question, how can I use select with gotags? I'll reword the issue, but it appears it does populate correctly without the select.

**Comment by jayconrod** [comment] 2020-10-29 14:48
I spent some time debugging this today, because it really seems like it should work.

Unfortunately, I don't have good news for you. It looks like Bazel Starlark transitions can't read attributes that were set with `select`. See [StarlarkRuleTransitionProvider.java](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/analysis/starlark/StarlarkRuleTransitionProvider.java;l=98).

For background, a Bazel *configuration* is a collection of build settings (`static = "on"`, `pure = "off"`, `gotags = ["sqlite"]` and so on). A transition is a dependency from a target in one configuration to another. There's a transition implementation function in Starlark that says which settings to change, based on attributes like `gotags`.

If that function can't access attributes set using `select`, then it can't completely perform the transition. The attribute appears not to exist, so the transition function ignores it.

I don't think there's anything I can do to help on the rules_go side. You could try opening an issue in bazelbuild/bazel asking for this to be implemented. I think if it were implemented, no change would be needed in rules_go.

**Comment by Mythra** [comment] 2020-10-29 15:04
@jayconrod thanks for looking into it! I really appreciate it, I'll look at opening an issue on bazel itself, and see what the outcome is.

**Comment by ZackButcher** [comment] 2020-10-29 17:13
https://github.com/bazelbuild/bazel/issues/12386

**Comment by jayconrod** [comment] 2020-11-09 21:00
Thanks for pursuing this on the Bazel side. I'll close this issue, since I don't think there's anything to do in rules_go.

**Closed by jayconrod** 2020-11-09 21:00 UTC
