### ISSUE TITLE
tool to auto generate WORKSPACE go_repository rules

### ISSUE THREAD

**Issue by kevinburkeotto** [bazelbuild/rules_go#897] opened 2017-10-11 16:25 UTC
One of the most tedious parts of getting a project set up on Bazel is grabbing HEAD of every project I import and adding the commit sha to the WORKSPACE.

It would be nice if there was a tool that had options for either "grab the latest version on the default branch of every dependency" or to convert from Gopkg.lock, if that exists, and could write out a valid WORKSPACE file.

**Comment by jayconrod** [comment] 2017-10-11 17:02
This is a huge pain point right now, and it's something I'd like to address very soon.

go/tools/wtool is the short term solution -- it adds a dependency on a single repository at HEAD. It is very simple, and it won't add recursive dependencies or update existing dependencies.

The long term solution will be to add some new commands to Gazelle: something like add-deps, update-deps, rm-deps. These *will* work recursively and will be able to update dependencies you already have and fetch dependencies you're already missing. #389 is the issue tracking this. This is a large complicated change.

#859 is a prerequisite; Gazelle needs to be able to index the import paths that are used and provided in a repository and use that index to resolve labels. Once that's done, Gazelle will need to be able to check what repositories Bazel knows about (either by querying Bazel or reading WORKSPACE), and determine which revisions are present.

#460 is another prerequisite. I'd like repositories added by Gazelle to have pre-generated build files. These could be inspected easily when Gazelle is updating the build files in the local repository. We'd like to avoid running Gazelle at build time inside repository rules.

Some new functionality I definitely want is being able to sync WORKSPACE with dependency manager lock files, at least with dep. Not sure if sync in both directions will be supported, but definitely toward WORKSPACE.

I'll close this issue as a duplicate of #389. I'll post a more complete proposal there once the prerequisites are out of the way.

**Closed by jayconrod** 2017-10-11 17:02 UTC
