### ISSUE TITLE
Issue with rules 0.6.0 and proto files in dependencies

### ISSUE THREAD

**Issue by ash2k** [bazelbuild/rules_go#900] opened 2017-10-12 01:36 UTC
Gazelle now generates proto rules but looks like some imports are incorrect? I'm not sure. Please take a look at error in this build: https://travis-ci.org/atlassian/smith/builds/286792771
```
ERROR: (10-12 00:15:16.022) /home/travis/gopath/src/github.com/atlassian/smith/vendor/k8s.io/apimachinery/pkg/apis/meta/v1alpha1/BUILD:57:1: no such package 'k8s.io/apimachinery/pkg/runtime': BUILD file not found on package path and referenced by '//vendor/k8s.io/apimachinery/pkg/apis/meta/v1alpha1:v1alpha1_go_proto'.
```
Error can be different from run to run but it is always about proto rules.

To reproduce this locally:
- clone the repo github.com/atlassian/smith
- checkout `update_rules` branch
- `make setup-ci` - will pull dependencies into `vendor`
- `bazel run //:gazelle-fix` to get rid of warnings
- `make test-ci` to try to run tests

p.s. another things that doesn't seem right is empty brackets in this message:
```
gazelle: found packages types () and descriptor () in /home/travis/gopath/src/github.com/atlassian/smith/vendor/github.com/gogo/protobuf/protobuf/google/protobuf
```

This happens using Bazel 0.6.1 on mac and on linux (travis).

**Comment by ash2k** [comment] 2017-10-12 01:41
I think the issue is that Gazelle generates proto rules which reference packages via "absolute" labels but they are in `vendor` directory actually. E.g. from `vendor/k8s.io/api/core/v1/BUILD`:
```
proto_library(
    name = "v1_proto",
    srcs = ["generated.proto"],
    visibility = ["//visibility:public"],
    deps = [
        "//k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1:v1beta1_proto",
        "//k8s.io/apimachinery/pkg/api/resource:resource_proto",
        "//k8s.io/apimachinery/pkg/apis/meta/v1:v1_proto",
        "//k8s.io/apimachinery/pkg/runtime:runtime_proto",
        "//k8s.io/apimachinery/pkg/runtime/schema:schema_proto",
        "//k8s.io/apimachinery/pkg/util/intstr:intstr_proto",
    ],
)
```
But `k8s.io/apimachinery` dependency is in my `vendor` directory and hence Bazel cannot find it.

Maybe Gazelle should prepend `//vendor/` if proto file is in `vendor` dir?

**Comment by jayconrod** [comment] 2017-10-12 14:34
That's pretty much exactly the problem. Gazelle should account for vendored external mode when resolving proto dependencies, both on `proto_library` and `go_proto_library` / `go_grpc_library`.

Related: #888

**Comment by ash2k** [comment] 2017-10-17 06:35
I tried updating to the latest commit (a5ad22c6a5bede85e35088b4a3a2a5dd7fa13f55) but it now fails with some compilation error:
```console
make test
goimports -w=true -d $(find . -type f -name '*.go' -not -path "./vendor/*" -not -path "./build/*" -not -path './pkg/client/clientset_generated/*' -not -name 'zz_generated.*')
bazel run //:gazelle
INFO: Found 1 target...
Target //:gazelle up-to-date:
  bazel-bin/gazelle_script.bash
  bazel-bin/gazelle
INFO: Elapsed time: 0.333s, Critical Path: 0.12s

INFO: Running command line: bazel-bin/gazelle
gazelle: found packages types () and descriptor () in /Users/mmazurskiy/gopath/src/github.com/atlassian/smith/vendor/github.com/gogo/protobuf/protobuf/google/protobuf
# TODO: why does it build binaries and docker in cmd?
bazel test \
                --test_env=KUBE_PATCH_CONVERSION_DETECTOR=true \
                --test_env=KUBE_CACHE_MUTATION_DETECTOR=true \
                -- ... -cmd/... -vendor/...
INFO: Found 26 targets and 7 test targets...
INFO: From Compiling external/com_google_protobuf/src/google/protobuf/compiler/js/embed.cc [for host]:
external/com_google_protobuf/src/google/protobuf/compiler/js/embed.cc:37:12: warning: unused variable 'output_file' [-Wunused-const-variable]
const char output_file[] = "well_known_types_embed.cc";
           ^
1 warning generated.
INFO: From Linking external/com_google_protobuf/libprotobuf_lite.a [for host]:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: bazel-out/host/bin/external/com_google_protobuf/libprotobuf_lite.a(arenastring.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: bazel-out/host/bin/external/com_google_protobuf/libprotobuf_lite.a(atomicops_internals_x86_msvc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: bazel-out/host/bin/external/com_google_protobuf/libprotobuf_lite.a(io_win32.o) has no symbols
INFO: From Linking external/com_google_protobuf/libprotobuf.a [for host]:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: bazel-out/host/bin/external/com_google_protobuf/libprotobuf.a(gzip_stream.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: bazel-out/host/bin/external/com_google_protobuf/libprotobuf.a(error_listener.o) has no symbols
INFO: From Linking external/com_github_google_protobuf/libprotobuf.a [for host]:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: bazel-out/host/bin/external/com_github_google_protobuf/libprotobuf.a(gzip_stream.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: bazel-out/host/bin/external/com_github_google_protobuf/libprotobuf.a(error_listener.o) has no symbols
INFO: From Linking external/com_github_google_protobuf/libprotobuf_lite.a [for host]:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: bazel-out/host/bin/external/com_github_google_protobuf/libprotobuf_lite.a(arenastring.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: bazel-out/host/bin/external/com_github_google_protobuf/libprotobuf_lite.a(atomicops_internals_x86_msvc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: bazel-out/host/bin/external/com_github_google_protobuf/libprotobuf_lite.a(io_win32.o) has no symbols
INFO: From Compiling external/com_github_google_protobuf/src/google/protobuf/compiler/js/embed.cc [for host]:
external/com_github_google_protobuf/src/google/protobuf/compiler/js/embed.cc:37:12: warning: unused variable 'output_file' [-Wunused-const-variable]
const char output_file[] = "well_known_types_embed.cc";
           ^
1 warning generated.
ERROR: /Users/mmazurskiy/gopath/src/github.com/atlassian/smith/vendor/k8s.io/apimachinery/pkg/runtime/BUILD:88:1: Generating Descriptor Set proto_library //vendor/k8s.io/apimachinery/pkg/runtime:runtime_proto failed (Exit 1).
k8s.io/apimachinery/pkg/util/intstr/generated.proto: File not found.
vendor/k8s.io/apimachinery/pkg/runtime/generated.proto: Import "k8s.io/apimachinery/pkg/util/intstr/generated.proto" was not found or had errors.
INFO: Elapsed time: 143.622s, Critical Path: 9.85s
//examples/sleeper/pkg/apis/sleeper/v1:go_default_test                NO STATUS
//pkg/apis/smith/v1:go_default_test                                   NO STATUS
//pkg/client/smart:go_default_test                                    NO STATUS
//pkg/controller:go_default_test                                      NO STATUS
//pkg/resources:go_default_test                                       NO STATUS
//pkg/speccheck:go_default_test                                       NO STATUS
//pkg/util/graph:go_default_test                                      NO STATUS

Executed 0 out of 7 tests: 7 were skipped.
make: *** [test-ci] Error 1
```

I'm on macOS Sierra 10.12.6 with latest XCode and command line tools installed.

p.s. I cannot opt-out from this proto rule generation using the gazelle rule (no attribute `proto` for the rule). It is not supposed to work or I'm doing it wrong?

**Comment by ash2k** [comment] 2017-10-17 06:41
It fails in some other weird way on Travis https://travis-ci.org/atlassian/smith/builds/288902981

**Comment by jayconrod** [comment] 2017-10-18 17:23
The error is actually coming from the proto compiler. It expects paths to imported protos to be relative to the repo root. Gazelle adds `//vendor` to the dep in the `proto_library` rule, but we haven't told protoc to look for protos in vendor/.

@ianthehat What's the most reasonable way to handle this? I'm sure we could hack something up in `go_proto_library`, but it doesn't seem like a good idea.

**Comment by ianthehat** [comment] 2017-10-18 18:32
I don't think there is anything we can directly do, the problem is in the proto_library rule which is totally outside our control.
You would need to get an extra option on that rule to control the effective path of a proto file.
The only alternative is to use the trick where you generate a new repository in a repository rule, and copy the proto file to the appropriate path and generate the proto_library rule in there instead.
It would be easier to just change the import path in the proto itself to be "correct" or to stop using vendoring for that repository

**Comment by tomwilkie** [comment] 2017-10-19 13:11
Does this effectively mean I can't vendor libraries containing protos which themselves import protos from other vendored libraries?  When I used make I would add `-Ivendor/` to the generation; perhaps we can add something similar to `proto_library`?

**Comment by tomwilkie** [comment] 2017-10-19 13:12
Already an issue for this is seems: https://github.com/bazelbuild/bazel/issues/3867

**Comment by jayconrod** [comment] 2017-10-19 14:15
> Does this effectively mean I can't vendor libraries containing protos which themselves import protos from other vendored libraries?

It seems that way. Ideally, `proto_library` should accept some attributes that let you modify imports like `-Ivendor/` as you suggested or something like the proposal in the bug.

Some workarounds are possible. You could patch the proto files in vendor, or you could symlink or copy them into places that Bazel expects.

**Comment by jayconrod** [comment] 2017-12-27 19:52
Closing old Gazelle issues. If something still needs to be fixed in Gazelle itself (as opposed to `proto_library` or `go_proto_library`), please file a new issue at bazelbuild/bazel-gazelle.

**Closed by jayconrod** 2017-12-27 19:52 UTC
Labels: bug, gazelle, proto
