### ISSUE TITLE
Declaration duplications in proto GRPC reflection

### ISSUE THREAD

**Issue by scorsi** [bazelbuild/rules_go#2564] opened 2020-07-10 18:03 UTC
### What version of rules_go are you using?

v0.23.3

### What version of gazelle are you using?

v0.21.1

### What version of Bazel are you using?

3.3.0-homebrew

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

MacOS 10.15.5 Darwin 64bits 

### Any other potentially useful information about your toolchain?

rules_proto commit 97d8af4dc474595af3900dd85cb3a29ad28cc313 (lastest)

### What did you do?

```go
package main

import (
	"context"
	"log"
	"net"

	pb "github.com/adfinitas-app/grpcKubeTraefikBazelTest/helloworld/helloworld"
	"google.golang.org/grpc"
	"google.golang.org/grpc/reflection"
)

const (
	port = ":50051"
)

// server is used to implement helloworld.GreeterServer.
type server struct {
	pb.UnimplementedGreeterServer
}

// SayHello implements helloworld.GreeterServer
func (s *server) SayHello(ctx context.Context, in *pb.HelloRequest) (*pb.HelloReply, error) {
	log.Printf("Received: %v", in.GetName())
	return &pb.HelloReply{Message: "Hello " + in.GetName() + "!"}, nil
}

func main() {
	lis, err := net.Listen("tcp", port)
	if err != nil {
		log.Fatalf("failed to listen: %v", err)
	}
	s := grpc.NewServer()
	pb.RegisterGreeterServer(s, &server{})
	reflection.Register(s)
	if err := s.Serve(lis); err != nil {
		log.Fatalf("failed to serve: %v", err)
	}
}
```

You can check out the full code right [here](https://github.com/scorsi/grpc-kube-traefik-bazel-test).

Maybe I did something wrong somewhere in my project.

### What did you expect to see?

Just to compile. :) 

### What did you see instead?

<details><summary><code>bazel run //greater-server:binary</code> Output</summary><br><pre>
/private/var/tmp/_bazel_scorsi/06e4013400bb27319c52fb9c7b1585dd/sandbox/darwin-sandbox/6410/execroot/grpc_kube_bazel_test/external/org_golang_google_grpc/reflection/grpc_reflection_v1alpha/reflection_grpc.pb.go:19:6: ServerReflectionClient redeclared in this block
        previous declaration at /private/var/tmp/_bazel_scorsi/06e4013400bb27319c52fb9c7b1585dd/sandbox/darwin-sandbox/6410/execroot/grpc_kube_bazel_test/bazel-out/darwin-fastbuild/bin/external/org_golang_google_grpc/reflection/grpc_reflection_v1alpha/grpc_reflection_v1alpha_go_proto_/google.golang.org/grpc/reflection/grpc_reflection_v1alpha/reflection.pb.go:898:6
/private/var/tmp/_bazel_scorsi/06e4013400bb27319c52fb9c7b1585dd/sandbox/darwin-sandbox/6410/execroot/grpc_kube_bazel_test/external/org_golang_google_grpc/reflection/grpc_reflection_v1alpha/reflection_grpc.pb.go:25:6: serverReflectionClient redeclared in this block
        previous declaration at /private/var/tmp/_bazel_scorsi/06e4013400bb27319c52fb9c7b1585dd/sandbox/darwin-sandbox/6410/execroot/grpc_kube_bazel_test/bazel-out/darwin-fastbuild/bin/external/org_golang_google_grpc/reflection/grpc_reflection_v1alpha/grpc_reflection_v1alpha_go_proto_/google.golang.org/grpc/reflection/grpc_reflection_v1alpha/reflection.pb.go:902:6
/private/var/tmp/_bazel_scorsi/06e4013400bb27319c52fb9c7b1585dd/sandbox/darwin-sandbox/6410/execroot/grpc_kube_bazel_test/external/org_golang_google_grpc/reflection/grpc_reflection_v1alpha/reflection_grpc.pb.go:29:6: NewServerReflectionClient redeclared in this block
        previous declaration at /private/var/tmp/_bazel_scorsi/06e4013400bb27319c52fb9c7b1585dd/sandbox/darwin-sandbox/6410/execroot/grpc_kube_bazel_test/bazel-out/darwin-fastbuild/bin/external/org_golang_google_grpc/reflection/grpc_reflection_v1alpha/grpc_reflection_v1alpha_go_proto_/google.golang.org/grpc/reflection/grpc_reflection_v1alpha/reflection.pb.go:906:61
/private/var/tmp/_bazel_scorsi/06e4013400bb27319c52fb9c7b1585dd/sandbox/darwin-sandbox/6410/execroot/grpc_kube_bazel_test/external/org_golang_google_grpc/reflection/grpc_reflection_v1alpha/reflection_grpc.pb.go:42:6: ServerReflection_ServerReflectionInfoClient redeclared in this block
        previous declaration at /private/var/tmp/_bazel_scorsi/06e4013400bb27319c52fb9c7b1585dd/sandbox/darwin-sandbox/6410/execroot/grpc_kube_bazel_test/bazel-out/darwin-fastbuild/bin/external/org_golang_google_grpc/reflection/grpc_reflection_v1alpha/grpc_reflection_v1alpha_go_proto_/google.golang.org/grpc/reflection/grpc_reflection_v1alpha/reflection.pb.go:919:6
/private/var/tmp/_bazel_scorsi/06e4013400bb27319c52fb9c7b1585dd/sandbox/darwin-sandbox/6410/execroot/grpc_kube_bazel_test/external/org_golang_google_grpc/reflection/grpc_reflection_v1alpha/reflection_grpc.pb.go:48:6: serverReflectionServerReflectionInfoClient redeclared in this block
        previous declaration at /private/var/tmp/_bazel_scorsi/06e4013400bb27319c52fb9c7b1585dd/sandbox/darwin-sandbox/6410/execroot/grpc_kube_bazel_test/bazel-out/darwin-fastbuild/bin/external/org_golang_google_grpc/reflection/grpc_reflection_v1alpha/grpc_reflection_v1alpha_go_proto_/google.golang.org/grpc/reflection/grpc_reflection_v1alpha/reflection.pb.go:925:6
/private/var/tmp/_bazel_scorsi/06e4013400bb27319c52fb9c7b1585dd/sandbox/darwin-sandbox/6410/execroot/grpc_kube_bazel_test/external/org_golang_google_grpc/reflection/grpc_reflection_v1alpha/reflection_grpc.pb.go:67:6: ServerReflectionServer redeclared in this block
        previous declaration at /private/var/tmp/_bazel_scorsi/06e4013400bb27319c52fb9c7b1585dd/sandbox/darwin-sandbox/6410/execroot/grpc_kube_bazel_test/bazel-out/darwin-fastbuild/bin/external/org_golang_google_grpc/reflection/grpc_reflection_v1alpha/grpc_reflection_v1alpha_go_proto_/google.golang.org/grpc/reflection/grpc_reflection_v1alpha/reflection.pb.go:942:6
/private/var/tmp/_bazel_scorsi/06e4013400bb27319c52fb9c7b1585dd/sandbox/darwin-sandbox/6410/execroot/grpc_kube_bazel_test/external/org_golang_google_grpc/reflection/grpc_reflection_v1alpha/reflection_grpc.pb.go:74:6: UnimplementedServerReflectionServer redeclared in this block
        previous declaration at /private/var/tmp/_bazel_scorsi/06e4013400bb27319c52fb9c7b1585dd/sandbox/darwin-sandbox/6410/execroot/grpc_kube_bazel_test/bazel-out/darwin-fastbuild/bin/external/org_golang_google_grpc/reflection/grpc_reflection_v1alpha/grpc_reflection_v1alpha_go_proto_/google.golang.org/grpc/reflection/grpc_reflection_v1alpha/reflection.pb.go:947:6
/private/var/tmp/_bazel_scorsi/06e4013400bb27319c52fb9c7b1585dd/sandbox/darwin-sandbox/6410/execroot/grpc_kube_bazel_test/external/org_golang_google_grpc/reflection/grpc_reflection_v1alpha/reflection_grpc.pb.go:81:6: RegisterServerReflectionServer redeclared in this block
        previous declaration at /private/var/tmp/_bazel_scorsi/06e4013400bb27319c52fb9c7b1585dd/sandbox/darwin-sandbox/6410/execroot/grpc_kube_bazel_test/bazel-out/darwin-fastbuild/bin/external/org_golang_google_grpc/reflection/grpc_reflection_v1alpha/grpc_reflection_v1alpha_go_proto_/google.golang.org/grpc/reflection/grpc_reflection_v1alpha/reflection.pb.go:954:57
/private/var/tmp/_bazel_scorsi/06e4013400bb27319c52fb9c7b1585dd/sandbox/darwin-sandbox/6410/execroot/grpc_kube_bazel_test/external/org_golang_google_grpc/reflection/grpc_reflection_v1alpha/reflection_grpc.pb.go:85:6: _ServerReflection_ServerReflectionInfo_Handler redeclared in this block
        previous declaration at /private/var/tmp/_bazel_scorsi/06e4013400bb27319c52fb9c7b1585dd/sandbox/darwin-sandbox/6410/execroot/grpc_kube_bazel_test/bazel-out/darwin-fastbuild/bin/external/org_golang_google_grpc/reflection/grpc_reflection_v1alpha/grpc_reflection_v1alpha_go_proto_/google.golang.org/grpc/reflection/grpc_reflection_v1alpha/reflection.pb.go:958:96
/private/var/tmp/_bazel_scorsi/06e4013400bb27319c52fb9c7b1585dd/sandbox/darwin-sandbox/6410/execroot/grpc_kube_bazel_test/external/org_golang_google_grpc/reflection/grpc_reflection_v1alpha/reflection_grpc.pb.go:89:6: ServerReflection_ServerReflectionInfoServer redeclared in this block
        previous declaration at /private/var/tmp/_bazel_scorsi/06e4013400bb27319c52fb9c7b1585dd/sandbox/darwin-sandbox/6410/execroot/grpc_kube_bazel_test/bazel-out/darwin-fastbuild/bin/external/org_golang_google_grpc/reflection/grpc_reflection_v1alpha/grpc_reflection_v1alpha_go_proto_/google.golang.org/grpc/reflection/grpc_reflection_v1alpha/reflection.pb.go:962:6
/private/var/tmp/_bazel_scorsi/06e4013400bb27319c52fb9c7b1585dd/sandbox/darwin-sandbox/6410/execroot/grpc_kube_bazel_test/external/org_golang_google_grpc/reflection/grpc_reflection_v1alpha/reflection_grpc.pb.go:89:6: too many errors
</pre></details>

**Comment by jayconrod** [comment] 2020-07-10 18:53
This looks like a duplicate of bazelbuild/bazel-gazelle#819.

**Closed by jayconrod** 2020-07-10 18:53 UTC

**Comment by scorsi** [comment] 2020-07-10 18:57
Sorry, I really tried to find the issue and I didn't thought about gazelle.

Thanks !

**Comment by jayconrod** [comment] 2020-07-10 19:01
No worries! From the error, it's not always clear what repo an issue should go to. That issue was also originally filed here. In this case, the build files generated by Gazelle for gRPC are causing conflicts.
