### ISSUE TITLE
Multiple providers of the same importpaths

### ISSUE THREAD

**Issue by qzmfranklin** [bazelbuild/rules_go#2186] opened 2019-08-20 08:37 UTC
### What version of rules_go are you using?
0.19.1

### What version of gazelle are you using?

0.18.1

### What version of Bazel are you using?

0.28.0
### What operating system and processor architecture are you using?
Ubuntu 18.04.2

### Any other potentially useful information about your toolchain?

clang compiler
but fairly standard
### What did you see instead?
```txt
link: warning: package "github.com/golang/protobuf/ptypes/struct" is provided by more than one rule:
    @com_github_golang_protobuf//ptypes/struct:go_default_library
    @io_bazel_rules_go//proto/wkt:struct_go_proto
Set "importmap" to different paths in each library.
This will be an error in the future.
```

**Comment by qzmfranklin** [comment] 2019-08-20 08:38
The `importmap` attribute is generated by gazelle. I have very little control over it.

Not sure how I can proceed without breaking myself in the future when the libraries are updated.

Help is appreciated.

**Comment by jayconrod** [comment] 2019-08-20 13:59
This is a legitimate warning. It should be changed to an error at some point. Two libraries implement the same proto. Protos have a global registry, so these shouldn't be mixed.

[Avoiding conflicts](https://github.com/bazelbuild/rules_go/blob/master/proto/core.rst#avoiding-conflicts) has more advice on this. The short version is try to either use `go_proto_library` or `go_library` with pre-generated .pb.go files exclusively. Gazelle will try to do the latter by default, but you can add `# gazelle:proto disable_global` to your root build file and `build_file_proto_mode = "disable_global"` to each `go_repository` rule to get the latter behavior.

Closing the issue because it's not a bug, but I'm happy to answer any questions.

**Closed by jayconrod** 2019-08-20 13:59 UTC
