### ISSUE TITLE
gazelle can't handle gopkg.in/yaml.v2

### ISSUE THREAD

**Issue by jeb2239** [bazelbuild/rules_go#947] opened 2017-10-23 00:27 UTC
For some reason gazelle doesn't generate a dependency on gopkg.in/yaml.v2.

```
bazel build //src/...
Extracting Bazel installation...
............
INFO: Analysed 3 targets (40 packages loaded).
INFO: Found 3 targets...
ERROR: /home/barriosj/.cache/bazel/_bazel_barriosj/75347ef6914677177b441e22d1f94b55/external/com_github_spf13_viper/BUILD.bazel:3:1: GoCompile external/com_github_spf13_viper/~normal~go_default_library~/github.com/spf13/viper.a failed (Exit 1)
2017/10/22 20:24:52 missing strict dependencies:
	external/com_github_spf13_viper/util.go: import of gopkg.in/yaml.v2, which is not a direct dependency
INFO: Elapsed time: 12.272s, Critical Path: 2.01s
FAILED: Build did NOT complete successfully
Makefile:2: recipe for target 'all' failed
```

**Comment by jayconrod** [comment] 2017-10-23 14:37
I couldn't reproduce this. Are you using any unusual options in `go_repository`? Could you post a WORKSPACE file that reproduces this?

Here's my test WORKSPACE file for reference.

```bzl
local_repository(
    name = "io_bazel_rules_go",
    path = "/usr/local/google/home/jayconrod/Code/rules_go",
)

load("@io_bazel_rules_go//go:def.bzl", "go_repository", "go_rules_dependencies", "go_register_toolchains")

go_rules_dependencies()

go_register_toolchains()

go_repository(
    name = "com_github_spf13_viper",
    commit = "8ef37cbca71638bf32f3d5e194117d4cb46da163",
    importpath = "github.com/spf13/viper",
)

go_repository(
    name = "in_gopkg_yaml_v2",
    commit = "eb3733d160e74a9c7e442f435eb3bea458e1d19f",
    importpath = "gopkg.in/yaml.v2",
)

go_repository(
    name = "com_github_pelletier_go_toml",
    commit = "8c31c2ec65b208cc2ad1608bf25a3ff91adf1944",
    importpath = "github.com/pelletier/go-toml",
)

go_repository(
    name = "com_github_magiconair_properties",
    commit = "8d7837e64d3c1ee4e54a880c5a920ab4316fc90a",
    importpath = "github.com/magiconair/properties",
)

go_repository(
    name = "com_github_mitchellh_mapstructure",
    commit = "06020f85339e21b2478f756a78e295255ffa4d6a",
    importpath = "github.com/mitchellh/mapstructure",
)

go_repository(
    name = "com_github_fsnotify_fsnotify",
    commit = "4da3e2cfbabc9f751898f250b49f2439785783a1",
    importpath = "github.com/fsnotify/fsnotify",
)

go_repository(
    name = "com_github_hashicorp_hcl",
    commit = "23c074d0eceb2b8a5bfdbb271ab780cde70f05a8",
    importpath = "github.com/hashicorp/hcl",
)

go_repository(
    name = "com_github_spf13_jwalterweatherman",
    commit = "12bd96e66386c1960ab0f74ced1362f66f552f7b",
    importpath = "github.com/spf13/jwalterweatherman",
)

go_repository(
    name = "com_github_spf13_afero",
    commit = "5660eeed305fe5f69c8fc6cf899132a459a97064",
    importpath = "github.com/spf13/afero",
)

go_repository(
    name = "com_github_spf13_cast",
    commit = "acbeb36b902d72a7a4c18e8f3241075e7ab763e4",
    importpath = "github.com/spf13/cast",
)

go_repository(
    name = "com_github_spf13_pflag",
    commit = "97afa5e7ca8a08a383cb259e06636b5e2cc7897f",
    importpath = "github.com/spf13/pflag",
)

go_repository(
    name = "org_golang_x_sys",
    commit = "8dbc5d05d6edcc104950cc299a1ce6641235bc86",
    importpath = "golang.org/x/sys",
)
```

**Comment by jeb2239** [comment] 2017-10-23 17:43
Sure using this project https://github.com/jeb2239/go_practice_code
with this fork of the rules where the only difference is the sources of the rules dependencies. https://github.com/jeb2239/rules_go

**Comment by jeb2239** [comment] 2017-10-23 17:44
The interesting thing is that this works with internet connection but not without. While if I remove that dependency this setup works fine without internet connection.

**Comment by jayconrod** [comment] 2017-10-24 15:19
I got this to work with a few modifications to WORKSPACE. This was with rules_go at master. I didn't try disabling the network.

* Changed `root_repos_remote` to my own `GOPATH`. Also updated all the local paths that aren't built with that string.
* Grepped for `importpath` and ran `go get -u` on all of those.
* Deleted the extra `org_golang_x_tools` rule. This shouldn't make a difference though.

Could you try running `bazel clean --expunge` and `go get -u` on all of the dependencies before running `bazel build //src/...` again? Maybe one of the repositories got into a weird state. I got some confusing results when I was missing some things from my `GOPATH`, so maybe some repository got into a weird state.

**Comment by jayconrod** [comment] 2017-10-24 15:28
I think I know what is happening: Gazelle uses the network when it resolves import paths. This is needed to find the repository prefix for each import. This is skipped for well known servers. For example, with `github.com/spf13/viper`, we know the prefix since we know that's how GitHub URLs are structured. gopkg.in is not one of these well known servers, so if the network is down when Gazelle generates build files, Gazelle would not figure that one out.

Gazelle has a command line flag, `-known_import` which can be used to add a known prefix manually. This can be repeated. It's not exposed in `go_repository` though.

As a workaround, just make sure the network is up when dependencies are fetched. This is when Gazelle runs inside `go_repository`. Alternatively, you could generate build files in each of those repositories ahead of time, then reference them with `local_repository` instead of `go_repository`.

**Comment by jayconrod** [comment] 2017-12-27 19:55
Closing old Gazelle issues. If anything still needs to be done for this, please file a new issue at bazelbuild/bazel-gazelle.

**Closed by jayconrod** 2017-12-27 19:55 UTC
Labels: gazelle
