### ISSUE TITLE
protoc execution results in stripped protobuf comments.

### ISSUE THREAD

**Issue by howardjohn** [bazelbuild/rules_go#2646] opened 2020-09-09 18:11 UTC
### What version of rules_go are you using?

v0.24.1

### What version of gazelle are you using?

N/A

### What version of Bazel are you using?

Build label: 3.5.0

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

x86_64 GNU/Linux

### Any other potentially useful information about your toolchain?

Reproduction repo: https://github.com/howardjohn/bazel-proto-test

### What did you do?

Reproduction repo: https://github.com/howardjohn/bazel-proto-test

Use protoc directly:
```
$ protoc --go_out=plugins=grpc:. echo.proto
$ cat echo.pb.go | rg 'ServerFirst ' -C 1
        // If true, requests will not be sent until magic string is received
        ServerFirst bool `protobuf:"varint,8,opt,name=serverFirst,proto3" json:"serverFirst,omitempty"`
        // If non-empty, make the request with the corresponding cert and key.
```
You can see comments are preserved

Using bazel:
```
$ bazel build //:echo_go_proto
INFO: Analyzed target //:echo_go_proto (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //:echo_go_proto up-to-date:
  bazel-bin/echo_go_proto.a
INFO: Elapsed time: 0.201s, Critical Path: 0.08s
INFO: 1 process: 1 linux-sandbox.
INFO: Build completed successfully, 2 total actions
$ cat bazel-out/k8-fastbuild/bin/echo_go_proto_/foo/echo.pb.go | rg 'ServerFirst ' -C 1
        Http2         bool      `protobuf:"varint,7,opt,name=http2,proto3" json:"http2,omitempty"`
        ServerFirst   bool      `protobuf:"varint,8,opt,name=serverFirst,proto3" json:"serverFirst,omitempty"`
        Cert          string    `protobuf:"bytes,10,opt,name=cert,proto3" json:"cert,omitempty"`
```

You can see comments are stripped.

Running bazel's protoc directly gives the same results of my own protoc indicating its not some version mismatch (ie `./bazel-out/k8-opt-exec-2B5CBBC6/bin/external/com_google_protobuf/protoc --go_out=plugins=grpc:. echo.proto`).

Running the command bazel runs (from `-s`):

```
bazel-out/k8-opt-exec-2B5CBBC6/bin/external/io_bazel_rules_go/go/tools/builders/go-protoc-bin_/go-protoc-bin -protoc bazel-out/k8-opt-exec-2B5CBBC6/bin/external/com_google_protobuf/protoc -importpath foo -out_path bazel-out/k8-fastbuild/bin/echo_go_proto_/ -plugin bazel-out/k8-opt-exec-2B5CBBC6/bin/external/com_github_golang_protobuf/protoc-gen-go/protoc-gen-go_/protoc-gen-go -descriptor_set bazel-out/k8-fastbuild/bin/echo_proto-descriptor-set.proto.bin -expected bazel-out/k8-fastbuild/bin/echo_go_proto_/foo/echo.pb.go -import 'echo.proto=foo' echo.proto
```
Does result in the comments stripped.

It seems like the bazel invocation is using this `go-protoc-bin` wrapper which is the source of our issues.

### What did you expect to see?

Comments are preserved.

### What did you see instead?

Comments are stripped.

**Comment by howardjohn** [comment] 2020-09-09 18:14
Root cause seems to be the descriptor_set/descriptor_set_in flag passed to protoc

**Comment by howardjohn** [comment] 2020-09-09 18:17
Seems --experimental_proto_descriptor_sets_include_source_info will do this. perhaps this is just a documentation issue then

**Comment by jayconrod** [comment] 2020-09-10 12:45
Duplicate of #1519

**Closed by jayconrod** 2020-09-10 12:45 UTC
