### ISSUE TITLE
Crossbuild circular dependency

### ISSUE THREAD

**Issue by achew22** [bazelbuild/rules_go#1238] opened 2018-01-13 01:23 UTC
```
bazel build --config=release --experimental_platforms=@io_bazel_rules_go//go/toolchain:linux_amd64 //ibazel:ibazel
WARNING: /home/achew22/.cache/bazel/_bazel_achew22/378856566cc5ab2d8fea39cb4a335e93/external/com_github_bazelbuild_bazel_integration_testing/WORKSPACE:1: Workspace name in /home/achew22/.cache/bazel/_bazel_achew22/378856566cc5ab2d8fea39cb4a335e93/external/com_github_bazelbuild_bazel_integration_testing/WORKSPACE (@build_bazel_integration_testing) does not match the name given in the repository's definition (@com_github_bazelbuild_bazel_integration_testing); this will cause a build error in future versions
ERROR: /home/achew22/.cache/bazel/_bazel_achew22/378856566cc5ab2d8fea39cb4a335e93/external/io_bazel_rules_go/go/toolchain/BUILD.bazel:11:1: in platform rule @io_bazel_rules_go//go/toolchain:linux_amd64: cycle in dependency graph:
    //ibazel:ibazel
.-> @io_bazel_rules_go//go/toolchain:linux_amd64
|   @io_bazel_rules_go//go/toolchain:amd64
`-- @io_bazel_rules_go//go/toolchain:linux_amd64
This cycle occurred because of a configuration option
ERROR: Analysis of target '//ibazel:ibazel' failed; build aborted
INFO: Elapsed time: 0.553s
FAILED: Build did NOT complete successfully (1 packages loaded)
```

You can test it using the release.sh script I created in this PR: https://github.com/bazelbuild/bazel-watcher/pull/115.

I read through the release notes/commit log and didn't see anything around changing the `--experimental_platform` flag but my theory is that I'm doing something wrong. Do you have any ideas?

**Comment by ianthehat** [comment] 2018-01-13 04:25
Which version of bazel? That was a known issue with 0.9, but should have been fixed in the 0.10 version.
See #1161

**Comment by achew22** [comment] 2018-01-13 04:43
That fixed the immediate issue. You're the best @ianthehat! I'm now getting a slightly different error.

```
$ bazel build --config=release --experimental_platforms=@io_bazel_rules_go//go/toolchain:darwin_amd64 //ibazel:ibazel
WARNING: /home/achew22/.cache/bazel/_bazel_achew22/378856566cc5ab2d8fea39cb4a335e93/external/com_github_bazelbuild_bazel_integration_testing/WORKSPACE:1: Workspace name in /home/achew22/.cache/bazel/_bazel_achew22/378856566cc5ab2d8fea39cb4a335e93/external/com_github_bazelbuild_bazel_integration_testing/WORKSPACE (@build_bazel_integration_testing) does not match the name given in the repository's definition (@com_github_bazelbuild_bazel_integration_testing); this will cause a build error in future versions
DEBUG: /home/achew22/.cache/bazel/_bazel_achew22/378856566cc5ab2d8fea39cb4a335e93/external/io_bazel_rules_go/proto/go_proto_library.bzl:253:3: DEPRECATED: proto:go_proto_library.bzl#go_proto_library is no longer supported, please use proto:def.bzl#go_proto_library
ERROR: While resolving toolchains for target @go_stdlib_plan9_386_pure_race//:go_stdlib_plan9_386_pure_race: no matching toolchains found for types @io_bazel_rules_go//go:bootstrap_toolchain
ERROR: Analysis of target '//ibazel:ibazel' failed; build aborted: no matching toolchains found for types @io_bazel_rules_go//go:bootstrap_toolchain
INFO: Elapsed time: 1.114s
FAILED: Build did NOT complete successfully (0 packages loaded)
```

**Comment by ianthehat** [comment] 2018-01-13 04:51
It's right, there are no matching toolchains for pure_race, because that's not a legal mode
The go standard library does not support compiling in both pure and race because the race detector itself needs cgo
I am surprised you don't get a more useful error than that somewhere earlier in the build though.

**Comment by achew22** [comment] 2018-01-13 04:52
Interestingly `bazel build --config=release --experimental_platforms=@io_bazel_rules_go//go/toolchain:linux_amd64 //ibazel:ibazel` works. Does that change you diagnosis at all?

**Comment by ianthehat** [comment] 2018-01-13 04:55
What's your host platform?
My guess, you are building a target that is in race mode and cross compilation is turning on pure, so you are implicitly building it in pure_race mode which does not work.

**Comment by achew22** [comment] 2018-01-13 05:09
`uname -a` reports `Linux lappy 4.10.8-041008-generic #201703310531 SMP Fri Mar 31 09:33:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`. I'm not sure I understand how its getting put into race mode. I only have `pure = "on"` set in the build file. is `@io_bazel_rules_go//go/toolchain:linux_amd64` implicitly race?

**Comment by jayconrod** [comment] 2018-08-14 20:00
@achew22 I've been going through some old issues. I tried but couldn't reproduce this with the command:

```
bazel build --platforms=@io_bazel_rules_go//go/toolchain:darwin_amd64 //ibazel
```

(My host platform is `linux_amd64`).

I'm going to close this as inactive, but please reopen if you're still seeing this.

**Closed by jayconrod** 2018-08-14 20:00 UTC
