### ISSUE TITLE
Open up package visibility of grpc internal

### ISSUE THREAD

**Issue by rickypai** [bazelbuild/rules_go#1971] opened 2019-02-28 18:01 UTC
Currently, the gazelle patch for grpc-go hides the visibility of grpc internal packages:

https://github.com/bazelbuild/rules_go/blob/72dff4e33d24aac4953ee794815dc569af0d8093/third_party/org_golang_google_grpc-gazelle.patch#L1596

This causes build errors in tests against our own implementations of grpc balancer interfaces that requires grpc internals to execute:

```
ERROR: target '@org_golang_google_grpc//internal/transport:go_default_library' is not visible from target '//rpc/grpc/balancer:go_default_test'. Check the visibility declaration of the former target if you think the dependency is legitimate
```

I think the gazelle patches should not hide the visibility of those packages, since they'd still be visible should one import them with vanilla go.

**Comment by jayconrod** [comment] 2019-02-28 18:11
Where are you importing that package from? cmd/go should block anyone outside of `google.golang.org/grpc` from importing anything in `google.golang.org/grpc/internal`. Gazelle maps that constraint to Bazel visibility rules.

**Comment by rickypai** [comment] 2019-02-28 18:15
I spoke too soon... we discovered this when attempting to upgrade `grpc-go` to a version that moved the transport implementation to `internal` directory in a project that was already built by `rules_go`. I was under the impression that vanilla go did not support package visibility, but seems like it does: https://golang.org/doc/go1.4#internalpackages

**Comment by jayconrod** [comment] 2019-02-28 21:20
Ok, cool. I'll close this issue, since it seems like everything is working as intended.

If you find you need to override visibility, you can override `org_golang_google_grpc` and other dependencies introduced by `go_rules_dependencies` with your own rules, and you can modify build files generated by Gazelle using `patches` (`go_repository` supports the same patch arguments as `http_archive` and `git_repository`). Be careful though obviously -- internal packages have no compatibility guarantees.

**Closed by jayconrod** 2019-02-28 21:20 UTC

**Comment by rickypai** [comment] 2019-03-01 04:41
sorry for the noise and thanks for the info for potentially how to resolve this.
