### ISSUE TITLE
filename or extension to long on windows x64

### ISSUE THREAD

**Issue by JohnnyS318** [bazelbuild/rules_go#2768] opened 2020-12-23 12:42 UTC
### What version of rules_go are you using?
v0.25.0

### What version of gazelle are you using?
v0.22.2

### What version of Bazel are you using?
bazel 3.7.1

### Does this issue reproduce with the latest releases of all the above?
yes

### What operating system and processor architecture are you using?
Windows x64

### Any other potentially useful information about your toolchain?
Nothing special. Docker toolchain but it is not related to this

### What did you do?
used the github.com/elastic/go-elasticsearch/v8 package. I am unable to reproduce my error myself on another repository. I tried to replicate the structure of the program and the length of the import path etc. but all compiled successfully.
The repository where the bug occurs is [this](github.com/JohnnyS318/RoyalAfgInGo) and it occurs on `bazel run //services/search:search`

I have long path enabled in regex and I did follow the steps given by this [using Bazel on Windows](https://docs.bazel.build/versions/master/windows.html#enable-symlink-support) Blog

### What did you expect to see?
A successful compilation of the package. All other packages compiled successfully to this point

### What did you see instead?
```
ERROR: C:/users/jonas/_bazel_jonas/b4n2c3vx/external/com_github_elastic_go_elasticsearch_v8/esapi/BUILD.bazel:3:11: GoCompilePkg external/com_github_elastic_go_elasticsearch_v8/esapi/go_default_library.a failed (Exit 1): builder.exe failed: error executing command bazel-out/host/bin/external/go_sdk/builder.exe -param=bazel-out/x64_windows-fastbuild/bin/external/com_github_elastic_go_elasticsearch_v8/esapi/go_default_library.a-0.params

compilepkg: error running subcommand: fork/exec external\go_sdk\pkg\tool\windows_amd64\compile.exe: The filename or extension is too long.
```

**Comment by jayconrod** [comment] 2020-12-23 14:50
Sorry, this repo is much too large for me to analyze. Please try and reduce it to a minimal example that reproduces the problem.

**Comment by JohnnyS318** [comment] 2021-01-02 10:45
Yes I know and I tried. When I test a repository with the same directory structure with go-elasticsearch it works. I tried the longest directory and a similar package structure, all work fine.

**Comment by jayconrod** [comment] 2021-01-06 15:16
I'll close this since I don't think I'll be able to reproduce this as is. Please comment if you're able to narrow it down to a smaller example.

(Bazel executes arbitrary code during builds, so I'm generally not willing to run an example unless I can verify the repo doesn't contain anything malicious.)

**Closed by jayconrod** 2021-01-06 15:16 UTC
