### ISSUE TITLE
gazelle -proto=default mysteriously removing go srcs and rules

### ISSUE THREAD

**Issue by ixdy** [bazelbuild/rules_go#907] opened 2017-10-12 20:47 UTC
In kubernetes/test-infra, I updated our rules_go and gazelle dependencies to 0cd983e2c6f6665fcae3e93eb303a00e54dc6fc5, and then updated all of our `BUILD` files, first with `-proto=legacy`, then without (separating this into two commits).

When I ran `gazelle -mode=fix` without `-proto=legacy`, it did weird things to `testgrid/config/BUILD` (see [commit](https://github.com/ixdy/kubernetes-test-infra/commit/97114745178397f93588e93d00634a377341ad71)), removing all of the go sources and `go_binary` rule, but leaving an invalid `go_test` rule.

I have no idea why it did this, and whether it's something weird we're doing or a bug in gazelle.

**Comment by jayconrod** [comment] 2017-10-13 18:25
This is confusing behavior, but it's actually working as intended.

When Gazelle finds source files in a directory that declare different packages, it normally prints an error and skips processing that directory. As a special case, if one of the packages matches the base name of the directory, that Gazelle will generate rules for that package and ignore source files belonging to other packages. This is common with libraries that also have helper tools in `package main`. Generally, people want the library and not the tool, so we avoid emitting an error and ignore the tool.

With the new support for proto rules, .proto files are treated as sources that are part of a package. If the proto has `option go_package` or `package` statements, the package name is derived from those. If not, the package name is derived from the filename. This is intended to match what protoc does.

This directory, test-infra/config, contains .go files in package `main`. It also has config.proto, which doesn't specify its package. So Gazelle determines that config.proto belongs to package `config`. Since that matches the directory name, it will ignore files belonging to the `main` package. It will generate `proto_library`, `go_proto_library`, and `go_library` rules for `config` and will delete empty rules (`go_binary`). It would delete the `go_test` as well, but that contains a manually written `data` attribute, so it  doesn't completely remove it.

---

I'm not sure how the proto is used in this directory. It wasn't mentioned in the BUILD file before, so if you don't need it, perhaps it's best to add `# gazelle:exclude config.proto` before running `gazelle fix`. `# gazelle:proto disable` would also do the trick. If you want to generate code from it, you could add something like `option go_package = "k8s.io/test-infra/testgrid/config;main";` to force it to be in the `main` package.

---

I'm not sure there's an immediate fix for this. This is the confusing result of several behaviors overlapping in an unsual way. Eventually, Gazelle will support multiple packages in each directory, and then we won't have to choose between them like this.

**Comment by jayconrod** [comment] 2017-12-27 20:01
Closing old Gazelle issues. Support for multiple packages is bazelbuild/bazel-gazelle#7. Please open a new issue at bazelbuild/bazel-gazelle if something isn't covered though.

**Closed by jayconrod** 2017-12-27 20:01 UTC
Labels: bug, gazelle
