### ISSUE TITLE
go_sdk

### ISSUE THREAD

**Issue by jeb2239** [bazelbuild/rules_go#1260] opened 2018-01-21 17:00 UTC
```
 /home/barriosj/.cache/bazel/_bazel_barriosj/aaa540067bcff65b4db4317218b0a805/external/bazel_gazelle/resolve/BUILD.bazel:44:1: no such package '@go_sdk//': The repository could not be resolved and referenced by '@bazel_gazelle//resolve:std_package_list'
ERROR: Analysis of target '//:gazelle' failed; build aborted: no such package '@go_sdk//': The repository could not be resolved
INFO: Elapsed time: 125.387s
```
what does this error mean and why would the go_sdk not be able to be resolved?

I have this in my workspace
```
git_repository(
    name = "io_bazel_rules_go",
    remote = "https://github.com/bazelbuild/rules_go.git",
    commit = "a390e7f7eac912f6e67dc54acf67aa974d05f9c3",
)
load("@io_bazel_rules_go//go:def.bzl", "go_rules_dependencies", "go_register_toolchains")
go_rules_dependencies()
go_register_toolchains()

http_archive(
    name = "bazel_gazelle",
    url = "https://github.com/bazelbuild/bazel-gazelle/releases/download/0.8/bazel-gazelle-0.8.tar.gz",
    sha256 = "e3dadf036c769d1f40603b86ae1f0f90d11837116022d9b06e4cd88cae786676",
)
load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies")
gazelle_dependencies()
```

**Comment by jayconrod** [comment] 2018-01-22 16:13
This is an issue with version skew between an old version of rules_go and a newer version of Gazelle. Gazelle depends on a list of standard library packages which is generated by rules_go. That's used to check whether an import should be resolved into a dependency or ignored. It looks like the version of rules_go you're using is old enough that it doesn't produce this list.

Are you able to update to a newer version of rules_go? 0.9.0 is the latest version. You'll need to rearrange your WORKSPACE file a bit:

```
http_archive(
    name = "io_bazel_rules_go",
    url = "https://github.com/bazelbuild/rules_go/releases/download/0.9.0/rules_go-0.9.0.tar.gz",
    sha256 = "4d8d6244320dd751590f9100cf39fd7a4b75cd901e1f3ffdfd6f048328883695",
)
http_archive(
    name = "bazel_gazelle",
    url = "https://github.com/bazelbuild/bazel-gazelle/releases/download/0.8/bazel-gazelle-0.8.tar.gz",
    sha256 = "e3dadf036c769d1f40603b86ae1f0f90d11837116022d9b06e4cd88cae786676",
)
load("@io_bazel_rules_go//go:def.bzl", "go_rules_dependencies", "go_register_toolchains")
go_rules_dependencies()
go_register_toolchains()
load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies")
gazelle_dependencies()
```

If you can't upgrade, you can load the old Gazelle script rule with  `load("@io_bazel_rules_go//go:def.bzl", "gazelle")`.

**Comment by akashgangil** [comment] 2018-02-28 22:45
I noticed this too. After upgrading to bazel 0.10.1 I see the error 

ERROR: /private/var/tmp/_bazel_gangil/13bbf3f8fafc3533089b82a6d2de4e72/akash-rules-go/external/io_bazel_rules_go/BUILD.bazel:19:1: every rule of type go_context_data implicitly depends upon the target '@go_sdk//:packages.txt', but this target could not be found because of: no such package '@go_sdk//': Traceback (most recent call last):
        File "/private/var/tmp/_bazel_gangil/13bbf3f8fafc3533089b82a6d2de4e72/akash-rules-go/external/io_bazel_rules_go/go/private/sdk.bzl", line 50
                _prepare(ctx)
        File "/private/var/tmp/_bazel_gangil/13bbf3f8fafc3533089b82a6d2de4e72/akash-rules-go/external/io_bazel_rules_go/go/private/sdk.bzl", line 104, in _prepare
                fail("failed to list standard package...")
failed to list standard packages
ERROR: Evaluation of query "deps(//...)" failed: errors were encountered while computing transitive closure

I don't use gazelle.

**Comment by jayconrod** [comment] 2018-03-01 15:52
@akashgangil I wasn't able to reproduce this.

Was there any other error output? We run `go list ...` in a newly downloaded SDK to build a list of standard library packages. From the error message you posted, it sounds like that command failed, but without the output, it's hard to tell why.

Does the error go away after `bazel clean --expunge`?

What version of Bazel are you using? What platform? Anything else unusual about your setup?

**Closed** 2018-08-14 20:08 UTC
Labels: question
