### ISSUE TITLE
go_proto_library fails when go_import_path is not set.

### ISSUE THREAD

**Issue by njt99** [bazelbuild/rules_go#1021] opened 2017-11-14 05:05 UTC
bazel version 0.7.0
rules_go version 0.7.0.
platform: ubuntu-trusty

**Summary**: go_proto_library fails to locate output .pb.go files when go_package_path isn't set.

**Detail**:
There are a number of `go get` repositories which contain .proto files which define package, but not go_package_path.
When imported with go_repository, they fail to build, because `protoc` puts the `.pb.go` output in a different place from where the rule expects to find it.
When I control the source, a work around is setting go_package_path.
The combination makes it difficult to contribute upstream.

This can be reproduced by attempting to build a rule that depends on github.com/njt99/rules_go_missing_pb_go/tiny. I've also tested it at HEAD.

**Comment by ianthehat** [comment] 2017-11-14 06:17
This is a duplicate of #910
I suggested on that bug that we might be able to use `--go_out=Mproto=importpath` to force it, but I have not had time to try it yet.

**Comment by njt99** [comment] 2017-11-14 07:36
Is there a workaround for rules in build files generated by `go_repository`?

It seems easy enough to try to force protoc, but that won't work unless I vendor or convince the upstream authors that they need to change their code to add go_package (which appears to be documented as optional in the instructions (https://github.com/golang/protobuf#parameters)).

**Comment by ashi009** [comment] 2017-11-24 03:46
@ianthehat  I'm holding off rules_go 0.7 upgrade due to this issue.  It appears that the `importpath` is not included in the `protoc` args. So as long as the `go_package` doesn't match the `importpath` (which looks like is generated from the path and the `go_prefix`), the `protoc` won't put the file into the directory bazel expects.

Is there a quick fix?

**Closed** 2017-12-06 14:55 UTC
Labels: duplicate, enhancement, proto
