### ISSUE TITLE
Target name directories in bazel-out contain the percent (%) symbols in their name

### ISSUE THREAD

**Issue by jernejstrasner** [bazelbuild/rules_go#2234] opened 2019-09-28 00:31 UTC
### What version of rules_go are you using?

0.19.4

### What version of gazelle are you using?

0.18.2

### What version of Bazel are you using?

0.29.1-homebrew

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

MacOS 10.14.6
x86_64

### Any other potentially useful information about your toolchain?

go1.13

### What did you do?

`bazel build //golang/package:target`

### What did you expect to see?

`bazel-out/darwin-fastbuild/bin/golang/package/darwin_amd64_stripped/target/golang/package.a`

### What did you see instead?

`bazel-out/darwin-fastbuild/bin/golang/package/darwin_amd64_stripped/target%/golang/package.a`
(see the % symbol above)

The problem is as follows:
- Bazel puts the percent `%` symbol at the end of the target name in the `bazel-out` directory structure
- `gopls` sees that symbol in the path when trying to process the file and panics (`invalid URL escape "%/g"`)
- `gopls` checks the path if it's a valid URI, which it isn't according to RFC

> According to URI syntax [RFC3986 <https://tools.ietf.org/html/rfc3986>], "%" is always treated as an escape character in a URI, so, according to the established URI syntax [RFC3986 <https://tools.ietf.org/html/rfc3986>] any occurrences of literal "%" symbols in a URI MUST be percent-encoded and represented in the form "%25”.

- this only happens with Go targets (eg. C++ output doesn't contain `%` in the path).

**Comment by jayconrod** [comment] 2019-09-30 14:41
Thanks for reporting this. At the moment, using gopls with Bazel is not supported.

I'll close this as a duplicate of #512, which is the main issue for integrating `golang.org/x/tools/go/packages` with rules_go, which would let gopls work in Bazel workspaces.

**Closed by jayconrod** 2019-09-30 14:41 UTC
