### ISSUE TITLE
Unable to compile nested packages

### ISSUE THREAD

**Issue by wno-git** [bazelbuild/rules_go#1794] opened 2018-10-27 20:11 UTC
Hello,

The Go rules are unable to compile a library consisting of nested packages. The
result is a compilation error because the compiler cannot resolve imports of
those nested packages within the library. Some code generators [1] produce this
kind of libraries and right now building the generated code with the current Go
rules is very difficult. For comparison `go build` can build this kind of
libraries without any problems.

Example:

```
$ tree .
.
├── BUILD
├── src
│   └── example.com
│       └── library
│           ├── library.go
│           ├── packageA
│           │   └── packageA.go
│           └── packageB
│               └── packageB.go
└── WORKSPACE
```

library.go
```
package library

import (
    "example.com/library/packageA"
    "example.com/library/packageB"
)

func Func() {
    packageA.Func();
    packageB.Func();
}
```

packageA.go
```
package packageA

import "fmt"

func Func() {
    fmt.Println("packageA")
}
```

packageB.go
```
package packageB

import "fmt"

func Func() {
    fmt.Println("packageB")
}
```

WORKSPACE
```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
    name = "io_bazel_rules_go",
    urls = ["https://github.com/bazelbuild/rules_go/releases/download/0.16.1/rules_go-0.16.1.tar.gz"],
    sha256 = "f5127a8f911468cd0b2d7a141f17253db81177523e4429796e14d429f5444f5f",
)
load("@io_bazel_rules_go//go:def.bzl", "go_rules_dependencies", "go_register_toolchains")
go_rules_dependencies()
go_register_toolchains()
```
BUILD
```
load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "library",
    srcs = [
        "src/example.com/library/library.go",
        "src/example.com/library/packageA/packageA.go",
        "src/example.com/library/packageB/packageB.go",
    ],
    importpath = "example.com/library",
)
```

Attempting to build this library results in the following:
```
$ bazel build //:library
INFO: Analysed target //:library (0 packages loaded).
INFO: Found 1 target...
ERROR: <snip>/BUILD:3:1: GoCompile linux_amd64_stripped/library%/example.com/library.a failed (Exit 1)
GoCompile: missing strict dependencies:
	<snip>/_bazel_xxx/4d446374ed07044b0f7632be5aeac2af/sandbox/processwrapper-sandbox/1/execroot/__main__/src/example.com/library/library.go: import of "example.com/library/packageA"
	<snip>/_bazel_xxx/4d446374ed07044b0f7632be5aeac2af/sandbox/processwrapper-sandbox/1/execroot/__main__/src/example.com/library/library.go: import of "example.com/library/packageB"
No dependencies were provided.
Check that imports in Go sources match importpath attributes in deps.
Target //:library failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.099s, Critical Path: 0.02s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

For comparison, building the library with `go build` succeeds:
```
$ echo $GOPATH
<snip current directory>
$ go build -o liblibrary.a example.com/library
$ file liblibrary.a
liblibrary.a: current ar archive
```

Note that in the above example all the Go source files reside in the source tree
and the sources of the `go_library` are listed explicitly for clarity. However,
source files generated by another rule would be supplied for the `go_library` by
a provider as a tree artifact [2].

As an alternative I've considered compiling each (sub)package as a separate
`go_library` target. However, this is cumbersome or impossible with code
generators if the structure of the code is complex, not known before execution
or if it depends on the input of the generator (as is the case with [1]).
Therefore to my understanding the simplest way to compile this kind of libraries
would be if the Go rules supported compilation of a tree of nested packages.
This would enable compiling generated libraries as a single `go_library` target.

Bazel version: `0.18.0`
OS: Debian Testing

 [1] https://github.com/go-swagger/go-swagger
 [2] Compiling a tree artifact with the Go rules is possible by appending `.go`
     to the directory name of the tree artifact which makes the Go rules accept
     it as input. Because of [3,4] the tree artifact is expanded recursively to
     a list of the source files before passed to the compiler, which seems to
     work fine.
 [3] https://github.com/bazelbuild/bazel/issues/5093
 [4] https://docs.google.com/document/d/11agWFiOUiz2htBLj6swPTob5z78TrCxm8DQE4uJLOwM

**Comment by jayconrod** [comment] 2018-10-29 16:35
Sorry, rules_go won't support this. `go_library` build exactly one package. Breaking that invariant would require a lot of work and would complicate a lot of things.

This is not something that `go build` supports either, by the way: in your example `go build -o liblibrary.a example.com/library`, `go build` compiles a separate .a file for each package, but it only writes the .a file for the package you requested to the `-o` path. .a files for all compiled packages are stored in the cache. The Go compiler cannot store compiled code for more than one package in an .a file.

Rules that produce tree artifacts of source files for multiple packages do present an issue. In general, Bazel needs to know all the inputs and outputs for an action ahead of time (during analysis) without reading source files. If a rule produces a directory and other rules need to consume different parts of that directory, that's very difficult. Maybe `go_swagger_library` should provide an explicit list of .go outputs (maybe listed through an `attr.output_list`) instead of a tree artifact?

**Comment by jayconrod** [comment] 2018-10-29 16:37
@rogerhub Gazelle works well for pre-generated files, but unfortunately, there's no way to run it on files that are generated during the build.

**Comment by wno-git** [comment] 2018-10-30 19:09
Hi,

> Have you considered using Gazelle to generate your BUILD rules? For some
inspiration, go_repository is an example of a workspace rule that generates some
code (downloads from VCS, in this case) and runs Gazelle to generate the BUILD
rules.

Yes, that is also an option. In fact, there is an existing attempt to provide
rules for this code generator using the `repository_rule` and Gazelle approach
[1]. For the most part they work but are missing a few things, most importantly
an implicit dependency on the Go toolchain, which is required by this generator
during its execution. I was not aware how a `repository_rule` could utilize the
Go toolchain and using a `repository_rule` overall did not seem the recommended
way to execute code generators. Therefore I dismissed this approach.  However,
the `go_repository` example you pointed out seems to have some clues how the Go
toolchain dependency could be achieved [2]. Using a `repository_rule` is
probably justified, since this generator does not integrate well with the Bazel
conventions. I will explore this option further, thanks.

> Sorry, rules_go won't support this. go_library build exactly one package.
Breaking that invariant would require a lot of work and would complicate a lot
of things.

Thanks for clearing this up. I will explore the solution pointed out by
@rogerhub.

> If a rule produces a directory and other rules need to consume different parts
of that directory, that's very difficult. Maybe go_swagger_library should
provide an explicit list of .go outputs (maybe listed through an
attr.output_list) instead of a tree artifact?

Bazel's recently improved support for tree artifacts gave me the impression they
would be a way forward for integrating this kind of generators that have
(partially)unknown outputs. Explicitly listed and known outputs would indeed
make the integration much easier but unfortunately does not seem to be supported
by this generator at this time. I can perhaps ping the developers about this.

Since this feature request is not feasible this issue can be closed. Thanks for
your valuable input and the rubber-duck debugging!

 [1] https://github.com/tnarg/rules_go_swagger
 [2] Perhaps there could be a `repository_rule` equivalent of the `go_rule`
 helper, to enable easily accessing the toolchain in `repository_rule`s if
 needed.

**Comment by jayconrod** [comment] 2018-10-30 20:42
Use caution when writing repository rules. They operate outside the normal build process. They're essentially a series of commands run on the host machine. They're not sandboxed, and they may not be reproducible because they can access files and programs on the host system. I think it's best to limit them to just checking out a repository and setting up build files. Try to use regular rules as much as possible. Of course, in some cases, particularly when dependency information cannot be known ahead of time, repository rules may be your only option.

In this particular case, I'd explore 1) having a rule that produces .go source files with swagger, 2) a rule that filters out individual directories, and 3) `go_library` rules that consume each directory. Maybe all that can be wrapped in a macro for convenience.

It doesn't look like 3) works today though, even with the new `--incompatible_expand_directories` flag. We do too much stuff with source files during analysis, before constructing `args`. I've filed #1798 to support this.

I'll close this issue now, but I'm happy to discuss further and answer questions.

**Closed by jayconrod** 2018-10-30 20:42 UTC
