### ISSUE TITLE
Cannot compile on NixOS

### ISSUE THREAD

**Issue by crawford** [bazelbuild/rules_go#1376] opened 2018-03-09 18:41 UTC
### Environment ###

```
$ bazel version
Build label: 0.10.1- (@non-git)
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Sat Nov 2 00:00:00 +11968 (315532800000)
Build timestamp: 315532800000
Build timestamp as int: 315532800000
```

```
$ nixos-version
17.09.3129.1dcd022f01b (Hummingbird)
```

### Failure ###

```
$ bazel build tarball
DEBUG: /home/alex/.cache/bazel/_bazel_alex/9a62ea23e6672e5bdeba02f2fd03b905/external/io_bazel_rules_go/go/private/sdk.bzl:103:5: env: ‘bin/go’: No such file or directory
ERROR: /home/alex/.cache/bazel/_bazel_alex/9a62ea23e6672e5bdeba02f2fd03b905/external/io_bazel_rules_go/BUILD.bazel:7:1: every rule of type go_context_data implicitly depends upon the target '
@go_sdk//:packages.txt', but this target could not be found because of: no such package '@go_sdk//': Traceback (most recent call last):                                                        
        File "/home/alex/.cache/bazel/_bazel_alex/9a62ea23e6672e5bdeba02f2fd03b905/external/io_bazel_rules_go/go/private/sdk.bzl", line 50
                _prepare(ctx)                                                                                                             
        File "/home/alex/.cache/bazel/_bazel_alex/9a62ea23e6672e5bdeba02f2fd03b905/external/io_bazel_rules_go/go/private/sdk.bzl", line 104, in _prepare
                fail("failed to list standard package...")                                                                                              
failed to list standard packages                          
ERROR: Analysis of target '//:tarball' failed; build aborted: no such package '@go_sdk//': Traceback (most recent call last):
        File "/home/alex/.cache/bazel/_bazel_alex/9a62ea23e6672e5bdeba02f2fd03b905/external/io_bazel_rules_go/go/private/sdk.bzl", line 50
                _prepare(ctx)                                                                                                             
        File "/home/alex/.cache/bazel/_bazel_alex/9a62ea23e6672e5bdeba02f2fd03b905/external/io_bazel_rules_go/go/private/sdk.bzl", line 104, in _prepare
                fail("failed to list standard package...")                                                                                              
failed to list standard packages                          
INFO: Elapsed time: 20.224s     
FAILED: Build did NOT complete successfully (110 packages loaded)
```

The reason this fails is because the rules are downloading a dynamically-linked copy of the Go toolchain:

```
$ file /home/alex/.cache/bazel/_bazel_alex/9a62ea23e6672e5bdeba02f2fd03b905/external/go_sdk/bin/go
/home/alex/.cache/bazel/_bazel_alex/9a62ea23e6672e5bdeba02f2fd03b905/external/go_sdk/bin/go: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, with debug_info, not stripped
```

My system (and no NixOS system) has `/lib64/ld-linux-x86-64.so.2`, so I get a "no such file or directory" error when I try to execute this binary.

**Comment by jayconrod** [comment] 2018-03-12 19:09
Interesting, I'm not familiar with NixOS. So it doesn't have a dynamic linker? I expect that breaks a lot of things.

If you have a working Go toolchain installed on your system, you can use it by calling `go_register_toolchains(go_version = "host")` in your WORKSPACE. Bazel will use the toolchain in `GOROOT` instead of downloading one from golang.org.

You may run into more problems after that if Bazel or anything in the toolchain dynamically links something though.

**Comment by benley** [comment] 2018-03-22 20:38
NixOS does have a dynamic linker, but system libraries are not in the same places you would find them on most traditional linux distros.  Nix is a bit like bazel in that it avoids using any implicit dependencies.  It explicitly sets the interpreter path and RPATH on shared libraries and binaries, and eschews LSB paths like /lib and /usr/lib.

For example:

```
$ ldd `which bash`
        linux-vdso.so.1 (0x00007ffe5f974000)
        libreadline.so.7 => /nix/store/a2vpf37zn5z4k6r6cvydl3m1i0757i73-readline-7.0p3/lib/libreadline.so.7 (0x00007f2cb5
fd5000)                                                                                                                 
        libhistory.so.7 => /nix/store/a2vpf37zn5z4k6r6cvydl3m1i0757i73-readline-7.0p3/lib/libhistory.so.7 (0x00007f2cb5dc
b000)                                                                                                                   
        libncursesw.so.6 => /nix/store/069g827lh3hrhp4vkcq3rsh5jh65pm3l-ncurses-6.0-20171125/lib/libncursesw.so.6 (0x0000
7f2cb5b5e000)                                                                                                           
        libdl.so.2 => /nix/store/2kcrj1ksd2a14bm5sky182fv2xwfhfap-glibc-2.26-131/lib/libdl.so.2 (0x00007f2cb595a000)
        libc.so.6 => /nix/store/2kcrj1ksd2a14bm5sky182fv2xwfhfap-glibc-2.26-131/lib/libc.so.6 (0x00007f2cb55a8000)
        /nix/store/2kcrj1ksd2a14bm5sky182fv2xwfhfap-glibc-2.26-131/lib/ld-linux-x86-64.so.2 => /nix/store/2kcrj1ksd2a14bm
5sky182fv2xwfhfap-glibc-2.26-131/lib64/ld-linux-x86-64.so.2 (0x00007f2cb6222000)
```

Ironically, the version of `go` provided by NixOS is _not_ dynamically linked...

**Comment by benley** [comment] 2018-03-22 20:40
And for what it's worth, bazel is able to build and link cc_library/cc_binary rules on NixOS as long as gcc is present, so Go ought to be OK to as long as the go toolchain doesn't assume LSB library paths.

**Comment by crawford** [comment] 2018-03-22 21:41
What is the proper fix here? I don't want to give up the pureness of my builds, but I also want them working on my machine. It seems like the issue is that Go distributes "Linux" builds when they mean "Debian-compatible".

**Comment by cstrahan** [comment] 2018-05-08 01:44
> Since NixOS doesn't store the loader in the location expected by most binaries, you won't be able to use dynamically linked binaries prepared for other distros. In particular, you won't be able to use the downloaded Go SDK.

Alternatively, an attr/option could be provided to specify the path to the dynamic linker; if a path is explicitly provided, the fetched binaries could be fixed up with [patchelf](https://nixos.org/patchelf.html).

Given that a number of build rules will want to fetch pre-compiled tool-chains and such, it might be best to give some thought to a unified solution to the general problem, which might be best solved in Bazel itself. I haven't used Bazel enough (yet) to write/think up a reasonable proposal, though.

**Comment by jayconrod** [comment] 2018-05-08 14:48
Our unified solution here is enabling the use of a custom toolchain. You can use `go_register_toolchains(version = "host")` to use the host toolchain, or you can explicitly download a custom toolchain with `go_local_sdk`. [toolchains.rst](https://github.com/bazelbuild/rules_go/blob/master/go/toolchains.rst) has more info. Please let me know if that should be improved or made clearer. It's also possible to define a toolchain through a custom rule; that probably won't be necessary here, but I'm happy to discuss further.

I don't think rules_go should implement any solution which is really specific to NixOS though. Patching fetched binaries is not a general solution, and I don't think the cost of developing, testing, and maintaining that justifies the benefit.

**Comment by alaric-dotmesh** [comment] 2018-07-23 17:29
A major goal of NixOS is to have reproducible builds, meaning that we can do the same build anywhere and get the same binaries; as such, we can't really condone downloading binaries that refer to host dependencies such as dynamic libraries and linkers (we allow use of the host kernel, and just hope that our compilers produce the same code on different kernels - grudgingly!).

So, (not being a bazel expert but having found this issue while trying to figure out why it doesn't work on his NixOS laptop), I suspect the best way to strong-arm bazel into becoming a reproducible build system will be to somehow disable any downloading of packages it does but instead to use the ones on the PATH, and use Nix (the NixOS build system) to make sure all the dependencies are in place before running it. Nix is all about creating a custom PATH for a build job that points to controlled versions of everything (the PATH actually points to a `/bin` which is a symlink farm assembled from the `/bin` directories of all the different input packages).

This can presumably be done on a per-package basis by patching the `WORKSPACE` file, if there's equivalents to `go_register_toolchains(go_version = "host")` for every thing in bazel that tries to download binaries that reference random resources on the host, but it will be a bit laborious finding and doing them all - is there a way we can have a global flag to put bazel into some kind of "reproducible build mode" that lets us pin down the input dependencies reliably? It needn't be NixOS-specific... A global "Use what's in my $PATH rather than downloading things" option would suffice.

**Comment by benley** [comment] 2018-07-25 02:44
> strong-arm bazel into becoming a reproducible build system

Bazel is also intended to be a reproducible build system; it verifies sha256 checksums of downloaded files (assuming the workspace rules actually specify them) just like Nix does, so in theory it ought to be acceptable to allow Bazel to download things.

That said, there are still plenty of reasons why Nix builds may not want to operate that way, and the way to do it may be to use `bazel build --override_repository="repository_name=/local/path/to/repository"` and have Nix pre-fetch them.

**Comment by jayconrod** [comment] 2018-07-26 16:56
Sorry for the slow response. Again, I don't know much about Nix, but I can comment on some of the Bazel aspects here.

In general, Bazel would prefer not to use anything at all outside of your workspace and declared external repositories. We'd like targets to be reproducible across systems, not just on Nix. This usually means downloading sources and tools at specific commits or with specific sha256 sums, so you should always get the same thing. Right now, this is part reality and part aspiration. 

rules_go downloads a specific version of the Go SDK from golang.org, but that doesn't work on NixOS because of the dynamic loader issue mentioned above. You can use `go_download_sdk` with custom URLs for NixOS, or you can use `go_host_sdk` to use the local `GOROOT`.

For C/C++ code (which Go uses via cgo and external linking), Bazel will try to autoconfigure a toolchain based on whatever the `CC` environment variable points to. If `CC` is not set, it will look for `gcc` and `clang` in `PATH`. You can explicitly configure a custom C/C++ toolchain with a `CROSSTOOL` file (see [Yet Another CROSSTOOL Writing Tutorial](https://github.com/bazelbuild/bazel/wiki/Yet-Another-CROSSTOOL-Writing-Tutorial). That's needed for toolchains downloaded from external repositories; Bazel folks are working on making this easier with `cc_toolchain` rules.

For the most part, everything else is explicitly downloaded with known git commits or sha256 sums. If you need to replace a repository, as mentioned above, you can use `--override_repository` to point to a local path. Bazel also has some support for proxies, though I'm not familiar enough with that to give advice on it.

**Comment by crawford** [comment] 2018-07-26 17:55
This comes back to my original assertion that this is Go's bug to fix. They claim to distribute "Linux" binaries but they are dynamically linked, limiting them to particular distributions. This isn't terribly surprising given Go's history of poor support for POSIX standards.

**Comment by jayconrod** [comment] 2018-07-26 18:20
Closing this issue as I don't think it's a constructive conversation anymore.

rules_go will use whichever version of Go you ask for. You can download something from golang.org, or you can use the version of Go installed on your system.

The SDK binaries don't work on NixOS, but you can still bootstrap from source or patch the interpreter.

If you feel that Go should distribute a statically linked SDK, feel free to file an issue at github.com/golang/go.

**Closed by jayconrod** 2018-07-26 18:20 UTC

**Comment by benley** [comment] 2018-07-26 18:22
Thanks, @jayconrod.  We can continue this discussion over at https://discourse.nixos.org

**Comment by rightfold** [comment] 2018-12-25 20:57
I got it working like this:
```nix
$ cat shell.nix                            
{ nixpkgs ? import <nixpkgs> {} }:
nixpkgs.stdenv.mkDerivation {
    name = "monorepo";
    buildInputs = [
        nixpkgs.bazel
        nixpkgs.go
    ];
    shellHook = ''
        export GOROOT="$(go env GOROOT)"
    '';
}
$ cat WORKSPACE | tail -n3
load("@io_bazel_rules_go//go:def.bzl", "go_register_toolchains", "go_rules_dependencies")
go_rules_dependencies()
go_register_toolchains(go_version = "host")
$ nix-shell --run 'bazel build //...'
```

**Comment by listx** [comment] 2019-04-19 05:52
Is there an easy way to call

```
go_register_toolchains(go_version = "host")
```

OR

```
go_register_toolchains()
```

depending on some environment variable? (E.g., presence of $NIX_PATH)

**Comment by listx** [comment] 2019-07-21 22:54
> Is there an easy way to call
> 
> ```
> go_register_toolchains(go_version = "host")
> ```
> 
> OR
> 
> ```
> go_register_toolchains()
> ```
> 
> depending on some environment variable? (E.g., presence of $NIX_PATH)

For posterity: Please see https://github.com/kubernetes-sigs/k8s-container-image-promoter/pull/79 for a patch that does exactly this.

**Comment by carnotweat** [comment] 2023-06-01 04:02
> nix-shell --run 'bazel build //...'

The following chain of repository dependencies lead to the missing definition.
 - @io_bazel_rules_go
This could either mean you have to add the '@io_bazel_rules_go' repository with a statement like `http_archive` in your WORKSPACE file (note that transitive dependencies are not added automatically), or move an existing definition earlier in your WORKSPACE file.
