### ISSUE TITLE
Use build_settings and transitions instead of aspect for cross-compilation

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/rules_go#2219] opened 2019-09-13 19:18 UTC
rules_go provides two ways to cross-compile code:

1. Users may set a target platform using `--platforms` on the command line. This selects a toolchain whose "default platform" is the target platform. We declare a separate `go_toolchain` and `toolchain` for each supported platform (even though the toolchains include the same files) to make this work. This mechanism generally works well.
2. Users may set `goos`, `goarch` and other attributes on `go_binary` and `go_test`. Both rules use an aspect that creates a second graph of actions if `goos`, `goarch` and other attributes are different than the default. This mechanism the the source of a lot of problems. In particular, `select` expressions (used for platform-specific dependencies) do not work because `select` is applied before analysis.

Recent versions of Bazel support [Starlark Build Configurations](https://docs.bazel.build/versions/master/skylark/config.html), which give users and Starlark rule authors much greater control over configuration transitions. We should use this functionality to remove the aspect. We may also be able to simplify toolchain declarations.

**Comment by siddharthab** [comment] 2019-10-06 03:27
#1600 can be marked as a duplicate of this issue.

**Comment by jmillikin-stripe** [comment] 2019-10-17 21:50
https://github.com/bazelbuild/rules_go/pull/2249 is related -- i want to use build settings to avoid the architecture-specific path component of `go_binary` outputs.

**Closed** 2020-04-17 21:48 UTC
Labels: cross-compilation, enhancement
