### ISSUE TITLE
Access debug.BuildInfo for Go Binaries

### ISSUE THREAD

**Issue by hjkatz** [bazelbuild/rules_go#3904] opened 2024-03-28 16:43 UTC
### What version of rules_go are you using?

0.46.0

### What version of gazelle are you using?

0.35.0

### What version of Bazel are you using?

7.1.0

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

linux, ubuntu, nix

### What did you do?

I used bazel to install our go binary, like so:

```
go_binary(
    name = "nd",
    embed = [":nd_lib"],
    visibility = ["//visibility:public"],
    // gc_linkopts = ["-buildvcs=true"], [Not committed yet]
)
```

I tried a few options but could not figure out how to do the following:

```
$ go build -buildvcs=true cmd/go/nd
```

### What did you expect to see?

I want to include vcs info at buildtime, see blog: https://shibumi.dev/posts/go-18-feature/

### What did you see instead?

No build info included

**Comment by malt3** [comment] 2024-04-03 12:31
I think this is a duplicate of https://github.com/bazelbuild/rules_go/issues/3090.
As mentioned in the issue, you can use stamping to achieve similar results today: https://github.com/bazelbuild/rules_go/blob/master/docs/go/core/defines_and_stamping.md#stamping-with-the-workspace-status-script

**Closed** 2024-04-03 13:00 UTC

**Comment by hjkatz** [comment] 2024-04-03 13:37
@malt3 Yes this is a duplicate. Thanks for pointing us in the right direction.
