### ISSUE TITLE
cgo tests fails with sandboxing

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/rules_go#12] opened 2016-04-18 11:35 UTC
See http://ci.bazel.io/job/rules_go/BAZEL_VERSION=HEAD,PLATFORM_NAME=ubuntu_15.10-x86_64/39/console

This is after merging #10 

/cc @yugui

**Comment by yugui** [comment] 2016-04-18 13:14
@damienmg 
I've started to investigate this issue.
* Is there any way to run these CI builds without merging PR?
* Do you have any idea about that it is failing only in ubuntu 15.10?
  I can't reproduce it in ubuntu 14.04 with Bazel 0.2.1.
* There is another failure in OSX. 
   http://ci.bazel.io/job/rules_go/BAZEL_VERSION=HEAD,PLATFORM_NAME=darwin-x86_64/39/console
   
   It looks to be [this bug](http://lists.apple.com/archives/Darwin-dev/2006/Sep/msg00084.html) in ld(1).
  Unfortunately I cannot reproduce the issue in El Capitan with XCode 7.3.

   BTW, what is the version of OSX and XCode in the CI environment?

**Comment by damienmg** [comment] 2016-04-18 13:24
* Not yet sorry, I am working on it but it requires to scale our CI a bit and it has been side tracked by other more urgent things right now.
* No idea I guess the gcc/ld version
* Oh yes sorry I mis read the result of breakage. it indeed has nothing to do with sandboxing:
  - Darwin is El Capitan: http://ci.bazel.io/computer/darwin-x86_64-2/systemInfo
  - I don't have the Xcode version, I could probably check but it's kind of hard. gcc -version returns:
```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/c++/4.2.1

Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.3.0
Thread model: posix
```

**Comment by yugui** [comment] 2016-04-18 14:09
Thank you.

For the failure on OSX, three possible workarounds come to my mind.  Which one do you prefer?
1. Upgrade XCode in the CI environment
2. Add `/usr/bin` to `$PATH`
3. Add a workaround in `osx_cc_wrapper.sh`



Let me explain more background behind the three workarounds.

1.  In my El Capitan environment, gcc is newer than the CI environment.  So we can expect the bug is fixed in the newer XCode.
  
   ```console
$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.29)
Target: x86_64-apple-darwin15.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
$ ld -v
@(#)PROGRAM:ld  PROJECT:ld64-264.3.101
configured to support archs: armv6 armv7 armv7s arm64 i386 x86_64 x86_64h armv6m armv7k armv7m armv7em (tvOS)
LTO support using: LLVM version 7.3.0
```
2. As discussed in the bug report for `ld(1)`, we need to stop passing `-s` flag to gcc as a workaround if we keep using the XCode vesion in the CI environment.
   
    Usually we could do it by removing `-s` flag from `go tool link` ([cmd/link/internal/ld/lib.go#L1071](https://github.com/golang/go/blob/3c8d6af8e02bbf230c2bef9f181d8ea393068299/src/cmd/link/internal/ld/lib.go#L1071)).
   
   On the other hand, `go tool link` without `-s` expects that `dsymutil` is available on `$PATH` ([cmd/link/internal/ld/lib.go#L1243](https://github.com/golang/go/blob/3c8d6af8e02bbf230c2bef9f181d8ea393068299/src/cmd/link/internal/ld/lib.go#L1243)).  So `/usr/bin` must be listed in `$PATH`.
3. Another possible solution is to filter out the `-s` flag in `osx_cc_wrapper.sh` depending on the version of `ld`.

**Comment by damienmg** [comment] 2016-04-18 14:28
osx_cc_wrapper.sh should not change the argument. Add `/usr/bin` to `$PATH` for this precise action seems ok to me (updating xcode would not fix the underlying bug)

**Comment by yugui** [comment] 2016-04-19 03:01
@damienmg
Could you take a look at #13?

I reproduced the issue on Ubuntu 15.04 (GNU `ld` 2.25) and on Mac OS X (XCode 7.1 and 7.2). Then I confirmed that #13 fixed the issue.

**Closed** 2016-04-19 08:09 UTC
Labels: bug

**Comment by damienmg** [comment] 2016-04-19 08:18
fyi the build is blue again \o/ Thanks!

**Comment by yugui** [comment] 2016-04-19 12:04
Thank you for your help!
