### ISSUE TITLE
Generated vendor path is wrong, not in repository root

### ISSUE THREAD

**Issue by fho** [bazelbuild/rules_go#1061] opened 2017-11-24 15:29 UTC
When I run `bazel run //:gazelle` the generated import paths for vendor dirs starts with `//vendor/`.
But our vendor directory is in `//go/vendor`, all generated paths to vendored libs are wrong.

Is it possible to set to path to vendor directory?

Our repository structure is like:
```
|- BUILD.bazel
|- WORKSPACE
|- go/
    |- vendor/
        |- google.golang.org/
    |- code/
            |- lib/
            |- myapp/
                |- cmd/
                    |- myapp/
                        |- cmd.go
                        |- BUILD
```

**Comment by jayconrod** [comment] 2017-11-27 16:31
This isn't possible at the moment; Gazelle only supports a vendor directory at the repository root.

#859 will fix this. I'm expected to close that by the end of the week.

I'm going to close this as a duplicate of #486.

**Closed by jayconrod** 2017-11-27 16:31 UTC
Labels: duplicate
