### ISSUE TITLE
missing strict dependencies

### ISSUE THREAD

**Issue by junghoahnsc** [bazelbuild/rules_go#1347] opened 2018-02-22 23:44 UTC
Hello,

After I upgraded to 0.10.0 from 0.9.0, I got the following error while compiling a third-party lib.

```
ERROR: /home/.cache/bazel/_bazel_jhahn/096b9924a546d44702313d7a4b963776/external/com_github_grpc_ecosystem_grpc_gateway/runtime/BUILD.bazel:3:1: GoCompile external/com_github_grpc_ecosystem_grpc_gateway/runtime/linux_amd64_stripped/go_default_library~/github.com/grpc-ecosystem/grpc-gateway/runtime.a failed (Exit 1)
2018/02/22 15:40:15 missing strict dependencies:
	external/com_github_grpc_ecosystem_grpc_gateway/runtime/handler.go: import of github.com/grpc-ecosystem/grpc-gateway/runtime/internal, which is not a direct dependency
```

I checked the generated BUILD file and it includes that lib like
```
go_library(
    name = "go_default_library",
    srcs = [
        "context.go",
        "convert.go",
        "doc.go",
        "errors.go",
        "handler.go",
        "marshal_json.go",
        "marshal_jsonpb.go",
        "marshal_proto.go",
        "marshaler.go",
        "marshaler_registry.go",
        "mux.go",
        "pattern.go",
        "proto2_convert.go",
        "proto_errors.go",
        "query.go",
    ],
    importpath = "github.com/grpc-ecosystem/grpc-gateway/runtime",
    visibility = ["//visibility:public"],
    deps = [
        "//runtime/internal:go_default_library",
        "//utilities:go_default_library",
        "@com_github_golang_protobuf//jsonpb:go_default_library",
        "@com_github_golang_protobuf//proto:go_default_library",
        "@com_github_golang_protobuf//ptypes/duration:go_default_library",
        "@com_github_golang_protobuf//ptypes/timestamp:go_default_library",
        "@org_golang_google_grpc//codes:go_default_library",
        "@org_golang_google_grpc//grpclog:go_default_library",
        "@org_golang_google_grpc//metadata:go_default_library",
        "@org_golang_google_grpc//status:go_default_library",
        "@org_golang_x_net//context:go_default_library",
    ],
)
```

This repo is defined like 
```
  go_repository(
        name="com_github_grpc_ecosystem_grpc_gateway",
        importpath="github.com/grpc-ecosystem/grpc-gateway",
        tag='v1.3.1', )
```
Is this an known issue? I couldn't find any change in 0.10.0 regarding this.

Thanks,

**Comment by junghoahnsc** [comment] 2018-02-23 03:36
importpath seems  to be generated incorrectly.

`external/com_github_grpc_ecosystem_grpc_gateway/runtime/internal/BUILD.bazel` is

```
go_library(
    name = "go_default_library",
    embed = [":internal_go_proto"],
    importpath = "internal",
    visibility = ["//visibility:public"],
)
```

Is there a way to fix this?

**Comment by jayconrod** [comment] 2018-02-23 20:02
This is a duplicate of bazelbuild/bazel-gazelle#123. You should be able to avoid this by using a very recent commit of Gazelle. There's no version tagged yet that includes the fix, bug I'll tag one soon and point rules_go to it.

**Closed by jayconrod** 2018-02-23 20:02 UTC
