### ISSUE TITLE
Remove support for custom Go toolchains

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/rules_go#474] opened 2017-05-25 18:57 UTC
In the latest release, you could use a custom Go toolchain with the Go rules, perhaps a `local_repository`, perhaps with custom patches. We are considering removing support for this.

This functionality is covered by tests/custom_go_toolchain.bash, which is currently broken at HEAD. It does not look like we can fix this and support cross-compilation with predeclared toolchains at the same time. We won't be able to determine GOOS, GOARCH, and supported target platforms for a custom toolchain. Consequently, we're considering removing support for custom toolchains.

This will not affect support for different *versions* of Go. You'll still be able to say (for example) `go_repositories(go_version = "1.8.3")`. You just won't be able to use your own Go toolchain. Please comment if this will cause any problems for you, and we'll figure out a solution.

cc @ixdy @wlynch @pmbethe09 @ianthehat

**Comment by ixdy** [comment] 2017-05-25 19:48
There's been discussion about a desire to build against Go tip (https://github.com/kubernetes/test-infra/issues/1399), or at least have some build that does this, though nothing beyond discussion yet. I'm still not sure how this would work exactly.

**Comment by jayconrod** [comment] 2017-05-26 14:53
@ianthehat This seems like a good use case for custom builds. How would that work with toolchains? I guess a new set of `go_toolchain` rules would need to be declared?

**Comment by mmikulicic** [comment] 2017-05-26 15:15
I also need a custom sdk (only for one arch, e.g. for darwin) because of a bug I'm in the process of reporting upstream but it's blocking me.

Ideally I'd like to be able to create a `go_sdk_repository` rule and pass it's rule name down to the `go_repositories` keyed by e.g. `go1.8.3.darwin-amd64.tar.gz`, so that it would use that rule instead of the one generated by the skylark script inside `go/private/repositories.bzl`.

Would that be acceptable?

I have no idea yet how to make this override, just asking first about the general idea.

**Comment by ianthehat** [comment] 2017-06-01 17:52
bazel supports --override_repository (as of 0.5) as a way to replace an repository rule with a local version.
This is the way I would expect people to generally have a temporary override of a go sdk, and could work for both use cases I think, as the toolchain declaration itself could be left alone and just the sdk swapped out underneath it (for a specific go version and platform)
Building from source against a specific commit is something I think it would not be that hard to add, it's just a custom go_sdk_repository variant that knows how to invoke make.bash during the download phase.
Then you just need to call go_toolchain with the right parameters for each platform and cross compilation you want to support. We could put parts of the table generation functionality used in toolchains.bzl in functions so they could be used to make that step easier as well if needed.
Building against tip from within normal repository rules is a much more dubious prospect, as it's a non reproducible build (the same build a minute later will be a different tip) and I would hesitate to encourage that through a standard mechanism, it would probably be better to fall back to override_repository for that case.

**Comment by minorhacks** [comment] 2017-07-18 18:08
Our org has a requirement that all external dependencies be hosted in-house (on an internal webserver, NFS share, Git repo, etc.) such that a clean build is not dependent on internet connectivity. Would removal of this feature impact this requirement?

(Side note: I'm having issues satisfying this requirement with the current implementation of `go_repositories` - is this a use case you guys want to support? Should I open a separate issue?)

**Comment by jayconrod** [comment] 2017-07-19 17:21
I originally filed this issue because the `go_linux` and `go_darwin` parameters to `go_repositories` have been broken for some time.

We definitely need to support custom Go SDKs again, but it's not clear to me that this is the right interface, especially since additional platforms and toolchains may need to be defined. Maybe we can automate this in Skylark or provide a template.

**Comment by ianthehat** [comment] 2017-08-15 23:41
The new interface is now in #683.
building with `--experimental_platforms=@io_bazel_rules_go//go/toolchain:host`
will now cause it to detect and use the hosts go sdk.
It checks for `GOROOT` first, if not set it tries to find `go` and use that to
work out the `GOROOT`
Leaving this open as we still need to fix up the test

**Comment by ianthehat** [comment] 2017-10-05 13:18
This was fixed in #829 and the systems fully documented in #864

**Closed by ianthehat** 2017-10-05 13:18 UTC
