### ISSUE TITLE
Wrong importpath for //go/tools/bazel

### ISSUE THREAD

**Issue by cgrushko** [bazelbuild/rules_go#1333] opened 2018-02-16 14:39 UTC
In https://github.com/bazelbuild/rules_go/blob/master/go/tools/bazel/BUILD.bazel, 

```
go_library(
    name = "go_default_library",
    srcs = ["bazel.go"],
    importpath = "github.com/bazelbuild/rules_go/go/tools/bazel",
    visibility = ["//visibility:public"],
)
```

The problem is that if I import this package in my code as `github.com/bazelbuild/...`, Gazelle creates a dependency to `@com_github_bazelbuild_rules_go//go/tools/bazel` which doesn't exist because the repository's name is `io_bazel_rules_go` (and changing it is hard, because everyone uses this name, including Gazelle and Buildozer).

However, if I import it as `bazel.io/rules_go/go/tools/bazel`, Gazelle doesn't generate any dependency at all (separate bug?) and Bazel complains about a "missing strict dependencies". Adding a manual dependency on `@io_bazel_rules_go//go/tools/bazel` still fails the build with the same strict deps violation, presumably because of the `importpath` here.

It seems logical to change the `importpath`, though I don't know who it affects. 
Also, is there a workaround I can use in the meanwhile, other than vendor https://github.com/bazelbuild/rules_go/blob/master/go/tools/bazel/bazel.go?

**Comment by jayconrod** [comment] 2018-02-16 15:51
bazelbuild/bazel-gazelle#132 will provide a way to deal with this. Gazelle already scans WORKSPACE for `go_repository` rules in order to build a mapping between repository names and import paths. There's not yet a way to tell it about repositories declared with other rules or declared inside macros.

We can't change the `importpath` of this library, since that would break anyone depending on it with the current path.

For now, I'd recommend marking the `deps` list that contains that import with a `# keep` comment. That will prevent Gazelle from modifying that attribute.

**Comment by cgrushko** [comment] 2018-02-16 16:41
Who's depending on that target? Wouldn't they all run into the same issues
as I?

**Comment by jayconrod** [comment] 2018-02-16 17:21
I'm not sure who's depending on it, but I'd rather not break them. I think the problem is that Gazelle is putting the wrong label in deps, so it should be fixed in Gazelle instead.

**Comment by cgrushko** [comment] 2018-02-16 18:28
Adding a dependency doesn't seem to work:

Go file:

```
...
import "bazel.io/rules_go/go/tools/bazel"
...
```

BUILD.bazel file:

```
go_library(
    name = "go_default_library",
    srcs = ["compat.go"],
    importpath = "github.com/bazelbuild/tools_java_autodeps/compat",
    visibility = ["//visibility:public"],
    deps = ["@io_bazel_rules_go//go/tools/bazel:go_default_library"],
)
```

Error: 

```
2018/02/16 13:26:36 missing strict dependencies:
        compat/compat.go: import of bazel.io/rules_go/go/tools/bazel, which is not a direct dependency
```

**Comment by cgrushko** [comment] 2018-02-16 18:31
Ah! Got it. I should change the import to `github.com/bazelbuild/rules_go/go/tools/bazel`, as specified in https://github.com/bazelbuild/rules_go/blob/master/go/tools/bazel/BUILD.bazel

**Closed** 2018-03-08 20:49 UTC
