### ISSUE TITLE
pure mode and protobuf

### ISSUE THREAD

**Issue by shariat** [bazelbuild/rules_go#1115] opened 2017-12-07 18:52 UTC
it seems that in `rules_go:0.8.0` with `bazel:0.8.1` or `bazel:0.8.0`, `--features=pure` as no effect anymore, the binary still has `glibc` dependency. Adding `pure="on"` to BUILD file works, but then protobuf won't compile anymore.

```
ERROR: .../BUILD.bazel:12:1: in @io_bazel_rules_go//go/private:rules/aspect.bzl%go_archive_aspect[pure="on",static="auto",msan="auto",race="auto"] aspect on go_proto_library rule //...:protofile_go_proto:
Traceback (most recent call last):
        File ".../BUILD.bazel", line 12
                @io_bazel_rules_go//go/private:rules/aspect.bzl%go_archive_aspect(...)
        File ".../external/io_bazel_rules_go/go/private/rules/aspect.bzl", line 76, in _go_archive_aspect_impl
                collect_src(ctx, aspect = True)
        File ".../external/io_bazel_rules_go/go/private/rules/aspect.bzl", line 48, in collect_src
                rule.files.srcs
No attribute 'srcs' in files. Make sure there is a label or label_list type attribute with this name
Available attributes: _action_listener, _go_prefix, _go_toolchain_flags, _toolchains, compatible_with, compiler, deps, embed, proto, restricted_to
```

**Comment by ianthehat** [comment] 2017-12-08 01:20
--features=pure was not working, and has not done for a while, fixed in #117
aspect builds not working for things with proto is a dupe of #994 and was is caused by the proto toolchain carrying deps that did not switch mode in the aspect (because they were picked out of a provider rather than re-collected)
Now we have switched the proto stuff to have a per rule compiler I can fix this, it may take a couple of days though (it's still not easy)

**Closed** 2017-12-08 15:54 UTC
