### ISSUE TITLE
Invalid go_default_library for isatty

### ISSUE THREAD

**Issue by abergmeier** [bazelbuild/rules_go#1157] opened 2017-12-19 07:54 UTC
I have the following `WORKSPACE` in Bazel 0.8.1:

```
http_archive(
    name = "io_bazel_rules_go",
    url = "https://github.com/bazelbuild/rules_go/releases/download/0.8.1/rules_go-0.8.1.tar.gz",
    sha256 = "90bb270d0a92ed5c83558b2797346917c46547f6f7103e648941ecdb6b9d0e72",
)
load("@io_bazel_rules_go//go:def.bzl", "go_repository", "go_rules_dependencies", "go_register_toolchains")
go_rules_dependencies()
go_register_toolchains()

go_repository(
    name = "com_github_mattn_go_isatty",
    importpath = "github.com/mattn/go-isatty",
    tag = "v0.0.3",
)
```

When trying to build `com_github_mattn_go_isatty` on Linux x86_64, I get an error:

`ERROR: /home/user/.cache/bazel/_bazel_user/39b2d6f0d213152194c5e70c47d440c6/external/com_github_mattn_go_isatty/BUILD.bazel:3:1: Label '@org_golang_x_sys//unix:go_default_library' is duplicated in the 'deps' attribute of rule 'go_default_library'`

What _gazelle_ produced was:

```
go_library(
    name = "go_default_library",
    srcs = [
        "doc.go",
    ] + select({
        "@io_bazel_rules_go//go/platform:android": [
            "isatty_others.go",
        ],
        "@io_bazel_rules_go//go/platform:darwin": [
            "isatty_bsd.go",
            "isatty_others.go",
        ],
        "@io_bazel_rules_go//go/platform:dragonfly": [
            "isatty_bsd.go",
            "isatty_others.go",
        ],
        "@io_bazel_rules_go//go/platform:freebsd": [
            "isatty_bsd.go",
            "isatty_others.go",
        ],
        "@io_bazel_rules_go//go/platform:linux": [
            "isatty_others.go",
        ],
        "@io_bazel_rules_go//go/platform:nacl": [
            "isatty_others.go",
        ],
        "@io_bazel_rules_go//go/platform:netbsd": [
            "isatty_bsd.go",
            "isatty_others.go",
        ],
        "@io_bazel_rules_go//go/platform:openbsd": [
            "isatty_bsd.go",
            "isatty_others.go",
        ],
        "@io_bazel_rules_go//go/platform:plan9": [
            "isatty_others.go",
        ],
        "@io_bazel_rules_go//go/platform:solaris": [
            "isatty_others.go",
            "isatty_solaris.go",
        ],
        "@io_bazel_rules_go//go/platform:windows": [
            "isatty_windows.go",
        ],
        "//conditions:default": [],
    }) + select({
        "@io_bazel_rules_go//go/platform:linux_386": [
            "isatty_linux.go",
        ],
        "@io_bazel_rules_go//go/platform:linux_amd64": [
            "isatty_linux.go",
        ],
        "@io_bazel_rules_go//go/platform:linux_arm": [
            "isatty_linux.go",
        ],
        "@io_bazel_rules_go//go/platform:linux_arm64": [
            "isatty_linux.go",
        ],
        "@io_bazel_rules_go//go/platform:linux_mips": [
            "isatty_linux.go",
        ],
        "@io_bazel_rules_go//go/platform:linux_mips64": [
            "isatty_linux.go",
        ],
        "@io_bazel_rules_go//go/platform:linux_mips64le": [
            "isatty_linux.go",
        ],
        "@io_bazel_rules_go//go/platform:linux_mipsle": [
            "isatty_linux.go",
        ],
        "@io_bazel_rules_go//go/platform:linux_ppc64": [
            "isatty_linux_ppc64x.go",
        ],
        "@io_bazel_rules_go//go/platform:linux_ppc64le": [
            "isatty_linux_ppc64x.go",
        ],
        "@io_bazel_rules_go//go/platform:linux_s390x": [
            "isatty_linux.go",
        ],
        "//conditions:default": [],
    }),
    importpath = "github.com/mattn/go-isatty",
    visibility = ["//visibility:public"],
    deps = select({
        "@io_bazel_rules_go//go/platform:solaris": [
            "@org_golang_x_sys//unix:go_default_library",
        ],
        "//conditions:default": [],
    }) + select({
        "@io_bazel_rules_go//go/platform:linux_ppc64": [
            "@org_golang_x_sys//unix:go_default_library",
        ],
        "@io_bazel_rules_go//go/platform:linux_ppc64le": [
            "@org_golang_x_sys//unix:go_default_library",
        ],
        "//conditions:default": [],
    }),
)
```

which seems correct enough. Unless the selectors for `@io_bazel_rules_go//go/platform:solaris` or `@io_bazel_rules_go//go/platform:linux_ppc64`* are buggy.

For whatever reason, `tag` == `v0.0.2` works.

**Comment by jayconrod** [comment] 2017-12-19 16:02
I believe this is a duplicate of bazelbuild/bazel-gazelle#28, which was fixed yesterday.

If you're using the `gazelle` rule from `@io_bazel_rules_go//go:def.bzl`, I haven't upgraded rules\_go to the newest version of Gazelle, but I will shortly. You can also use the gazelle rule from `@bazel_gazelle//:def.bzl`.

If you're using a locally installed version of Gazelle, you can install the new one with `go get -u github.com/bazelbuild/bazel-gazelle/cmd/gazelle`.

**Closed by jayconrod** 2017-12-19 16:02 UTC
