### ISSUE TITLE
bazel build with remote caching takes much longer time for downloading than using 'go build'

### ISSUE THREAD

**Issue by niukuo** [bazelbuild/rules_go#2834] opened 2021-02-27 03:49 UTC
### What version of rules_go are you using?
v0.24.13

### What version of gazelle are you using?
v0.22.3

### What version of Bazel are you using?
bazel 3.7.1

### Does this issue reproduce with the latest releases of all the above?
yes

### What operating system and processor architecture are you using?
centos 7

### What did you do?

I'm using bazel-remote as remove caching service in .bazelrc
```
build --remote_cache=grpc://127.0.0.1:9092
build --experimental_remote_downloader=grpc://127.0.0.1:9092
```

when I was using 'GOPROXY=http://goproxy.cn bazel build cfssl', it takes long time to fetch remote repositories

`Fetching @com_github_google_certificate_transparency_go; fetching 183s`

when I was using 'go install', it's much faster.
```
time docker run --rm --network host -v /usr/local/go:/usr/local/go --env GOPROXY=http://goproxy.cn --env CGO_ENABLED=0 centos:7 /usr/local/go/bin/go install github.com/cloudflare/cfssl/cmd/cfssl@v1.5.0
go: downloading github.com/cloudflare/cfssl v1.5.0
go: downloading github.com/go-sql-driver/mysql v1.4.0
go: downloading github.com/lib/pq v1.3.0
go: downloading github.com/mattn/go-sqlite3 v1.10.0
go: downloading github.com/jmoiron/sqlx v1.2.0
go: downloading github.com/GeertJohan/go.rice v1.0.0
go: downloading github.com/jmhodges/clock v0.0.0-20160418191101-880ee4c33548
go: downloading golang.org/x/crypto v0.0.0-20201012173705-84dcc777aaee
go: downloading github.com/google/certificate-transparency-go v1.0.21
go: downloading github.com/zmap/zlint/v2 v2.2.1
go: downloading github.com/kisielk/sqlstruct v0.0.0-20150923205031-648daed35d49
go: downloading github.com/zmap/zcrypto v0.0.0-20200911161511-43ff0ea04f21
go: downloading golang.org/x/net v0.0.0-20201010224723-4f7140c49acb
go: downloading github.com/daaku/go.zipexe v1.0.0
go: downloading github.com/weppos/publicsuffix-go v0.13.0
go: downloading github.com/golang/protobuf v1.3.1
go: downloading golang.org/x/text v0.3.3

real    0m15.923s
user    0m0.020s
sys     0m0.030s
```

I created a repo to reproduce this at https://github.com/niukuo/go_slow

here's my BUILD.bazel

```
load("@bazel_gazelle//:def.bzl", "gazelle")
load("@io_bazel_rules_go//go:def.bzl", "go_binary")

# gazelle:prefix github.com/niukuo/go_slow
gazelle(name = "gazelle")

# keep
go_binary(
    name = "cfssl",
    embed = ["@com_github_cloudflare_cfssl//cmd/cfssl"],
    pure = "on",
    visibility = ["//visibility:public"],
)
```

What can I do to make it faster using 'bazel build'?

**Comment by jayconrod** [comment] 2021-03-01 14:35
This looks like a duplicate of #2188.

**Closed by jayconrod** 2021-03-01 14:35 UTC
