### ISSUE TITLE
Cross-compile for darwin failure

### ISSUE THREAD

**Issue by junghoahnsc** [bazelbuild/rules_go#1174] opened 2017-12-21 22:47 UTC
Hello,

I'm trying to cross-compile for darwin, but it failed.

The rule is like

```
go_binary(
    name = "test_darwin",
    basename = "test",
    embed = [":test_main"],
    goarch = "amd64",
    goos = "darwin",
    pure = "on",
)
```

And the error was
```
ERROR: /home/jhahn/.cache/bazel/_bazel_jhahn/096b9924a546d44702313d7a4b963776/external/com_github_spf13_afero/BUILD.bazel:3:1: GoCompile external/com_github_spf13_afero/darwin_amd64_pure_stripped/go_default_library~/github.com/spf13/afero.a failed (Exit 1)
external/com_github_spf13_afero/unionFile.go:40:9: undefined: BADFD
external/com_github_spf13_afero/unionFile.go:60:12: undefined: BADFD
external/com_github_spf13_afero/unionFile.go:74:12: undefined: BADFD
external/com_github_spf13_afero/unionFile.go:88:12: undefined: BADFD
external/com_github_spf13_afero/unionFile.go:102:12: undefined: BADFD
external/com_github_spf13_afero/unionFile.go:116:12: undefined: BADFD
external/com_github_spf13_afero/unionFile.go:183:14: undefined: BADFD
external/com_github_spf13_afero/unionFile.go:197:9: undefined: BADFD
external/com_github_spf13_afero/unionFile.go:211:9: undefined: BADFD
external/com_github_spf13_afero/unionFile.go:225:12: undefined: BADFD
external/com_github_spf13_afero/unionFile.go:225:12: too many errors
2017/12/21 14:35:55 error running compiler: exit status 1
```

But I can see `BADFD` in https://github.com/spf13/afero/blob/master/const_bsds.go, but this file doesn't seem to be included. Is this an known issue?

Thanks,

**Comment by ianthehat** [comment] 2017-12-21 23:02
Hi
This is a duplicate of #1148, select statements cause issues 
You can still cross compile by using --toolchains on the command line, but not by setting goos/goarch on the binary rule

**Closed by ianthehat** 2017-12-21 23:02 UTC

**Comment by tanin47** [comment] 2018-01-04 18:32
Hello @ianthehat, I'm new to Bazel and golang. 

I wonder if you could provide a sample command line for cross-compiling with --toolchains.

I tried with the partial example in #1148, and it gave me an unrelated error:

```
bazel build --experimental_platforms=@io_bazel_rules_go//go/toolchain:windows_amd64  //src:win64
ERROR: /home/tanin/.cache/bazel/_bazel_tanin/5bd8718d505a78ddae5517e72018e575/external/io_bazel_rules_go/go/toolchain/BUILD.bazel:11:1: in platform rule @io_bazel_rules_go//go/toolchain:windows_amd64: cycle in dependency graph:
    //src:win64
.-> @io_bazel_rules_go//go/toolchain:windows_amd64
|   @io_bazel_rules_go//go/toolchain:amd64
`-- @io_bazel_rules_go//go/toolchain:windows_amd64
This cycle occurred because of a configuration option
ERROR: Analysis of target '//src:win64' failed; build aborted
INFO: Elapsed time: 0.241s
FAILED: Build did NOT complete successfully (1 packages loaded)
```

**Comment by ianthehat** [comment] 2018-01-04 19:57
That looks like you are trying to use Bazel 0.9? that version is broken, you need 0.8.1

**Comment by tanin47** [comment] 2018-01-04 23:59
Thank you @ianthehat. Switching to Bazel 0.8.1 solves my problem. 

I'd like to share some snippets here:

The command: `bazel build --experimental_platforms=@io_bazel_rule
s_go//go/toolchain:windows_amd64  //src:win64`

The BUILD file: 

```
go_binary( 
  name = "win64",
  srcs = glob(["**/*.go"]),
  goos = "windows",
  goarch = "amd64",
  pure = "on",
  gc_linkopts = [
    "-extldflags",
    "-static",
  ],
)
```

**Comment by ianthehat** [comment] 2018-01-05 00:59
You know you can set `static = "on"` on go_binary?
You should not need the gc_linkopts.
