### ISSUE TITLE
experimental_platforms mac os to linux does not work

### ISSUE THREAD

**Issue by margic** [bazelbuild/rules_go#1009] opened 2017-11-09 20:36 UTC
Cross compiling with release 0.7.0 --experimental_platforms does not work on mac to produce linux binaries.

I have create a sample repo that fails with the command `bazel build --experimental_platforms=@io_bazel_rules_go//go/toolchain:linux_amd64 //:logrusbazel`

https://github.com/margic/logrusbazel

**Comment by margic** [comment] 2017-11-09 20:37
Command output 
```
 bazel build --experimental_platforms=@io_bazel_rules_go//go/toolchain:linux_amd64 //:logrusbazel
INFO: Found 1 target...
ERROR: /Users/paul.crofts/Documents/go/src/github.com/margic/logrusbazel/vendor/golang.org/x/sys/unix/BUILD.bazel:3:1: GoCompile vendor/golang.org
/x/sys/unix/~pure_stripped~go_default_library~/~partial.a failed (Exit 1).
bazel-out/darwin_x86_64-fastbuild/bin/vendor/golang.org/x/sys/unix/go_default_library.cgo.dir/vendor_golang.org_x_sys_unix_flock.cgo1.go:16:42: undefined: Flock_t
bazel-out/darwin_x86_64-fastbuild/bin/vendor/golang.org/x/sys/unix/go_default_library.cgo.dir/vendor_golang.org_x_sys_unix_sockcmsg_unix.cgo1.go:37:18: undefined: Cmsghdr
bazel-out/darwin_x86_64-fastbuild/bin/vendor/golang.org/x/sys/unix/go_default_library.cgo.dir/vendor_golang.org_x_sys_unix_sockcmsg_unix.cgo1.go:43:9: undefined: Cmsghdr
2017/11/09 13:36:46 error running compiler: exit status 1
Target //:logrusbazel failed to build
Use --verbose_failures to see the command lines o
```

**Comment by margic** [comment] 2017-11-09 20:39
Full command output with errors
```
bazel build --verbose_failures --experimental_platforms=@io_bazel_rules_go//go/toolchain:linux_amd64 //:logrusbazel
INFO: Found 1 target...
ERROR: /Users/paul.crofts/Documents/go/src/github.com/margic/logrusbazel/vendor/golang.org/x/sys/unix/BUILD.bazel:3:1: GoCompile vendor/golang.org
/x/sys/unix/~pure_stripped~go_default_library~/~partial.a failed (Exit 1): compile failed: error executing command
  (cd /private/var/tmp/_bazel_paul.crofts/fc93648e8fa8d6c7ba0f8e338fa9b101/execroot/__main__ && \
  exec env - \
  bazel-out/host/bin/external/io_bazel_rules_go/go/tools/builders/compile -go bazel-out/host/bin/external/go_stdlib_linux_amd64_pure/bin/go -root_file bazel-out/host/bin/external/go_stdlib_linux_amd64_pure/ROOT -goos linux -goarch amd64 '-cgo=0' -package_list external/go_sdk/packages.txt -src bazel-out/darwin_x86_64-fastbuild/bin/vendor/golang.org/x/sys/unix/go_default_library.cgo.dir/vendor_golang.org_x_sys_unix_env_unset.cgo1.go -src bazel-out/darwin_x86_64-fastbuild/bin/vendor/golang.org/x/sys/unix/go_default_library.cgo.dir/vendor_golang.org_x_sys_unix_constants.cgo1.go -src bazel-out/darwin_x86_64-fastbuild/bin/vendor/golang.org/x/sys/unix/go_default_library.cgo.dir/vendor_golang.org_x_sys_unix_dev_darwin.cgo1.go -src bazel-out/darwin_x86_64-fastbuild/bin/vendor/golang.org/x/sys/unix/go_default_library.cgo.dir/vendor_golang.org_x_sys_unix_dirent.cgo1.go -srcbazel-out/darwin_x86_64-fastbuild/bin/vendor/golang.org/x/sys/unix/go_default_library.cgo.dir/vendor_golang.org_x_sys_unix_endian_little.cgo1.go -src bazel-out/darwin_x86_64-fastbuild/bin/vendor/golang.org/x/sys/unix/go_default_library.cgo.dir/vendor_golang.org_x_sys_unix_env_unix.cgo1.go -src bazel-out/darwin_x86_64-fastbuild/bin/vendor/golang.org/x/sys/unix/go_default_library.cgo.dir/vendor_golang.org_x_sys_unix_flock.cgo1.go -src bazel-out/darwin_x86_64-fastbuild/bin/vendor/golang.org/x/sys/unix/go_default_library.cgo.dir/vendor_golang.org_x_sys_unix_pagesize_unix.cgo1.go -src bazel-out/darwin_x86_64-fastbuild/bin/vendor/golang.org/x/sys/unix/go_default_library.cgo.dir/vendor_golang.org_x_sys_unix_race0.cgo1.go -src bazel-out/darwin_x86_64-fastbuild/bin/vendor/golang.org/x/sys/unix/go_default_library.cgo.dir/vendor_golang.org_x_sys_unix_sockcmsg_unix.cgo1.go -src bazel-out/darwin_x86_64-fastbuild/bin/vendor/golang.org/x/sys/unix/go_default_library.cgo.dir/vendor_golang.org_x_sys_unix_str.cgo1.go -src bazel-out/darwin_x86_64-fastbuild/bin/vendor/golang.org/x/sys/unix/go_default_library.cgo.dir/vendor_golang.org_x_sys_unix_syscall.cgo1.go -src bazel-out/darwin_x86_64-fastbuild/bin/vendor/golang.org/x/sys/unix/go_default_library.cgo.dir/vendor_golang.org_x_sys_unix_syscall_bsd.cgo1.go -src bazel-out/darwin_x86_64-fastbuild/bin/vendor/golang.org/x/sys/unix/go_default_library.cgo.dir/vendor_golang.org_x_sys_unix_syscall_darwin.cgo1.go -src bazel-out/darwin_x86_64-fastbuild/bin/vendor/golang.org/x/sys/unix/go_default_library.cgo.dir/vendor_golang.org_x_sys_unix_syscall_darwin_amd64.cgo1.go -src bazel-out/darwin_x86_64-fastbuild/bin/vendor/golang.org/x/sys/unix/go_default_library.cgo.dir/vendor_golang.org_x_sys_unix_syscall_unix.cgo1.go -src bazel-out/darwin_x86_64-fastbuild/bin/vendor/golang.org/x/sys/unix/go_default_library.cgo.dir/vendor_golang.org_x_sys_unix_syscall_unix_gc.cgo1.go -src bazel-out/darwin_x86_64-fastbuild/bin/vendor/golang.org/x/sys/unix/go_default_library.cgo.dir/vendor_golang.org_x_sys_unix_timestruct.cgo1.go -src bazel-out/darwin_x86_64-fastbuild/bin/vendor/golang.org/x/sys/unix/go_default_library.cgo.dir/vendor_golang.org_x_sys_unix_zerrors_darwin_amd64.cgo1.go -src bazel-out/darwin_x86_64-fastbuild/bin/vendor/golang.org/x/sys/unix/go_default_library.cgo.dir/vendor_golang.org_x_sys_unix_zsyscall_darwin_amd64.cgo1.go -src bazel-out/darwin_x86_64-fastbuild/bin/vendor/golang.org/x/sys/unix/go_default_library.cgo.dir/vendor_golang.org_x_sys_unix_zsysnum_darwin_amd64.cgo1.go -src bazel-out/darwin_x86_64-fastbuild/bin/vendor/golang.org/x/sys/unix/go_default_library.cgo.dir/vendor_golang.org_x_sys_unix_ztypes_darwin_amd64.cgo1.go -o 'bazel-out/darwin_x86_64-fastbuild/bin/vendor/golang.org/x/sys/unix/~pure_stripped~go_default_library~/~partial.a' -trimpath . -I . -- -p golang.org/x/sys/unix bazel-out/darwin_x86_64-fastbuild/bin/vendor/golang.org/x/sys/unix/go_default_library.cgo.dir/_cgo_gotypes.go bazel-out/darwin_x86_64-fastbuild/bin/vendor/golang.org/x/sys/unix/go_default_library.cgo.dir/_cgo_import.go)

Use --sandbox_debug to see verbose messages from the sandbox.
bazel-out/darwin_x86_64-fastbuild/bin/vendor/golang.org/x/sys/unix/go_default_library.cgo.dir/vendor_golang.org_x_sys_unix_flock.cgo1.go:16:42: undefined: Flock_t
bazel-out/darwin_x86_64-fastbuild/bin/vendor/golang.org/x/sys/unix/go_default_library.cgo.dir/vendor_golang.org_x_sys_unix_sockcmsg_unix.cgo1.go:37:18: undefined: Cmsghdr
bazel-out/darwin_x86_64-fastbuild/bin/vendor/golang.org/x/sys/unix/go_default_library.cgo.dir/vendor_golang.org_x_sys_unix_sockcmsg_unix.cgo1.go:43:9: undefined: Cmsghdr
2017/11/09 13:39:09 error running compiler: exit status 1
Target //:logrusbazel failed to build
INFO: Elapsed time: 5.296s, Critical Path: 5.02s
```

**Comment by jayconrod** [comment] 2017-11-09 22:07
I think this is a duplicate of #995. Does building with --cpu=k8 fix this?

**Comment by margic** [comment] 2017-11-09 22:58
no building with --cpu=k8 does not fix this.

**Comment by ianthehat** [comment] 2017-11-10 02:48
It fixes the error you reported, but still does not work.
The problem is that logrus depends on x/sys/unix, which uses cgo, and we don't support cross compiling with cgo right now.

**Comment by margic** [comment] 2017-11-10 15:01
I just tried a similar project changing from logrus to glog. And it worked with --cpu k8. I guess I'm using glog now.

I can live with that.

**Comment by margic** [comment] 2017-11-10 15:12
So off topic, but I'm checking out uber's zap for logging. It looks very interesting.

**Comment by ianthehat** [comment] 2017-11-10 16:19
I would really like to support cross compiling cgo, but it's seriously non trivial, you can't even cross compile the standard library correctly with cgo enabled right now (go build can't do this either, so I am not likely to even start work on it before we at least reach feature parity with everything go build *can* do).
We do need to document these limitations better,  but as I have not quite finished cross compilation support it's basically undocumented right now.

I know uber are using Bazel, maybe they are a good place to start with upstreaming BUILD files so you can use http_archive instead of go_repository. We could start building a list of libraries that work well with go in Bazel.

**Comment by margic** [comment] 2017-11-10 20:17
I just ran into the same problem with viper another very common library. It should compile with CGO_ENABLED=0 is there a way to pass that to the rules or is it already doing tha?

**Comment by ianthehat** [comment] 2017-11-10 20:37
It compiles with CGO_ENABLED=0 if you are in "pure" mode, which is implied by cross compilation.
I believe this is identical behavior to go build.
If you can find something that correctly compiles with go build (in cross compilation mode) but does not with bazel, then it's probably something I can fix, but if go build can't handle it then we are stuck.

**Comment by margic** [comment] 2017-11-10 21:06
I think I have such an example but based on the start of the conversation let me double check.

**Comment by ianthehat** [comment] 2017-11-10 21:22
Note that pure mode and cross compilation is only fully supported at the tip of rules_go (within the last 2 days)

**Comment by margic** [comment] 2017-11-10 22:33
I just update my example to the current master and checked in the vendor folder to make it easy to checkout and run 
`bazel build --cpu=k8 --features=pure //service1:service1`

this build has viper in it and fails. It will build with CGO_ENABLED=0 but not with bazel. Any chance you could take a look and comment? I know it's a big ask.
https://github.com/margic/gobazel

**Comment by jayconrod** [comment] 2017-11-13 19:38
There is a real bug here. We are building cgo code in a pure configuration and invoking the external linker. It also seems that the host compiler and host external linker are being used, even though this is a cross build.

Ian has been looking at this over the weekend. Hopefully we'll have a fix out soon.

**Comment by margic** [comment] 2017-11-14 20:40
Nice, I'll check this out.

**Closed** 2017-11-23 02:29 UTC

**Comment by mrinalwadhwa** [comment] 2018-01-24 04:24
what is the right way to compile on macos for linux?
```
> bazel build --cpu=k8 --features=pure //examples/deb_packages/deb_packages_base:check_certs
ERROR: No default_toolchain found for cpu 'k8'. Valid cpus are: [
  darwin,
  armeabi-v7a,
  x64_windows,
  x64_windows_msvc,
  x64_windows_msys,
  s390x,
  ios_x86_64,
]
INFO: Elapsed time: 0.183s
FAILED: Build did NOT complete successfully (0 packages loaded)
```
