### ISSUE TITLE
Skipping "testdata" directory in Gazelle broken for "github.com/golang/protobuf"

### ISSUE THREAD

**Issue by ains** [bazelbuild/rules_go#497] opened 2017-06-01 09:12 UTC
Testdata directories are excluded from BUILD file generation by Gazelle at the moment (https://github.com/bazelbuild/rules_go/blob/master/go/tools/gazelle/packages/walk.go#L56)

However for "github.com/golang/protobuf", there exists a testdata directory contains Go code that you should be able to import. https://github.com/golang/protobuf/tree/master/proto/testdata

Is there a reason we need to skip _all_ testdata directories with Gazelle, and would it be possible to relax the constraint to perhaps be testdata directories without Go sources should be skipped?

**Comment by jayconrod** [comment] 2017-06-01 14:04
We should relax this constraint. Gazelle should try to reproduce the behavior of `go/build`, and this is a case where we are too strict.

I'll close this as a duplicate of #415, which is the same issue in `golang.org/x/crypto`. I'll take a look at this soon, hopefully today.

**Closed by jayconrod** 2017-06-01 14:04 UTC
