### ISSUE TITLE
go_proto_library builds fail with --cpu=k8

### ISSUE THREAD

**Issue by mikelueck** [bazelbuild/rules_go#990] opened 2017-11-06 04:02 UTC
Error message:

	File "/private/var/tmp/_bazel_mike/00b041f53c11f89102e9b74cd3bb4834/external/io_bazel_rules_go/proto/def.bzl", line 26, in _go_proto_library_impl
		go_toolchain.actions.library(ctx, go_toolchain = go_toolchain, mo..., <6 more arguments>)
	File "/private/var/tmp/_bazel_mike/00b041f53c11f89102e9b74cd3bb4834/external/io_bazel_rules_go/go/private/actions/library.bzl", line 120, in go_toolchain.actions.library
		go_toolchain.actions.archive(ctx, go_toolchain = go_toolchain, mo..., <4 more arguments>)
	File "/private/var/tmp/_bazel_mike/00b041f53c11f89102e9b74cd3bb4834/external/io_bazel_rules_go/go/private/actions/archive.bzl", line 96, in go_toolchain.actions.archive
		fail("Archive mode does not match {} ...)))
Archive mode does not match @com_github_golang_protobuf//proto:go_default_library is stripped expected pure_stripped.
ERROR: Analysis of target '//model/proto:proto_go_proto' failed; build aborted: Analysis of target '//model/proto:proto_go_proto' failed; build aborted.

Any recommendations for fixing this error?

Environment:
Mac
Bazel 0.7.0
Go version go1.9.2 darwin/amd64

**Comment by xoebus** [comment] 2017-11-07 23:36
Passing the `--features=pure` flag made this work in my build.

**Comment by ianthehat** [comment] 2017-11-07 23:44
I have been looking into this, and I now know what the problem is, but I don't have a good solution yet.
The issue is that the com_github_golang_protobuf//proto:go_default_library dependancy is injected by the toolchain, and deps of the toolchain are always in host mode instead of target mode, and thus are not valid. This is a bug/missing feature of Bazel, and won't be fixed before 0.8, so we might have to find a temporary work around.

**Comment by mikelueck** [comment] 2017-11-08 00:01
Gah...initially I had hopes that --features=pure would work but apparently not:

import /private/var/tmp/_bazel_mike/00b041f53c11f89102e9b74cd3bb4834/bazel-sandbox/4160208225850885526/execroot/__main__/bazel-out/host/bin/external/com_github_golang_protobuf/proto/~pure_stripped~go_default_library~/github.com/golang/protobuf/proto.a: object is [darwin amd64 go1.9.2 X:framepointer] expected [linux amd64 go1.9.2 X:framepointer]
2017/11/07 18:55:24 error running compiler: exit status 1
INFO: Elapsed time: 1.036s, Critical Path: 0.71s

It seems exactly as you said ianthehat.  I'd love a workaround :)...just to keep me going.

In general I'm a big Bazel fan, but it sure is hard being on the bleeding edge :).  Thanks for all the hard work.

**Comment by xoebus** [comment] 2017-11-08 01:34
Ah, my bad. It seemed as if `—feature pure` worked but it caused something earlier to fail rather than something later.

**Closed** 2017-12-04 15:52 UTC
