### ISSUE TITLE
go_config_info.static: 'NoneType' value has no field or method 'static'

### ISSUE THREAD

**Issue by linzhp** [bazelbuild/rules_go#2523] opened 2020-05-29 16:57 UTC
`go_config_info` may be `None` before calling `get_mode`:
https://github.com/bazelbuild/rules_go/blob/6ed0b2f05933a920f4ed9408948123d0e3ad3e03/go/private/context.bzl#L351-L369

However, `get_mode` requires it to be not `None`: https://github.com/bazelbuild/rules_go/blob/6ed0b2f05933a920f4ed9408948123d0e3ad3e03/go/private/mode.bzl#L70

As a result, the build may crash in some settings.

### What version of rules_go are you using?

v0.23.2

### What version of gazelle are you using?

v0.21.1

### What version of Bazel are you using?

3.1.0

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

Darwin amd64

### What did you do?

```bash
$ bazel build //:gazelle
```

### What did you expect to see?

Build successfully

### What did you see instead?
```
INFO: Invocation ID: 19e0616d-6118-41ef-b3db-321e84427f81
INFO: SHA256 (https://github.com/bazelbuild/rules_go/releases/download/v0.23.2/rules_go-v0.23.2.tar.gz) = 0c10738a488239750dbf35336be13252bad7c74348f867d30c3c3e0001906096
DEBUG: Rule 'io_bazel_rules_go' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "0c10738a488239750dbf35336be13252bad7c74348f867d30c3c3e0001906096"
DEBUG: Repository io_bazel_rules_go instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_zplin/db67431f618bf23018777556a2edc2eb/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
INFO: SHA256 (https://github.com/bazelbuild/bazel-gazelle/releases/download/v0.21.1/bazel-gazelle-v0.21.1.tar.gz) = cdb02a887a7187ea4d5a27452311a75ed8637379a1287d8eeb952138ea485f7d
DEBUG: Rule 'bazel_gazelle' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "cdb02a887a7187ea4d5a27452311a75ed8637379a1287d8eeb952138ea485f7d"
DEBUG: Repository bazel_gazelle instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_zplin/db67431f618bf23018777556a2edc2eb/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: /private/var/tmp/_bazel_zplin/db67431f618bf23018777556a2edc2eb/external/io_bazel_rules_go/proto/wkt/BUILD.bazel:109:17: in @io_bazel_rules_go//go/private:rules/aspect.bzl%go_archive_aspect[pure="off",static="off",msan="off",race="off",goos="auto",goarch="auto"] aspect on go_proto_wrapper rule @io_bazel_rules_go//proto/wkt:wrappers_wrapper: 
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_zplin/db67431f618bf23018777556a2edc2eb/external/io_bazel_rules_go/proto/wkt/BUILD.bazel", line 109
		@io_bazel_rules_go//go/private:rules/aspect.bzl%go_archive_aspect(...)
	File "/private/var/tmp/_bazel_zplin/db67431f618bf23018777556a2edc2eb/external/io_bazel_rules_go/go/private/rules/aspect.bzl", line 38, in _go_archive_aspect_impl
		go_context(ctx, ctx.rule.attr)
	File "/private/var/tmp/_bazel_zplin/db67431f618bf23018777556a2edc2eb/external/io_bazel_rules_go/go/private/context.bzl", line 371, in go_context
		get_mode(ctx, toolchain, <2 more arguments>)
	File "/private/var/tmp/_bazel_zplin/db67431f618bf23018777556a2edc2eb/external/io_bazel_rules_go/go/private/mode.bzl", line 68, in get_mode
		_ternary(<3 more arguments>)
	File "/private/var/tmp/_bazel_zplin/db67431f618bf23018777556a2edc2eb/external/io_bazel_rules_go/go/private/mode.bzl", line 70, in _ternary
		go_config_info.static
'NoneType' value has no field or method 'static'
ERROR: Analysis of target '//:gazelle' failed; build aborted: Analysis of target '@io_bazel_rules_go//proto/wkt:wrappers_wrapper' failed
INFO: Elapsed time: 26.887s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (251 packages loaded, 7963 targets configured)
```

**Comment by jayconrod** [comment] 2020-06-01 17:29
Marking as a bug, since `get_mode` should be prepared for `go_config_info` to be `None`.

The error here is very surprising though. Building Gazelle should not cause this, and I couldn't get that to reproduce. From the stack, it looks like `go_archive_aspect` was activated somehow. That should have been deleted earlier. It's not wired in anywhere. Are there any local changes to use that aspect?

**Comment by linzhp** [comment] 2020-06-01 18:59
Gazelle is still using `go_archive_aspect`: https://github.com/bazelbuild/bazel-gazelle/blob/master/internal/gazelle_binary.bzl#L139

**Comment by jayconrod** [comment] 2020-06-02 15:24
That's an unfortunate oversight in Gazelle. I'll fix that.

I still couldn't reproduce the problem, though reproducing it shouldn't be necessary for a fix. `gazelle_binary` is defined with `go_rule`, which adds a dependency on `@io_bazel_rules_go//:go_context_data`, which has `GoConfigInfo`. `go_archive_aspect` passes the attributes from the rule being analyzed to `go_context`, so `go_config_info` shouldn't be `None`.

**Comment by linzhp** [comment] 2020-06-02 15:50
I couldn't reproduce it outside Uber's Go monorepo either. Probably need some more debugging.

**Closed** 2020-06-02 16:46 UTC
Labels: bug, go
