### ISSUE TITLE
Cross Compiling jessevdk/go-flags

### ISSUE THREAD

**Issue by xoebus** [bazelbuild/rules_go#995] opened 2017-11-07 23:07 UTC
Hi there,

I'm trying to cross compile one of [my projects](https://github.com/xoebus/cryptdo) which depends on [jessevdk/go-flags](https://github.com/jessevdk/go-flags). The go-flags library has some (fairly complex) build directives to allow cross-platform querying of the terminal width. I *think* that they're confusing gazelle and making the build fail.

**Versions**

Bazel: 0.7.0
Go Rules: 0.7.0

**Command**

```
bazel build --experimental_platforms=@io_bazel_rules_go//go/toolchain:linux_amd64 --features=pure //cmd/cryptdo
```

**Output**

```
INFO: Found 1 target...
ERROR: /private/var/tmp/_bazel_cb/314e6db7a04fa07463806a43d1e0e1ca/external/com_github_jessevdk_go_flags/BUILD.bazel:3:1: GoCompile external/com_github_jessevdk_go_flags/~pure_st
ripped~go_default_library~/github.com/jessevdk/go-flags.a failed (Exit 1).
external/com_github_jessevdk_go_flags/termsize.go:18:5: undefined: tIOCGWINSZ
external/com_github_jessevdk_go_flags/termsize.go:21:12: undefined: tIOCGWINSZ
2017/11/07 14:16:12 error running compiler: exit status 1
Target //cmd/cryptdo:cryptdo failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 32.196s, Critical Path: 26.33s
```

**Generated BUILD.bazel File**

```
load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "go_default_library",
    srcs = [
        "arg.go",
        "closest.go",
        "command.go",
        "completion.go",
        "convert.go",
        "error.go",
        "flags.go",
        "group.go",
        "help.go",
        "ini.go",
        "man.go",
        "multitag.go",
        "option.go",
        "optstyle_other.go",
        "parser.go",
        "termsize.go",
        "tiocgwinsz_other.go",
    ] + select({
        "@io_bazel_rules_go//go/platform:darwin_amd64": [
            "tiocgwinsz_bsdish.go",
        ],
        "@io_bazel_rules_go//go/platform:linux_amd64": [
            "tiocgwinsz_linux.go",
        ],
        "@io_bazel_rules_go//go/platform:windows_amd64": [
            "optstyle_windows.go",
            "termsize_nosysioctl.go",
        ],
        "//conditions:default": [],
    }),
    importpath = "github.com/jessevdk/go-flags",
    visibility = ["//visibility:public"],
)
```

I'm confused by the "undefined" error because, if anything, it should be defined twice (once in `tiocgwinsz_other.go` and once in `tiocgwinsz_linux.go`).

**Comment by xoebus** [comment] 2017-11-08 01:38
This might be self inflicted by the addition of the `pure` flag. I’ll keep digging.

**Comment by xoebus** [comment] 2017-11-08 01:54
I can reproduce in isolation with no `--features=pure` flag too.

```
$ bazel build --experimental_platforms=@io_bazel_rules_go//go/toolchain:linux_amd64 @com_github_jessevdk_go_flags//:go_default_library
INFO: Found 1 target...
ERROR: /private/var/tmp/_bazel_cb/314e6db7a04fa07463806a43d1e0e1ca/external/com_github_jessevdk_go_flags/BUILD.bazel:3:1: GoCompile external/com_github_jessevdk_go_flags/~pure_stripped~go_default_library~/github.com/jessevdk/go-flags.a failed (Exit 1).
external/com_github_jessevdk_go_flags/termsize.go:18:5: undefined: tIOCGWINSZ
external/com_github_jessevdk_go_flags/termsize.go:21:12: undefined: tIOCGWINSZ
2017/11/07 17:51:18 error running compiler: exit status 1
Target @com_github_jessevdk_go_flags//:go_default_library failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 3.433s, Critical Path: 2.64s
```

**Comment by jayconrod** [comment] 2017-11-08 19:10
The cause of this is the current mismatch between Bazel platforms and the `config_setting` rules we've defined in `@io_bazel_rules_go//go/platform`, which rely on the `--cpu` value. When Bazel 0.8 is released, these rules will be changed to match the platform being used, but as of 0.7, the platform constraints aren't exposed to `config_setting`.

As a workaround, you can try building with the --cpu flag instead. I was able to cross-compile this library from darwin/amd64 to linux/amd64 like this:

```
bazel build --cpu=k8 :go_default_library
```

I'll leave this issue open so we can verify it's fixed when Bazel 0.8 is released.

**Comment by xoebus** [comment] 2017-11-08 19:14
That worked! Thanks for your help. I'm looking forward to Bazel 0.8.

**Comment by margic** [comment] 2017-11-09 20:42
similar issue #1009

**Comment by jayconrod** [comment] 2017-12-27 20:06
Closing old Gazelle issues. This should be working. If not, please file a new issue at bazelbuild/bazel-gazelle.

**Closed by jayconrod** 2017-12-27 20:06 UTC
Labels: bug, gazelle
