### ISSUE TITLE
nogo: exclude targets globally

### ISSUE THREAD

**Issue by symbiont-sean-lyons** [bazelbuild/rules_go#2794] opened 2021-01-22 19:33 UTC
My team currently uses golangci-lint as an analysis runner but would love to adopt something more "official" that can be expected to work well with bazel.

We currently lean on the ability to globally exclude files according to some list of patterns.  More specifically, we lean on this feature to ignore vendored files when doing static analysis.  Based on documentation, it seems that nogo only has the ability to exclude files on a per-linter basis.

Ideally, we would be able to configure nogo like so

BUILD.bazel
```
nogo(
  name = "lint",
  deps = [
    ...
  ],
  exclude = ["//vendor"],
  visibility = ["//visibility:public"],
)
```

or alternatively maybe we could use a JSON config and skip specific file patterns rather than build targets.

BUILD.bazel
```
nogo(
    name = "lint",
    deps = [
      ...
    ],
    config = "config.json",
    visibility = ["//visibility:public"],
)
```

config.json
```
{
  "exclude_files": ["vendor/.*"]
}
```

I guess I'm partial to the exclusion being in the nogo definition so that the JSON schema can avoid acknowledging "special" keys that do not reference analyzers.

**Comment by jayconrod** [comment] 2021-02-05 17:54
Agreed that nogo should have this capability. The configuration format is pretty limited. I'll close this issue as a duplicate of #2513 though, which is similar.

**Closed by jayconrod** 2021-02-05 17:54 UTC
