### ISSUE TITLE
add rules for go proto API v2

### ISSUE THREAD

**Issue by ghasemloo** [bazelbuild/rules_go#2587] opened 2020-08-04 15:20 UTC
creating a bug so we can track this.

Go has a new proto API: https://blog.golang.org/protobuf-apiv2 
The bazel rules for go proto do not yet support v2 API

The protoc and its grpc plugin seem to work:
https://godoc.org/google.golang.org/grpc/cmd/protoc-gen-go-grpc
https://pkg.go.dev/google.golang.org/grpc/cmd/protoc-gen-go-grpc
in
https://github.com/grpc/grpc-go

```shell
go get -u google.golang.org/protobuf/cmd/protoc-gen-go
go get -u google.golang.org/grpc/cmd/protoc-gen-go-grpc

protoc --go_out=paths=source_relative:. --go-grpc_out=paths=source_relative:. --go_opt=paths=source_relative --go-grpc_opt=paths=source_relative FILE
```

**Comment by jayconrod** [comment] 2020-08-04 16:18
I think this is a duplicate of #2587. If something isn't covered there, let's add to that issue instead.

Note that `google.golang.org/grpc/cmd/protoc-gen-go-grpc` is not part of any release, so I believe it's still under development. I'd rather not add support until it's stable.

**Closed by jayconrod** 2020-08-04 16:18 UTC

**Comment by ghasemloo** [comment] 2020-08-04 17:50
That duplicate bug seems to be this bug itself, did you intend to close this as a duplicate of another one?

If I am not mistakedn, protoc-gen-go-grpc seems to be part of their latest release:
https://github.com/grpc/grpc-go/tree/v1.31.0/cmd/protoc-gen-go-grpc

**Comment by ghasemloo** [comment] 2020-08-04 17:51
did you mean https://github.com/bazelbuild/rules_go/issues/2522?

**Comment by jayconrod** [comment] 2020-08-04 18:49
Oops yes, #2522.
