### ISSUE TITLE
Cannot ignore "src/vendor"

### ISSUE THREAD

**Issue by linzhp** [bazelbuild/rules_go#2350] opened 2020-01-26 17:10 UTC
### What version of rules_go are you using?

v0.21.0

### What version of gazelle are you using?

https://github.com/bazelbuild/bazel-gazelle/commit/c8b8db60089ed71e70ea3be0d12af1db1c61e71e

### What version of Bazel are you using?

2.0.0

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

macOS 10.15.2, amd64

### What did you do?

* Add "src/vendor/" to the `.bazelignore` file at the root of a Bazel repository, like https://github.com/bazelbuild/bazel-gazelle
* Set Go toolchain version to be 1.13.6
* Build a Go target, e.g., `bazel build //cmd/gazelle`

### What did you expect to see?

Build complete successfully

### What did you see instead?

```
INFO: Analyzed target //cmd/gazelle:gazelle (3 packages loaded, 18 targets configured).
INFO: Found 1 target...
ERROR: /Users/zplin/gocode/src/github.com/bazelbuild/bazel-gazelle/cmd/gazelle/BUILD.bazel:4:1: GoLink cmd/gazelle/darwin_amd64_stripped/gazelle failed (Exit 1) builder failed: error executing command bazel-out/host/bin/external/go_sdk/builder link -sdk external/go_sdk -installsuffix darwin_amd64 -arc ... (remaining 54 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
external/go_sdk/pkg/tool/darwin_amd64/link: cannot open file : open : no such file or directory
link: error running subcommand: exit status 2
cannot find package vendor/golang.org/x/net/http/httpguts (using -importcfg)
cannot find package vendor/golang.org/x/net/http2/hpack (using -importcfg)
cannot find package vendor/golang.org/x/net/idna (using -importcfg)
cannot find package vendor/golang.org/x/net/http/httpproxy (using -importcfg)
cannot find package vendor/golang.org/x/crypto/chacha20poly1305 (using -importcfg)
cannot find package vendor/golang.org/x/crypto/cryptobyte (using -importcfg)
cannot find package vendor/golang.org/x/crypto/curve25519 (using -importcfg)
cannot find package vendor/golang.org/x/crypto/hkdf (using -importcfg)
cannot find package vendor/golang.org/x/net/dns/dnsmessage (using -importcfg)
cannot find package vendor/golang.org/x/net/route (using -importcfg)
Target //cmd/gazelle:gazelle failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 7.718s, Critical Path: 2.06s
INFO: 3 processes: 3 darwin-sandbox.
FAILED: Build did NOT complete successfully
```

## Note
Gazelle doesn't have `src/vendor` directory, and the error is complaining about `vendor` not `src/vendor`. Not sure why ignoring `src/vendor` would cause this error.

This issue occurs in Bazel 2.0 and Go 1.13 but doesn't occur in Bazel 1.1 or Go 1.12

**Comment by jayconrod** [comment] 2020-01-27 17:24
Duplicate of #2016 
Caused by bazelbuild/bazel#10534

It looks like the packages listed in the error message are from the `src/vendor` directory in `@go_sdk`. These can't be excluded from the build. Packages in the standard library depend on them.

Go's approach to vendoring changed in 1.13. Before that, we copied packages into `internal` directories and changed their import paths. Since 1.13, we just use `go mod vendor`, and we added some special cases to make it work both in `GOPATH` and module mode. So that might explain why you didn't see this earlier.

**Closed by jayconrod** 2020-01-27 17:24 UTC
