### ISSUE TITLE
'@go_sdk//:libs' does not produce any go_sdk libs files (expected .a)

### ISSUE THREAD

**Issue by sevki** [bazelbuild/rules_go#2016] opened 2019-03-29 12:25 UTC
### What version of rules_go are you using?
0.18.1

### What version of gazelle are you using?
0.17.0

### What version of Bazel are you using?
```
INFO: Invocation ID: f919b3c4-0d0d-4ed8-a369-dd7cff3d08c8
Build label: 0.22.0- (@non-git)
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Jan 28 19:53:21 2019 (1548705201)
Build timestamp: 1548705201
Build timestamp as int: 1548705201
```

### Does this issue reproduce with the latest releases of all the above?
yes

### What operating system and processor architecture are you using?
```
Linux faraday 5.0.2-arch1-1-ARCH #1 SMP PREEMPT Thu Mar 14 18:47:49 UTC 2019 x86_64 GNU/Linux
```

### What did you do?

```
load("@bazel_gazelle//:def.bzl", "gazelle")

# gazelle:prefix github.com/example/project
gazelle(name = "gazelle")
```

### What did you expect to see?
gazelle run

### What did you see instead?
```
INFO: Invocation ID: d0657e05-6d3c-4fb9-ada2-b56251f5de96
Loading: 
Loading: 0 packages loaded
Analyzing: target //:gazelle (1 packages loaded, 0 targets configured)
ERROR: /home/sevki/.cache/bazel/_bazel_sevki/182253000d927481e59ea96d87a036b0/external/go_sdk/BUILD.bazel:37:12: in libs attribute of go_sdk rule @go_sdk//:go_sdk: '@go_sdk//:libs' does not produce any go_sdk libs files (expected .a)
ERROR: /home/sevki/.cache/bazel/_bazel_sevki/182253000d927481e59ea96d87a036b0/external/go_sdk/BUILD.bazel:38:15: in headers attribute of go_sdk rule @go_sdk//:go_sdk: '@go_sdk//:headers' does not produce any go_sdk headers files (expected .h)
ERROR: Analysis of target '//:gazelle' failed; build aborted: Analysis of target '@go_sdk//:go_sdk' failed; build aborted
INFO: Elapsed time: 1.110s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (5 packages loaded, 1 target configured)
ERROR: Build failed. Not running target
FAILED: Build did NOT complete successfully (5 packages loaded, 1 target configured)
```

**Comment by linzhp** [comment] 2020-01-02 18:57
Got the same error today with Bazel 1.2.1, rules_go 0.20.3 and Gazelle d609195564c406705d5cbcb4b08111436c2348b0

Did you figure out how to solve this issue?

**Comment by sevki** [comment] 2020-01-06 10:39
@linzhp nope

**Comment by csstaub** [comment] 2020-01-06 17:14
I was able to reproduce this with Bazel 1.2.0 and 2.0.0, seems to be an issue with bazelignore rules messing with how the go_sdk is loaded somehow.

Here's a min example to trigger the bug:

WORKSPACE:
```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive", "http_file")

http_archive(
    name = "io_bazel_rules_go",
    urls = [
        "https://storage.googleapis.com/bazel-mirror/github.com/bazelbuild/rules_go/releases/download/v0.20.3/rules_go-v0.20.3.tar.gz",
        "https://github.com/bazelbuild/rules_go/releases/download/v0.20.3/rules_go-v0.20.3.tar.gz",
    ],
    sha256 = "e88471aea3a3a4f19ec1310a55ba94772d087e9ce46e41ae38ecebe17935de7b",
)

http_archive(
    name = "bazel_gazelle",
    urls = [
        "https://storage.googleapis.com/bazel-mirror/github.com/bazelbuild/bazel-gazelle/releases/download/v0.19.1/bazel-gazelle-v0.19.1.tar.gz",
        "https://github.com/bazelbuild/bazel-gazelle/releases/download/v0.19.1/bazel-gazelle-v0.19.1.tar.gz",
    ],
    sha256 = "86c6d481b3f7aedc1d60c1c211c6f76da282ae197c3b3160f54bd3a8f847896f",
)

load("@io_bazel_rules_go//go:deps.bzl", "go_rules_dependencies", "go_register_toolchains")

go_rules_dependencies()

go_register_toolchains()

load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies", "go_repository")

gazelle_dependencies()
```

BUILD.bazel:
```
load("@bazel_gazelle//:def.bzl", "gazelle")

# gazelle:prefix github.com/example/example
gazelle(
    name = "gazelle",
)
```

.bazelignore:
```
pkg
```

.bazelversion:
```
2.0.0
```

Output:
```
❯❯❯ bazel clean --expunge && bazel run //:gazelle
INFO: Starting clean.
Starting local Bazel server and connecting to it...
ERROR: /private/var/tmp/_bazel_cstaub/ce3be99227fe0366c516305ad66df037/external/go_sdk/BUILD.bazel:30:1: in libs attribute of go_sdk rule @go_sdk//:go_sdk: '@go_sdk//:libs' does not produce any go_sdk libs files (expected .a)
ERROR: /private/var/tmp/_bazel_cstaub/ce3be99227fe0366c516305ad66df037/external/go_sdk/BUILD.bazel:30:1: in headers attribute of go_sdk rule @go_sdk//:go_sdk: '@go_sdk//:headers' does not produce any go_sdk headers files (expected .h)
ERROR: Analysis of target '//:gazelle' failed; build aborted: Analysis of target '@go_sdk//:go_sdk' failed; build aborted
INFO: Elapsed time: 8.515s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (43 packages loaded, 6299 targets configured)
FAILED: Build did NOT complete successfully (43 packages loaded, 6299 targets configured)
    Fetching @local_config_cc; fetching
    Fetching @org_golang_x_tools; Cloning c9f9432ec4b21a28c4d47f172513698febb68e9c of https://go.googlesource.com/tools
    Fetching @org_golang_x_sync; Restarting.
    Fetching @bazel_gazelle_go_repository_config; Restarting.
    Fetching @com_github_pmezard_go_difflib; Restarting.
    Fetching @com_github_bazelbuild_buildtools; Restarting.
    Fetching @com_github_pelletier_go_toml; Restarting.
    Fetching @bazel_gazelle_go_repository_tools; Restarting.
```

The bug goes away if I do one of the following:
* delete the .bazelignore file or remove the "pkg" line
* switch to an older version of Bazel (1.1.0 or earlier)

**Comment by csstaub** [comment] 2020-01-06 17:19
As for a workaround, in our case we had "pkg" in the .bazelignore file because we set our Go monorepo to $GOPATH for historical reasons. Replacing the "pkg" line in our .bazelignore file with more specific entries like "pkg/mod" and "pkg/sumdb" (but not including any "pkg/{goos}_{goarch}" folders) appears to work for now.

**Comment by jayconrod** [comment] 2020-01-06 17:59
@csstaub Thanks for posting a repro. Hadn't heard of `.bazelignore` files before. That would definitely cause problems like this.

@linzhp @sevki Was this the cause of the issue for you? If not, can you post enough information to reproduce (with Bazel 1.2.0 or later)?

**Comment by linzhp** [comment] 2020-01-06 21:26
@jayconrod The issue is resolved @csstaub's approach 

>  "pkg" line in our .bazelignore file with more specific entries like "pkg/mod" and "pkg/sumdb" (but not including any "pkg/{goos}_{goarch}" folders)

Thanks @csstaub for figuring this out!

**Comment by jayconrod** [comment] 2020-01-06 21:37
Cool, I'll close this then.

**Closed by jayconrod** 2020-01-06 21:37 UTC

**Comment by linzhp** [comment] 2020-01-06 22:34
@jayconrod I think what @csstaub proposed is more of a workaround than a solution. The root cause, I believe is somewhere on rules_go that depends on `pkg/{goos}_{goarch}`, which is wrong. `.bazelignore` is a [documented features](https://docs.bazel.build/versions/master/guide.html#.bazelignore) of Bazel, which is doing what it is supposed to do. So I think we should leave this issue open until the root cause is fixed.

**Comment by csstaub** [comment] 2020-01-06 22:48
Have to agree with @linzhp here, I should also mention this breaks the build even if the repo is not set to $GOPATH. There's many potential reasons I could see folks wanting to ignore a directory named `pkg` in their repos and having it break builds like this seems like a bug to me especially since the error message is very confusing and the fix is non-obvious.

**Comment by jayconrod** [comment] 2020-01-07 15:24
I reproduced this and then ran a couple experiments with `.bazelignore`. It looks like the directories named in `.bazelignore` are ignored not only in the main workspace but also in external repositories. Not sure if that's working as intended or not; the documentation only mentions directories in the main workspace.

So what seems to be happening is that the `pkg` directory in a `go_download_sdk` rule (`@go_sdk`) is ignored. It contains the standard library and toolchain, so rules_go must depend on it.

**Comment by csstaub** [comment] 2020-01-07 16:42
Should we file an issue about this on the main bazel repo? At minimum it seems the documentation needs to be clarified if `.bazelignore` rules also apply to external repos.

**Comment by jayconrod** [comment] 2020-01-07 17:35
Seems reasonable to file an issue. As you said, at minimum, the documentation should be clarified.

**Comment by csstaub** [comment] 2020-01-09 21:28
Circling back for anyone who finds this issue, looks like this is fixed on the Bazel main branch, so I'm assuming should be fixed in the next release.
