### ISSUE TITLE
Cross compile no matching toolchains found

### ISSUE THREAD

**Issue by willtrking** [bazelbuild/rules_go#1240] opened 2018-01-13 22:57 UTC
Hey there,

Trying to cross compile to linux/amd64 from darwin with the following command:
`bazel build --experimental_platforms=@io_bazel_rules_go//go/toolchain:linux_amd64 --toolchain_resolution_debug //apparatus/cmd`

Gives me the following error

```
ERROR: While resolving toolchains for target @go_stdlib_netbsd_arm_pure//:go_stdlib_netbsd_arm_pure: no matching toolchains found for types @io_bazel_rules_go//go:bootstrap_toolchain
ERROR: Analysis of target '//apparatus/cmd:cmd' failed; build aborted: no matching toolchains found for types @io_bazel_rules_go//go:bootstrap_toolchain
INFO: Elapsed time: 0.663s
FAILED: Build did NOT complete successfully (41 packages loaded)
```

The toolchain that comes after `ERROR: While resolving toolchains for target` changes on every attempt, but the general error is the same. 

Running bazel 0.8.1

WORKSPACE file

```

git_repository(
    name = "io_bazel_rules_docker",
    remote = "https://github.com/bazelbuild/rules_docker.git",
    commit = "8aeab63328a82fdb8e8eb12f677a4e5ce6b183b1"
)

http_archive(
    name = "io_bazel_rules_go",
    url = "https://github.com/bazelbuild/rules_go/releases/download/0.9.0/rules_go-0.9.0.tar.gz",
    sha256 = "4d8d6244320dd751590f9100cf39fd7a4b75cd901e1f3ffdfd6f048328883695",
)

http_archive(
    name = "bazel_gazelle",
    url = "https://github.com/bazelbuild/bazel-gazelle/releases/download/0.8/bazel-gazelle-0.8.tar.gz",
    sha256 = "e3dadf036c769d1f40603b86ae1f0f90d11837116022d9b06e4cd88cae786676",
)

load("@io_bazel_rules_go//go:def.bzl", "go_rules_dependencies", "go_register_toolchains")
go_rules_dependencies()
go_register_toolchains()

load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies")

gazelle_dependencies()


load(
    "@io_bazel_rules_docker//go:image.bzl",
    _go_image_repos = "repositories"
)

_go_image_repos()

```

BUILD file

```
load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "go_default_library",
    srcs = [
        "config.go",
        "main.go",
        "pgsql.go",
        "version.go",
    ],
    importpath = "github.com/willtrking/mono-test/apparatus/cmd",
    visibility = ["//visibility:private"],
    deps = [
        "//apparatus:go_default_library",
        "//g/gutil:go_default_library",
        "//october-go:go_default_library",
        "//vendor/github.com/jackc/pgx:go_default_library",
        "//vendor/github.com/willtrking/generated-protos/apparatuspb:go_default_library",
        "//vendor/github.com/spf13/cobra:go_default_library",
        "//vendor/github.com/spf13/viper:go_default_library",
        "//vendor/github.com/willtrking/pgsqlxx:go_default_library",
        "//vendor/go.uber.org/zap:go_default_library",
        "//vendor/google.golang.org/grpc:go_default_library",
        "//zing:go_default_library",
        "//zing/pgxzing:go_default_library",
    ],
)

go_binary(
    name = "cmd",
    embed = [":go_default_library"],
    importpath = "github.com/willtrking/mono-test/apparatus/cmd",
    visibility = ["//visibility:public"]
)
```

Any guidance would be greatly appreciated, trying to cross compile for use in a docker container.

**Comment by steeve** [comment] 2018-01-14 16:23
A bisect confirmed it is because of https://github.com/bazelbuild/rules_go/commit/3983133bc698b298e1f71e4b439ce23c1feecfaa

**Comment by steeve** [comment] 2018-01-14 16:26
I managed to make it work again with the following diff:
```diff
diff --git a/go/private/rules/stdlib.bzl b/go/private/rules/stdlib.bzl
index 22a80c6..c2ecf5e 100644
--- a/go/private/rules/stdlib.bzl
+++ b/go/private/rules/stdlib.bzl
@@ -140,7 +140,7 @@ stdlib = rule(
           cfg="host",
           default=Label("@bazel_tools//tools/objc:xcrunwrapper")),
     },
-    toolchains = ["@io_bazel_rules_go//go:bootstrap_toolchain"],
+    toolchains = ["@io_bazel_rules_go//go:toolchain"],
     fragments = ["cpp", "apple"],
 )
```

**Comment by ash2k** [comment] 2018-01-15 06:02
I'm getting similar errors but using `--cpu=k8` flag:
```console
 bazel build --cpu=k8 //bla/bla
ERROR: While resolving toolchains for target @go_stdlib_solaris_amd64_pure_race//:go_stdlib_solaris_amd64_pure_race: no matching toolchains found for types @io_bazel_rules_go//go:bootstrap_toolchain
ERROR: Analysis of target '//bla/bla' failed; build aborted: no matching toolchains found for types @io_bazel_rules_go//go:bootstrap_toolchain
INFO: Elapsed time: 0.390s
FAILED: Build did NOT complete successfully (0 packages loaded)
```
OR
```console
bazel build --cpu=k8 //bla/bla
ERROR: While resolving toolchains for target @go_stdlib_android_arm64_pure_race//:go_stdlib_android_arm64_pure_race: no matching toolchains found for types @io_bazel_rules_go//go:bootstrap_toolchain
ERROR: Analysis of target '//bla/bla' failed; build aborted: no matching toolchains found for types @io_bazel_rules_go//go:bootstrap_toolchain
INFO: Elapsed time: 0.255s
FAILED: Build did NOT complete successfully (0 packages loaded)
```
OR
```
bazel build --cpu=k8 //bla/bla
ERROR: While resolving toolchains for target @go_stdlib_linux_386_pure//:go_stdlib_linux_386_pure: no matching toolchains found for types @io_bazel_rules_go//go:bootstrap_toolchain
ERROR: Analysis of target '//bla/bla' failed; build aborted: no matching toolchains found for types @io_bazel_rules_go//go:bootstrap_toolchain
INFO: Elapsed time: 0.247s
FAILED: Build did NOT complete successfully (0 packages loaded)
```
Note how target toolchains are different and completely wrong. I'm on latest macOS, with Bazel 0.9.0.

**Comment by rmrobinson-textnow** [comment] 2018-01-15 13:43
I am experiencing the same thing on Bazel 0.9.0 and OS X El Capitan.

A minimal set of files that I have used to reproduce this:
WORKSPACE:
```
http_archive(
    name = "io_bazel_rules_go",
    url = "https://github.com/bazelbuild/rules_go/releases/download/0.9.0/rules_go-0.9.0.tar.gz",
    sha256 = "4d8d6244320dd751590f9100cf39fd7a4b75cd901e1f3ffdfd6f048328883695",
)

load(
    "@io_bazel_rules_go//go:def.bzl",
    "go_rules_dependencies",
    "go_register_toolchains",
    "go_repository")

go_rules_dependencies()
go_register_toolchains()
```

BUILD.bazel
```
load("@io_bazel_rules_go//go:def.bzl", "go_binary")

go_binary(
    name = "hello",
    srcs = ["main.go"],
    deps = [],
)
```

main.go
```
package main

import "fmt"

func main() {
	fmt.Println("Hello World!")
}
```

Cross-building yields:
```
bazel build --cpu=k8  //services/helloworld/cmd:hello
ERROR: While resolving toolchains for target @go_stdlib_android_386_pure//:go_stdlib_android_386_pure: no matching toolchains found for types @io_bazel_rules_go//go:bootstrap_toolchain
ERROR: Analysis of target '//services/helloworld/cmd:hello' failed; build aborted: no matching toolchains found for types @io_bazel_rules_go//go:bootstrap_toolchain
INFO: Elapsed time: 0.149s
FAILED: Build did NOT complete successfully (1 packages loaded)
```

The exact toolchain it fails on seems to change (have also seen go_stdlib_freebsd_amd64_cgo, go_stdlib_freebsd_386_cgo, go_stdlib_plan9_arm_cgo, amongst others). Setting/unsetting the 'pure' option does not have an effect.

**Comment by willtrking** [comment] 2018-01-15 21:06
Thanks @steeve 

Switching my workspace to include the commit prior to https://github.com/bazelbuild/rules_go/commit/3983133bc698b298e1f71e4b439ce23c1feecfaa worked for me. Able to successfully cross compile and build docker images with the cross compiled binaries using `go_image`

For anyone else, instead of the `http_archive` which include 0.9.0 of rules_go, use the following

```
git_repository(
    name = "io_bazel_rules_go",
    remote = "https://github.com/bazelbuild/rules_go.git",
    commit = "3f38260eda98d23e9142bb905caede5912508770"
)
```

**Comment by ianthehat** [comment] 2018-01-16 22:17
Bootstrap toolchains were being unnecessarily fussy about matching, should be fixed.

**Closed** 2018-01-18 02:57 UTC
