### ISSUE TITLE
Different os.Getwd() in bazel test and go test

### ISSUE THREAD

**Issue by linzhp** [bazelbuild/rules_go#2032] opened 2019-04-15 18:34 UTC
`os.Getwd()` returns different result when it is called outside test functions than when it is called inside. [Example code](https://github.com/linzhp/bazel_examples/blob/master/workingdir/workingdir_test.go)

### What version of rules_go are you using?

0.18.3

### What version of gazelle are you using?

`63ddd72aa315d020456f1a96bc6fcca9405810cb`

### What version of Bazel are you using?

0.24.1

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

macOS AMD 64

### What did you do?

```bash
git clone https://github.com/linzhp/bazel_examples.git
cd bazel_examples
go test ./workingdir
bazel test workingdir:go_default_test
```

### What did you expect to see?

Both "go test" and "bazel test" succeed.

### What did you see instead?

"go test" succeeded, "bazel test" failed

**Comment by jayconrod** [comment] 2019-04-15 22:01
I believe this is a duplicate of #1918.

**Closed by jayconrod** 2019-04-15 22:01 UTC
