### ISSUE TITLE
Support coverageredesign (Go 1.20+)

### ISSUE THREAD

**Issue by matloob** [bazelbuild/rules_go#3397] opened 2022-12-13 18:57 UTC
@fmeum 

Go 1.20 changes the way coverage is done by default (see https://tip.golang.org/doc/go1.20#cover). This is controlled by the coverageredesign GOEXPERIMENT.

We can work around this by setting GOEXPERIMENT=nocoverageresign, but should update the way coverage is done so that's not necessary.

**Comment by fmeum** [comment] 2023-04-03 11:47
Closing as a duplicate of https://github.com/bazelbuild/rules_go/issues/3513, which has more context.

**Closed by fmeum** 2023-04-03 11:47 UTC
