### ISSUE TITLE
cross compilation does not build platform-specific dependencies

### ISSUE THREAD

**Issue by kevindrosendahl** [bazelbuild/rules_go#1167] opened 2017-12-20 20:38 UTC
Hi,

I've been toying around with cross compiling from darwin to linux amd64 with the `goos` and `goarch` args to `go_binary`, and have found that platform specific dependencies are not being included. I found this referenced in this comment: https://github.com/bazelbuild/rules_go/issues/354#issuecomment-346390320 but could not find an issue for it, so I figured I'd open one.

Below is a reproducible example. Thanks for the great work!

`WORKSPACE`:
```
http_archive(
    name = "io_bazel_rules_go",
    url = "https://github.com/bazelbuild/rules_go/releases/download/0.8.1/rules_go-0.8.1.tar.gz",
    sha256 = "90bb270d0a92ed5c83558b2797346917c46547f6f7103e648941ecdb6b9d0e72",
)
load("@io_bazel_rules_go//go:def.bzl", "go_rules_dependencies", "go_register_toolchains", "go_repository")
go_rules_dependencies()
go_register_toolchains()

go_repository(
        name = "com_github_mattn_go_isatty",
        commit = "57fdcb988a5c543893cc61bce354a6e24ab70022",
        importpath = "github.com/mattn/go-isatty",
)
```

`cmd/main.go`:
```
package main

import (
        "fmt"
        "os"

        "github.com/mattn/go-isatty"
)

func main() {
        // From https://github.com/mattn/go-isatty README.md
        if isatty.IsTerminal(os.Stdout.Fd()) {
                fmt.Println("Is Terminal")
        } else {
                fmt.Println("Is Not Terminal")
        }
}

```

`cmd/BUILD.bazel`:
```
load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["main.go"],
    importpath = "example/cmd",
    visibility = ["//visibility:private"],
    deps = ["@com_github_mattn_go_isatty//:go_default_library"],
)

go_binary(
    name = "cmd",
    embed = [":go_default_library"],
    importpath = "example/cmd",
    visibility = ["//visibility:public"],
)

go_binary(
    name = "cmd_linux",
    embed = [":go_default_library"],
    goarch = "amd64",
    goos = "linux",
    importpath = "example/cmd",
    pure = "on",
    visibility = ["//visibility:public"],
)
```

```
$ uname
Darwin

$ bazel version
Build label: 0.8.1-homebrew
...

$ bazel run //cmd
INFO: Analysed target //cmd:cmd (0 packages loaded).
INFO: Found 1 target...
Target //cmd:cmd up-to-date:
  bazel-bin/cmd/darwin_amd64_stripped/cmd
INFO: Elapsed time: 0.378s, Critical Path: 0.01s
INFO: Build completed successfully, 1 total action

INFO: Running command line: bazel-bin/cmd/darwin_amd64_stripped/cmd
Is Not Terminal

$ bazel build //cmd:cmd_linux
INFO: Analysed target //cmd:cmd_linux (0 packages loaded).
INFO: Found 1 target...
ERROR: .../cmd/BUILD.bazel:18:1: GoCompile cmd/linux_amd64_pure_stripped/cmd_linux~/example/cmd.a failed (Exit 1)
cmd/main.go:12:5: undefined: isatty.IsTerminal
2017/12/20 12:34:12 error running compiler: exit status 1
Target //cmd:cmd_linux failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.504s, Critical Path: 0.12s
FAILED: Build did NOT complete successfully
```

Relevant file with build tag: https://github.com/mattn/go-isatty/blob/master/isatty_linux.go#L1

**Comment by jayconrod** [comment] 2017-12-20 21:29
Thanks for reporting this, especially with a reproducible test case.

I believe this is a duplicate of #1148 though, so I'll close this issue and we can continue discussion there.

**Closed by jayconrod** 2017-12-20 21:29 UTC
