### ISSUE TITLE
gazelle needs to run faster

### ISSUE THREAD

**Issue by mikedanese** [bazelbuild/rules_go#427] opened 2017-05-02 18:06 UTC
gazelle is unreasonably slow in the kubernetes repository. It is 2-3 orders of magnitude slower than gazel. For example:
```console
$ pwd
/usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/pkg
$ time gazel pkg
gazel pkg  3.09s user 0.57s system 141% cpu 2.583 total
$  time (cd pkg/; gazelle -mode fix > gazelle.log 2>&1)
( cd pkg/; gazelle -mode fix > gazelle.log 2>&1; )  5.34s user 4.12s system 1% cpu 10:10.35 total
```
That's 2 seconds vs 10 minutes. I don't know if this is the only issue, but gazel got a huge speedup when we started caching calls to the build.Context, a la [this](https://github.com/mikedanese/gazel/blob/v17/gazel/gazel.go#L127-L146).

**Comment by jayconrod** [comment] 2017-05-02 18:45
Agreed that gazelle is unacceptably slow for Kubernetes. I think #353 is the cause of most of this slowness.

I'll leave this issue open to remind us to re-evaluate performance once #353, since there are probably other significant causes.

**Comment by jayconrod** [comment] 2017-05-11 18:05
@mikedanese Could you check performance with the current Gazelle is acceptable? #353 is fixed now.

**Comment by jayconrod** [comment] 2017-05-24 17:22
@mikedanese Gentle ping. Is performance acceptable now?

We'll be moving away from `build.Context` soon, but I don't expect the performance to be significantly difference, since the new solution does much of the same work.

**Comment by mikedanese** [comment] 2017-05-24 17:25
Yes perf is now accpetable. ~2 seconds for the whole repo using:

gazelle -external vendored

**Closed** 2017-05-24 17:27 UTC
Labels: bug, gazelle
