### ISSUE TITLE
test/a.TestInternalA·f: relocation target test/a.TestInternalA not defined

### ISSUE THREAD

**Issue by junghoahnsc** [bazelbuild/rules_go#813] opened 2017-09-08 01:57 UTC
After I moved rules_go to HEAD, I got a GoLink error like
```
a/BUILD:11:1: GoLink a/a_test failed (Exit 1)
test/a.init: call to external function
main.init: relocation target test/a.init not defined
test/a.TestInternalA·f: relocation target test/a.TestInternalA not defined
main.init: undefined: "test/a.init"
test/a.TestInternalA·f: undefined: "test/a.TestInternalA"
```
This is from a simple test repo to reproduce it:
```
a / a.go
    a_test.go
b / b.go
```
where, `b.go` depends on `a.go`, and `a_test.go` is an internal test that is in the same package as `a.go`

I uploaded this to https://github.com/jhahn21/test/tree/go_rule_test.
Is this a dependency issue?

Thanks,

**Comment by ianthehat** [comment] 2017-09-08 03:50
The error message is not very clear, but this is a fundamentally broken project.
It's not really a dependancy issue, it's a duplicate package issue.
`//a:a_test` depends on `//a/b:go_default_library` depends on `//a:go_default_library`
which is not a cycle, so bazel is happy with it. The problem is that 
`//a:go_default_library` and`//a:a_test`
both represent the same package as far as the linker is concerned, you cannot ever link both of those targets into the same binary.
We probably ought to be able to detect this and produce a more helpful message, but it's never going to actually work.

**Comment by junghoahnsc** [comment] 2017-09-08 04:03
Thanks for looking into this!
Then, how does the current 0.5.4 version work with this project?

**Comment by redhotpenguin** [comment] 2017-10-23 22:16
Thanks for the description @ianthehat. I ran into this error a couple days ago and was able to work through my code to discover the circular dependency which was causing this.

**Comment by dlorenc** [comment] 2017-10-25 17:45
@redhotpenguin any tips for tracking down how to find the circular dependency? I have some code that builds fine with "go build" but hits this error in bazel.

**Comment by redhotpenguin** [comment] 2017-10-25 22:59
@dlorenc start by commenting out packages in your a_test.go file to make sure you don't need them. Then go through that revised list and see if any of them have a.go as a dependency.

In my case it turned out that I had referenced a.go in a_test.go, when I didn't need to as they were in the same namespace. A methodical approach and patience are your friends here.

**Comment by ashi009** [comment] 2017-11-24 07:30
@ianthehat gazelle generates `go_test` rule with the identical `importpath` as the `go_library` one has.  Which ultimate caused this collision.  So a quick fix is to give all the go_test rules different `importpath`s, i.e. adding a suffix `_test`.

This is not a perfect solution, as in theory it's not testing the `same` code, as other libraries are calling the code in the `go_libaray` while the `go_test` is using the code embedded.

**Comment by jayconrod** [comment] 2017-11-27 18:57
Closing this issue, since I don't think there's anything to be done on the rules_go side.

As @ianthehat mentioned, in any given build, no two packages can have the same import path. We have ways of working around this for internal and external tests.

Internal tests live in the same package as the code being tested. This works by referencing the library under test through the `embed` attribute of a `go_test` rule. So the library won't actually be compiled with the test, but the test and library will be compiled together as a single package.

External tests live in a different package (ending with _test). These tests have a different import path from the library under test and are compiled separately.

"go test" hides most of this complexity, but this is how it works under the hood.

The one big limitation that we know of is that internal and external tests can't be part of the same `go_test` rule. It's difficult to reference test-only helper definitions defined in an internal test from an external test. It's still possible to do this through creative use of `embed`.

**Closed by jayconrod** 2017-11-27 18:57 UTC
