### ISSUE TITLE
rules_go broken by Bazel@HEAD because docker env

### ISSUE THREAD

**Issue by mhlopko** [bazelbuild/rules_go#1669] opened 2018-08-17 06:51 UTC
Hello go team :)

CC @philwo

It seems that this PR https://github.com/bazelbuild/bazel/pull/5721 will break //tests/core/go_path:go_path_test once released. I can cleanly reproduce, buildkite can as well (https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/386#61d56139-a891-4868-b136-e34a6f3f68f3).

Would you mind taking a look, and in case this actually is a bug in Bazel file an issue?

Thank you!

**Comment by jayconrod** [comment] 2018-08-17 14:00
I'll take a look at this today. Any special steps to reproduce?

Just from a quick look at the logs, it seems that we're getting a symlink but we expect a regular file. This would be inside a directory output; my understanding is that the action that produces the directory has control over the file content and metadata within it. Is that changing?

What's the story with the docker env?

**Comment by jayconrod** [comment] 2018-08-23 19:06
Closing the issue here because I think this is a regression in Bazel. Opened bazelbuild/bazel#5971 to track this.

**Closed** 2018-09-05 20:15 UTC
