### ISSUE TITLE
gazelle creates invalid copts

### ISSUE THREAD

**Issue by dbenamydd** [bazelbuild/rules_go#1065] opened 2017-11-27 16:56 UTC
Hi again! ~https://github.com/jmhodges/levigo~ A variant of <- with manually vendored deps doesn't work out of the box:

WORKSPACE
```
http_archive(
    name = "io_bazel_rules_go",
    url = "https://github.com/bazelbuild/rules_go/releases/download/0.7.0/rules_go-0.7.0.tar.gz",
    sha256 = "91fca9cf860a1476abdc185a5f675b641b60d3acf0596679a27b580af60bf19c",
)
load("@io_bazel_rules_go//go:def.bzl", "go_rules_dependencies", "go_register_toolchains")
go_rules_dependencies()
go_register_toolchains()
```

BUILD
```
load("@io_bazel_rules_go//go:def.bzl", "gazelle", "go_library", "go_test")

gazelle(
    name = "gazelle",
    prefix = "github.com/whatever",
)
```

```
bazel run //:gazelle
```
adds a bit to BUILD including
```
    copts = [
        "-I/deps/lz4 -I/deps/leveldb/include -fno-builtin-memcmp -DLEVELDB_PLATFORM_POSIX -DLEVELDB_ATOMIC_PRESENT",
        "-I/deps/lz4 -I/deps/leveldb/include -I/deps/leveldb -std=c++11 -fno-builtin-memcmp -lpthread -DLEVELDB_PLATFORM_POSIX -DLEVELDB_ATOMIC_PRESENT",
        "-I/deps/snappy -DSNAPPY",
        "-I/deps/snappy -std=c++11 -g -O2 -fPIC -DPIC -DSNAPPY",
```
and then
```
bazel build //...
...
ERROR: /code/github.com/DataDog/leveldb/BUILD:8:1: in cc_library rule //:go_default_library.cgo_c_lib: The include path '/deps/lz4' references a path outside of the execution root.
...
```

I got this stuff building by adding separate BUILD files for the deps and then having the go rule specify cdeps, and if that's the best way to do it, maybe that's too complicated for gazelle for figure out. If it's easy though, maybe it could error out with useful info instead?

I'm still very new to bazel so could definitely be missing something though!

Many thanks!

**Comment by jayconrod** [comment] 2017-11-27 17:23
Gazelle gets the `copts` and `clinkopts` from `#cgo` directives in the source files. Some flags are necessary to compile (especially flags like -D, -f). Some flags include or link system libraries, which makes sense in some contexts but not others. In general though, Gazelle can't figure it out. If a flag is causing problems, try setting `copts` manually to something that works, then marking it with a `# keep` comment so Gazelle doesn't modify it further.

I'm a little surprised by the error you're getting, "... references a path outside of the execution root." Normally that is allowed, but discouraged. What version of Bazel and rules_go are you using? Does this go away if you change the -I flags to -isystem?

**Comment by dbenamydd** [comment] 2017-11-29 09:06
Oh, makes sense.

And sorry, I realized I originally hit this on a private fork on the above mentioned repo which has a slightly different setup.

That said:

bazel 0.7.0
rules_go 0.7.0
go 1.9.2
-isystem didn't help

**Comment by mathyourlife-fitbit** [comment] 2017-12-14 19:00
Hit the same `references a path outside of the execution root.` when working with a library that has github.com/miekg/pkcs11 vendored.

bazel: 0.8.1
rules_go: 0.8.1  737df20c53499fd84b67f04c6ca9ccdee2e77089
running on mac

I created a minimal project that replicates the issue.
https://github.com/mathyourlife-fitbit/bazel-project is a bazel project with a target //:tar that is attempting to build and package the binary from a "third party" https://github.com/mathyourlife-fitbit/bazel-binary-source 

```
bazel build //:tar
ERROR: /private/var/tmp/_bazel_dcouture/d5e61e8ad266b2a99e30e0bf66e97296/external/com_github_mathyourlife_fitbit_bazel_binary_source/vendor/github.com/miekg/pkcs11/BUILD.bazel:3:1: in cc_library rule @com_github_mathyourlife_fitbit_bazel_binary_source//vendor/github.com/miekg/pkcs11:go_default_library.cgo_c_lib: The include path '/usr/local/share/libtool' references a path outside of the execution root.
ERROR: Analysis of target '//:tar' failed; build aborted: Analysis of target '@com_github_mathyourlife_fitbit_bazel_binary_source//vendor/github.com/miekg/pkcs11:go_default_library.cgo_c_lib' failed; build aborted
INFO: Elapsed time: 0.178s
FAILED: Build did NOT complete successfully (1 packages loaded)
```

**Comment by jayconrod** [comment] 2017-12-15 00:03
@mathyourlife-fitbit That's working as intended from the Bazel perspective. One of Bazel's major strengths is that it forces rules to be explicit about their dependencies, and it sandboxes actions to prevent them from accessing files they haven't declared. This is needed for remote execution and caching to work. Exceptions are made for standard C/C++ toolchains, headers, and libraries (which don't need to be cached and can be installed on remote executors), but nothing in /usr/local is standard.

In order for this cgo code to work, you'll need to get that library (ltdl) compiled through a Bazel rule (`cc_library`) then add it as a dependency of the `go_library` through the `cgo` attribute. This is not something Gazelle (and by extension `go_repository`) can do automatically. You'll need to edit the build files for this, so you'll probably need to vendor it.

**Comment by mathyourlife-fitbit** [comment] 2017-12-15 12:30
Thanks, @jayconrod .  I'll give that a shot.

**Comment by ianthehat** [comment] 2017-12-21 19:43
I am going to close this issue as it seems there is no work for us to do here, please re-open if you thing this is not the case.

**Closed by ianthehat** 2017-12-21 19:43 UTC
Labels: question
