### ISSUE TITLE
build_file_name seems to be viral

### ISSUE THREAD

**Issue by gbrail** [bazelbuild/rules_go#240] opened 2017-01-04 01:08 UTC
Thanks for fixing the build_file_name parameter!

I am trying to use the "viper" library:

new_go_repository(
  name = "com_github_spf13_viper",
  importpath = "github.com/spf13/viper",
  commit = "651d9d916abc3c3d6a91a12549495caba5edffd2",
)

This depends on way too many things, including:

new_go_repository(
  name = "com_github_spf13_afero",
  importpath = "github.com/spf13/afero",
  commit = "2f30b2a92c0e5700bcfe4715891adb1f2a7a406d",
)

which, in turn, depends on good old "x/text":

new_go_repository(
  name = "org_golang_x_text",
  importpath = "golang.org/x/text",
  commit = "fd889fe3a20f4878f5f47672fd3ca5b86db005e2",
  build_file_name = "BUILD.bazel",
)

As you can see I included "build_file_name" because the x/text package has a directory named "build" which previously broke my build. So now that particular part of the build does not break.

However, now I get the following error:

ERROR: /private/var/tmp/.../external/com_github_spf13_afero/BUILD:5:1: no such package '@org_golang_x_text//unicode/norm': BUILD file not found on package path and referenced by '@com_github_spf13_afero//:go_default_library'.

It seems that I can move this error elsewhere by adding "build_file_name" to the other two package definitions in WORKSPACE. However I fear that perhaps I will have to do this for every BUILD file in my project.

Is there another way to work around this? Thanks!

**Comment by katre** [comment] 2017-01-04 16:11
What version of Bazel are you using? I recently committed https://github.com/bazelbuild/bazel/commit/b9c65d1ea5254b41238c23bdfbe3543f1dbd3a42 (after initially committing it, then reverting it), which does exactly this: external repositories will use BUILD.bazel instead of BUILD to fix this issue.

Can you try building Bazel from head and seeing if that has the same issue? This is pretty much a duplicate of #2226.

**Comment by katre** [comment] 2017-01-04 16:13
Sorry, commented on the wrong issue, although it is also clearly related. :)
Looking further now.

**Comment by katre** [comment] 2017-01-04 17:27
Sorry, do you have a repository I can clone to demonstrate the behavior? It'll be easier to try and diagnose the issue.

**Comment by gbrail** [comment] 2017-01-04 17:45
Let me create one on my personal account for reproducing this.

**Comment by gbrail** [comment] 2017-01-04 18:25
OK -- I created this repo:

https://github.com/gbrail/bazeltest

It works fine using standard go tools:

$ go get github.com/spf13/viper
$ go get github.com/spf13/pflag
$ go build
$ ./bazeltest -a foo
Thanks! The argument is "foo"

With Bazel I get this:

$ bazel build ...
ERROR:
/private/var/tmp/xxx/86a917567b1bb441eefbaa9cc0bd05b1/external/com_github_spf13_afero/BUILD:5:1:
no such package '@org_golang_x_text//unicode/norm': BUILD file not found on
package path and referenced by
'@com_github_spf13_afero//:go_default_library'.
ERROR: Analysis of target '//:bazeltest' failed; build aborted.
INFO: Elapsed time: 0.129s

I'm using go 1.7.3 and Bazel 0.4.3 (from Homebrew) on OS X.

**Comment by katre** [comment] 2017-01-04 20:15
Thanks!

I can reproduce your problem with Bazel 0.4.3. When I use Bazel built from head (which contains the fix for https://github.com/bazelbuild/bazel/issues/2226), I don't see the same errors.

Then I saw errors trying to access gopkg.in/yaml.v2. That doesn't seem to be an actual git repository, which is what new_go_repository expects. Once I changed it as follows, your bazeltest target builds:
```
new_go_repository(
  name = "in_gopkg_yaml_v2",
  importpath = "gopkg.in/yaml.v2",
  remote = "github.com/go-yaml/yaml",
  commit = "a5b47d31c556af34a302ce5d659e6fea44d90de0",
)
```

We're planning a Bazel release of 0.5.0 this month that will include that fix, until then please use Bazel built from head. (Cherrypicking the fix for https://github.com/bazelbuild/bazel/issues/2226 into 0.4.3 unfortunately doesn't seem to work, for reasons I haven't figured out).

**Closed by katre** 2017-01-04 20:15 UTC

**Comment by gbrail** [comment] 2017-01-05 17:41
Thank you! The build from "master" works great for me.
