### ISSUE TITLE
Compiling with cgo fails when #including a .c file

### ISSUE THREAD

**Issue by treaster** [bazelbuild/rules_go#281] opened 2017-02-28 07:06 UTC
Go compilation fails when a .c source file #includes another .c file. Renaming the included file to .h results in successful compilation, suggesting that the problem is due to how Bazel and/or rules_go handles file extensions. The scenario works properly when compiling with the standard go toolchain. The code differs only in the name of the #included file.

The resulting error when a .c file is #included is:
```
ERROR: [snip]/bazel_cgo_includes/src/fails/BUILD:3:1: CGoCodeGen //src/fails:cgo_default_library.cgo failed: Process exited with status 1 [sandboxed].
[snip]/local-fastbuild/genfiles/src/fails/cgo_default_library.cgo.dir/src/src/fails/foo.go:6:21: fatal error: lib/foo.c: No such file or directory
compilation terminated.
```

I've create a repository to demonstrate the problem, with instructions.
https://github.com/treaster/bazel_cgo_includes

Working BUILD file is here:
https://github.com/treaster/bazel_cgo_includes/blob/master/src/works/BUILD

Failing BUILD file is here:
https://github.com/treaster/bazel_cgo_includes/blob/master/src/fails/BUILD

How to reproduce:
```
git clone https://github.com/treaster/bazel_cgo_includes.git
export GOPATH=$(pwd)/bazel_cgo_includes
cd $GOPATH
bazel build src/works:works # compilation succeeds
bazel build src/fails:fails # compilation fails
go build works  # compilation succeeds
go build fails  # compilation succeeds
```

**Comment by jayconrod** [comment] 2017-04-04 19:13
Sorry to take so long to look into this. I was able to reproduce this issue using the repository linked (thanks for including that!).

The selection based on file extension happens in [`_setup_cgo_library`](https://github.com/bazelbuild/rules_go/blob/3e16d3e328b161ed23b85f4b639ab284b92f1d4a/go/def.bzl#L1118). Only the .go files and the C headers are passed to `cgo_codegen`. That causes the error you saw.

Passing all files to `cgo_codegen` doesn't fix the problem though. The cgo generated files and the C sources and headers are [built with `cc_library`](https://github.com/bazelbuild/rules_go/blob/3e16d3e328b161ed23b85f4b639ab284b92f1d4a/go/def.bzl#L1154). Bazel does not allow inclusion of .c files through `cc_library`. You can reproduce this with something like the following:

```bzl
# BUILD
cc_library(
    name = "foo",
    srcs = ["foo.c", "bar.c"],
)
```

```c
// foo.c
#include "bar.c"
int foo() {
  return bar();
}
```

```c
// bar.c
inline int bar() {
  return 12;
}
```

Since we need `cc_library` to compile this, I don't think it's feasible for us to fix this issue, so I'm closing this.

Is it possible for you to include .h files instead? Including .c files would result in them being compiled multiple times (through includes and on their own). Link errors are pretty likely in that situation.

**Closed by jayconrod** 2017-04-04 19:13 UTC
