### ISSUE TITLE
list of valid targets

### ISSUE THREAD

**Issue by jeb2239** [bazelbuild/rules_go#745] opened 2017-08-23 23:53 UTC
Hello, I am considering using bazel and go for an existing project which is configured to use vendoring. There seem to be no working examples of a a complex go project using bazel. I was wondering how I can view a list of valid build targets.

**Comment by ianthehat** [comment] 2017-08-24 00:29
Hi,
There are some fairly complicated projects using bazel+go, but most of the ones I know of are either not ones you can see publicly, or so complicated that they do not act as a good example for new users.

If you have specific questions, or want to get us to look at how you are using them, we would be happy to help.

Are you asking for the set of things that would be valid for a `bazel build` command line?
If so you can use bazel query to find out what targets exist, although I generally find using the bash tab completion much easier.

**Comment by jeb2239** [comment] 2017-08-24 14:23
This is our project structure.

```
.
├── bazel-bin -> /home/barriosj/.cache/bazel/_bazel_barriosj/3e70ab7c419be882c8e5f76cf833d218/execroot/__main__/bazel-out/local-fastbuild/bin
├── bazel-genfiles -> /home/barriosj/.cache/bazel/_bazel_barriosj/3e70ab7c419be882c8e5f76cf833d218/execroot/__main__/bazel-out/local-fastbuild/genfiles
├── bazel-go -> /home/barriosj/.cache/bazel/_bazel_barriosj/3e70ab7c419be882c8e5f76cf833d218/execroot/__main__
├── bazel-out -> /home/barriosj/.cache/bazel/_bazel_barriosj/3e70ab7c419be882c8e5f76cf833d218/execroot/__main__/bazel-out
├── bazel.sh
├── bazel-testlogs -> /home/barriosj/.cache/bazel/_bazel_barriosj/3e70ab7c419be882c8e5f76cf833d218/execroot/__main__/bazel-out/local-fastbuild/testlogs
├── bin
│   ├── govendor
│   └── swagger
├── build
│   ├── configExample
│   ├── config.json
│   └── loggerExample
├── BUILD.bazel
├── nova
├── pkg
│   └── linux_amd64
│       └── nova
├── src
│   └── nova
│       ├── apps
│       ├── bin
│       ├── common
│       ├── framework
│       └── vendor 
├── vendor
│   ├── github.com
│   │   ├── denisenkom
│   │   ├── DisposaBoy
│   │   ├── gorilla
│   │   ├── sirupsen
│   │   └── Sirupsen
│   ├── golang.org
│   │   └── x
│   └── gopkg.in
│       ├── airbrake
│       └── gemnasium
└── WORKSPACE
```

If we drill down into the nova directory more....

```
 nova
    ├── apps
    │   ├── example
    │   │   ├── BUILD.bazel
    │   │   ├── configExample.go  <=== main pkg
    │   │   ├── loggerExample.go  <=== main pkg
    │   │   
    │   ├── dogService
    │   │   ├── BUILD.bazel
    │   │   ├── dogService.go   <=== main pkg
    │   │   |-- dogServiceHandlers.go 
    │   ├── catService
    │   │   ├── BUILD.bazel
    │   │   ├── catService.go  <=== main pkg
    |   |   |-- catServiceBisLogic.go
    │   └── snakeService
    │       ├── BUILD.bazel
    │       └── snakeService.go <=== main pkg
    |
    ├── common
    │   ├── config
    │   │   ├── BUILD.bazel
    │   │   ├── jsonconfig.go
    │   │   └── jsonconfig_test.go
    │   └── log
    │       ├── BUILD.bazel
    │       ├── json_formatter.go
    │       └── logger.go
    .....
```

The top level WORKSPACE file

```
git_repository(
    name = "io_bazel_rules_go",
    remote = "https://github.com/bazelbuild/rules_go.git",
    tag = "0.5.3",
)
load("@io_bazel_rules_go//go:def.bzl", "go_repositories")
load("@io_bazel_rules_go//go:def.bzl", "go_repository")
go_repository(
    name = "com_github_denisenkom_go-mssqldb",
    importpath = "github.com/denisenkom/go-mssqldb",
    commit = "fbf0a491e5ec011522c8870da9b0553135e2f9da"
)

go_repository(
        name = "com_github_DisposaBoy_JsonConfigReader",
        importpath = "github.com/DisposaBoy/JsonConfigReader",
        commit = "33a99fdf1d5ee1f79b5077e9c06f955ad356d5f4"
)

go_repository(
        name = "com_github_gorilla_mux",
        importpath = "github.com/gorilla/mux",
        commit = "4c1c3952b7d9d0a061a3fa7b36fd373ba0398ebc"
)

go_repository(
        name = "com_github_gorilla_handlers",
        importpath = "github.com/gorilla/handlers",
        commit = "a4d79d4487c2430a17d9dc8a1f74d1a6ed6908ca"
)

go_repositories()
```



The top level BUILD.bzl

```
load("@io_bazel_rules_go//go:def.bzl", "gazelle", "go_prefix")

go_prefix("src")

gazelle(name = "gazelle")

```

**Comment by jeb2239** [comment] 2017-08-24 14:24
I just don't really even know where to start with using bazel to build. I am used to gradle's gradle build doing all the work.

**Comment by jeb2239** [comment] 2017-08-25 02:26
Hello, just wondering if you have any suggestions. The company I work for will most likely ditch bazel if we can't figure out how to use it and I think that would be a mistake.

**Comment by ianthehat** [comment] 2017-08-25 02:38
One thing is that it looks like you are using vendored directories.
Although this is not really the Bazel way, we do support it, but you need to put external="vendored" in your gazelle rule if you want to use that.
You can build everything with `bazel build //...` and test everything with `bazel test //...`, or you can build a specific thing by listing just that rule, I am guessing `bazel build //src/nova/apps/dogService` for instance would be one target.
If you try that and tell me what error you get, I can help more. I am assuming the repository you are working on is private and I can't directly take a look?

**Comment by jeb2239** [comment] 2017-08-25 02:53
yeah it is private which makes getting support for this harder. what is the Bazel way of doing this? I think the whole vendor thing is strange anyway and very different from how C++ libs are handled.

**Comment by jeb2239** [comment] 2017-08-25 03:00
```
bazel build //src/nova/apps/example/loggerExample

.................................
ERROR: no such package 'src/nova/apps/example/loggerExample': BUILD file not found on package path.
INFO: Elapsed time: 0.407s

```

**Comment by jeb2239** [comment] 2017-08-25 03:25
```
bazel build //src/nova/apps/example:example.
INFO: Found 1 target...
ERROR: /home/barriosj/services.barriosj/go/src/nova/apps/example/BUILD.bazel:11:1: GoCompile src/evo/apps/example/~lib~/example.o failed (Exit 1).
2017/08/24 23:22:45 missing strict dependencies:
	src/nova/apps/example/configExample.go: import of nova/common/config, which is not a direct dependency
Target //src/nova/apps/example:example failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.735s, Critical Path: 0.33s
```

This is what I got with the BUILD.bazel being
```
load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "go_default_library",
    srcs = [
        "configExample.go"
    ],
    visibility = ["//visibility:private"],
)

go_binary(
    name = "example",
    library = ":go_default_library",
    visibility = ["//visibility:public"],
)

```

**Comment by jeb2239** [comment] 2017-08-25 13:36
I tried running bazel build again like so

```
bazel build //src/nova/apps/example:loggerExample --verbose_failures
WARNING: Output base '/home/barriosj/.cache/bazel/_bazel_barriosj/3e70ab7c419be882c8e5f76cf833d218' is on NFS. This may lead to surprising failures and undetermined behavior.
ERROR: /home/barriosj/services.barriosj/go/src/nova/apps/example/BUILD.bazel:13:1: no such package 'nova/common/log': BUILD file not found on package path and referenced by '//src/nova/apps/example:loggerExample'.
ERROR: Analysis of target '//src/nova/apps/example:loggerExample' failed; build aborted.
INFO: Elapsed time: 0.097s
```
With `/home/barriosj/my_proj/go/BUILD.bazel` being

```
load("@io_bazel_rules_go//go:def.bzl", "gazelle", "go_prefix")

go_prefix("src")

gazelle(
    name = "gazelle",
    external = "vendored",
)
```
And
`/home/barriosj/services.barriosj/go/src/evo/apps/example/BUILD.bazel` being
```
load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_binary(
    name = "configExample",
    srcs = ["configExample.go"],
    visibility = ["//visibility:public"],
    deps = [
        "//src/nova/common/config:go_default_library",
        "//vendor/github.com/sirupsen/logrus:go_default_library",
    ],
)

go_binary(
    name = "loggerExample",
    srcs = ["loggerExample.go"],
    visibility = ["//visibility:public"],
    deps = ["//nova/common/log:go_default_library"],
)


```

**Comment by ianthehat** [comment] 2017-08-25 17:41
The dependancy in loggerExample is broken, 
deps = ["//nova/common/log:go_default_library"],
should probably be 
deps = ["//src/nova/common/log:go_default_library"],

**Comment by jeb2239** [comment] 2017-08-26 22:13
what is the alternative to vendoring?

**Comment by ianthehat** [comment] 2017-08-27 02:08
Using bazel external repositories, basically the contents of the WORKSPACE file.
These let you pick which version of your dependancies you use, and where to get them from. It gives you flexibility and reproducibility without having to pollute your source tree, commit things to your repository, or run any external tools.

**Comment by jeb2239** [comment] 2017-08-27 02:12
do I need gazel with this approach?

**Comment by jeb2239** [comment] 2017-08-27 02:23
is the workspace file I posted above correct?

**Comment by ianthehat** [comment] 2017-08-27 02:33
You do need gazelle to build your own BUILD files, and it's also running for you inside the go_repository rules.
Your original WORKSPACE file looked okay, I can't really say for certain it is either correct or complete without seeing the rest of your repository.

**Comment by jeb2239** [comment] 2017-08-27 02:48
when I try to use my own libraries 
import "nova/common/log"    it always fails. Is there any reason for this based on the build and workspace i posted above?

**Comment by ianthehat** [comment] 2017-08-27 03:03
It's the same thing I pointed out yesterday.
gazelle is going to consistently get the deps wrong because of the src directory below your workspace root.
If you import nova/common/log gazelle is going to put //nova/common/log:go_default_library in the deps, and that's not the path to the actual go library.
In the future, gazelle will be clever enough to work this out, but for now you have to hand fix deps that are wrong.

**Comment by jeb2239** [comment] 2017-08-27 03:08
so I should just remove the src directory and make nova in the same directory as WORKSPACE?

**Comment by jeb2239** [comment] 2017-08-27 03:11
This is very very very similar to what I am trying to build. https://github.com/jeb2239/go_cmake_project

**Comment by jeb2239** [comment] 2017-08-27 19:47
I think I may have gotten the hang of it now.

How ever for the first time I get this error

```
bazel build -s //:gazelle
ERROR: /home/barriosj/.cache/bazel/_bazel_barriosj/a2b9c39f61ee73a06e61e45fc6ce8f8a/external/io_bazel_rules_go/go/tools/gazelle/gazelle/BUILD:24:1: every rule of type go_binary implicitly depends upon the target '@io_bazel_rules_go_toolchain//:go_toolchain', but this target could not be found because of: no such package '@io_bazel_rules_go_toolchain//': The repository could not be resolved
ERROR: Analysis of target '//:gazelle' failed; build aborted
INFO: Elapsed time: 0.147s
```

Does this mean every time this is installed it has to get the rules from github? Is there away to store them locally on a filesystem

**Comment by jeb2239** [comment] 2017-08-28 01:07
I am trying the external dependencies method right now.

Is bazel unable to build 3rd part projects? 

for example

https://github.com/sirupsen/logrus

```
ERROR: /home/barriosj/.cache/bazel/_bazel_barriosj/3e70ab7c419be882c8e5f76cf833d218/external/com_github_sirupsen_logrus/BUILD.bazel:5:1: no such package '@org_golang_x_crypto//ssh/terminal': The repository could not be resolved and referenced by '@com_github_sirupsen_logrus//:go_default_library'.
ERROR: Analysis of target '//src/evo/apps/example:go_default_library' failed; build aborted.
INFO: Elapsed time: 0.171s

```

**Comment by ianthehat** [comment] 2017-08-28 01:43
Bazel caches external repositories, but it will refetch them if you modify anything that could have affected what got fetched, or if you do a clean (you should almost never do clean in Bazel though, about the only good reason to is if you wrote a broken rule)

That error is because the package you are trying to build has another dependancy that you did not add to your workspace. You can add dependancies using [wtool](/bazelbuild/rules_go/tree/master/go/tools/wtool), normally you can cut'n'paste part of the name from the error message, in this case
```
wtool org_golang_x_crypto
```
is probably what you want. Unfortunately this is a fairly long winded process for the very first time if you have lots of transitive dependancies and you have to add them one by one if there are a lot of them. We have plans for how to fix this by adding more functionality to gazelle but it's not going to be done any time soon.

**Comment by jeb2239** [comment] 2017-08-29 00:11
also is it possible to install all the rules needed for bazel locally? or install them so that they are fetched from a directory?

**Comment by twpayne** [comment] 2017-08-29 14:06
To install locally ("vendor") `rules_go` locally in `bazel-rules/`, I have the following:

1) This in my `WORKSPACE`:

```python
local_repository(
    name = "io_bazel_rules_go",
    path = "bazel-rules/github.com/bazelbuild/rules_go",
)

load("@io_bazel_rules_go//go:def.bzl", "go_repositories")

go_repositories()
```

2) A script to fetch or update `rules_go`:

```sh
#!/bin/sh

RULES_GO_VERSION=0.5.3
rm -rf bazel-rules/github.com/bazelbuild/rules_go
mkdir -p bazel-rules/github.com/bazelbuild/rules_go
curl -s -L https://github.com/bazelbuild/rules_go/archive/${RULES_GO_VERSION}.tar.gz | tar -C bazel-rules/github.com/bazelbuild/rules_go --strip-components=1 -xzf -
```

**Comment by ianthehat** [comment] 2017-08-29 14:30
If you just want to avoid the downloads, you want to use `--experimental_repository_cache=some_absoulte_path` which causes it to cache all downloads (across all instances of bazel).
bazel clean never empties that folder.
If you want to run with local modifications of rules_go, then you can use `--override_repository` to force a local copy in place of the expected one (which is what we do when working on the rules)
The advantage of these approaches is you don't have to have modifications of  your workspace or build that you should not commit or push.
You can put them in your bazelrc to avoid having to type them all the time.

**Comment by jeb2239** [comment] 2017-08-30 23:52
can we use our own toolchain? it seems that the rules assume we want to use the downloaded go

**Comment by jeb2239** [comment] 2017-08-31 23:09
is setting my own toolchain impossible?

**Comment by jeb2239** [comment] 2017-09-01 13:48
Any information on this?

**Comment by jayconrod** [comment] 2017-09-01 15:00
This is still being developed, and there are some changes currently in flight that will should make local toolchains easier.

cc @ianthehat

**Comment by jeb2239** [comment] 2017-09-01 16:19
How do industrial users of bazel get around this limitation?

**Comment by ianthehat** [comment] 2017-09-01 16:27
Toolchains were checked in for the very first time this week, there are no industrial users of bazel using this feature yet.
There are also very few demands for custom sdk's, everyone just wants to use the ones shipped by the go team, so it's not a feature in high demand.
There is a demand for the ability to use the host toolchain in a container, for people that want to control the installed sdk by controlling the image rather than the go version, and that is possible right now.
Setting your own toolchain right now is possible, but it's more work than it needs to be, and the system is changing fast, so it's going to be frustrating to keep up to date with.
Can I ask what your use case is so I can make sure the stuff we are writing supports it?

**Comment by jeb2239** [comment] 2017-09-01 16:42
I guess the logic is that we can't afford to use a remotely hosted toolchain because it may not be there and we must be able to clean build our software no matter what. We also will need to download the Go rules and put them on our file system as well.

**Comment by ianthehat** [comment] 2017-09-01 16:52
So they way most people manage that at the moment is a simple http proxy
The go sdk's are fetched using the http rules, and verified by sha, so it's easy to do and be sure it's okay.
You can also (as of this morning) just pre-declare the sdk's and leave the toolchains alone.
You can use the go_sdk rule with the same name as one of the built in sdk's but a different url, so long as you do so before you load the go rules, it will prefer your version to the one inside the rules, but it will still build the toolchain on top of it for you.
This is not the same thing as declaring a custom toolchain, which you do if you actually want to alter the behaviour, or a custom sdk that has differing layout or features, both of which are more effort and still changing fast.

**Comment by jeb2239** [comment] 2017-09-01 16:58
so I can't just download go and put it on my file system and point bazel to that install?

**Comment by jeb2239** [comment] 2017-09-01 17:00
if I have a system wide go installation bazel can't be configured to work with that correct?

**Comment by ianthehat** [comment] 2017-09-01 17:21
As I mentioned above, building with host sdk is an important case for containers, so we do support it.
I said how to do this in #683, but it's not documented yet. You specify `--experimental_platforms=@io_bazel_rules_go//go/toolchain:host` on the command line.
The command line will probably change in the future as the newer toolchain selection improvements get added to bazel, but that should work right now.
It will prefer the GOROOT environment variable if set, otherwise it will search your path for the go executable.
You can also just use the go_sdk override mechanism but with a path rather than a url, if you want it permanent in your workspace rather than custom on the command line.

**Comment by jeb2239** [comment] 2017-09-01 17:57
how do I use go_sdk ? do you have and example of using without a url?

**Comment by ianthehat** [comment] 2017-09-01 18:04
It's not documented yet because it's not finished yet, but if you want to try it
```
go_sdk(name="go1_8_1_linux_amd64", url="https://storage.googleapis.com/golang/go1.8.1.linux-amd64.tar.gz")
```

**Comment by jeb2239** [comment] 2017-09-06 16:18
is it possible to customize the location of the vendor directory?

**Comment by jayconrod** [comment] 2017-09-06 17:42
> is it possible to customize the location of the vendor directory?

What would this mean? The rules don't recognize the vendor directory as being special, except to determine the import path of a library if it's unspecified. Gazelle does not allow the vendor directory to be customized.

> And can we use local directories as external dependencies instead of repositories?

You need to use some kind of repository (not just a directory), but there are ways to make that local. You can use [`local_repository`](https://docs.bazel.build/versions/master/be/workspace.html#local_repository). It accepts absolute or relative paths. Avoid pointing inside the current workspace though, as that will confuse Bazel. You can also use [`http_archive`](https://docs.bazel.build/versions/master/be/workspace.html#http_archive) with a local proxy.

**Comment by jeb2239** [comment] 2017-09-06 20:03
so can't point gazzelle to my vendor directory and have it use it?

**Comment by jayconrod** [comment] 2017-09-06 20:06
You can run gazelle with `-external vendored` on the command line or `external = "vendored"` in the rule. That will tell Gazelle to resolve import paths outside of your prefix to the vendor directory. You can't vendor the SDK or rules_go itself that way though.

**Comment by ianthehat** [comment] 2017-10-05 00:20
I am going to close this issue as it is not tracking any work we need to do and all questions have been answered, please feel free to re-open or open new issues if you need to.

**Closed by ianthehat** 2017-10-05 00:20 UTC
Labels: question
