### ISSUE TITLE
asm fails on building with `--compilation_mode=dbg`

### ISSUE THREAD

**Issue by vhbit** [bazelbuild/rules_go#2150] opened 2019-07-18 10:29 UTC
### What version of rules_go are you using?

0.19

### What version of gazelle are you using?

0.18.1

### What version of Bazel are you using?

0.28

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

Mac OS X 10.14.5, X86_64

### What did you do?

building with `--compilation_mode=dbg` fails with:
```
flag provided but not defined: -N
usage: asm [options] file.s ...
Flags:
  -D value
    	predefined symbol with optional simple value -D=identifier=value; can be set multiple times
  -I value
    	include directory; can be set multiple times
  -S	print assembly and machine code
  -V	print version and exit
  -debug
    	dump instructions as they are parsed
  -dynlink
    	support references to Go symbols defined in other shared libraries
  -e	no limit on number of errors reported
  -gensymabis
    	write symbol ABI information to output file, don't assemble
  -o string
    	output file; default foo.o for /a/b/c/foo.s as first argument
  -shared
    	generate code that can be linked into a shared library
  -trimpath string
    	remove prefix from recorded source file paths
compilepkg: error running subcommand: exit status 2
```

After running with `--sandbox_debug --verbose_failures` I've noticed that in long-long output there is the following:
`-gcflags '-N -l' -asmflags '-N -l'`

seems that `-N` should not go to the `-asmflags` as that parameter is not supported by `go tool asm`.

Removing `--compilation_mode=dbg` fixes the build

**Comment by jayconrod** [comment] 2019-07-18 13:59
I think this is a duplicate of #2144, but please comment if you can reproduce this on `master`.

**Closed by jayconrod** 2019-07-18 13:59 UTC
