### ISSUE TITLE
doesn't allow cgo CXXFLAGS `-std` setting that go build allows

### ISSUE THREAD

**Issue by jmhodges** [bazelbuild/rules_go#1512] opened 2018-05-23 21:08 UTC
The package `somemain` at https://github.com/jmhodges/bazel_bugs/tree/cld3 (the branch cld3 of my bazel_bugs repo) fails to build with:

```
$  bazel build //somemain:somemain 
INFO: Analysed target //somemain:somemain (4 packages loaded).
INFO: Found 1 target...
ERROR: /private/var/tmp/_bazel_jmhodges/eb16c8c3f4af4addfaf08c38f6204969/external/com_github_jmhodges_gocld3/cld3/BUILD.bazel:3:1: CGoCodeGen @com_github_jmhodges_gocld3//cld3:go_default_library.cgo_codegen failed (Exit 1)
error: invalid argument '-std=c++11' not allowed with 'C'
```

It seems that the gocld3 package does not build because of the CXXFLAGS setting in it (see https://github.com/jmhodges/gocld3/blob/b87be5d4b64748be2c19665b2b48abaa88a81d51/cld3/cld3.go#L8). 

That `-std=c++11` fixes warnings (and, I think, errors) that would otherwise occur in the C++ build.

**Comment by jayconrod** [comment] 2018-05-24 14:39
Thanks for reporting this. I've opened bazelbuild/bazel-gazelle#206, which is the root cause of this. `-std=c++11` should go in `cxxopts` instead of `copts`. I'll close this issue in favor of that one.

rules_go support for `cxxopts` is pretty recent. Gazelle combines all of these together because we used to only accept a single list, `copts`.

**Closed by jayconrod** 2018-05-24 14:39 UTC
