### ISSUE TITLE
gazelle can't use cloud.google.com/go/datastore from v1.0.0

### ISSUE THREAD

**Issue by ribrdb** [bazelbuild/rules_go#2202] opened 2019-08-26 21:32 UTC
gazelle seems to work correctly up to cloud.google.com/go v0.44.0
After that they split cloud.google.com/go/datastore into a separate module. Now gazelle generates separate workspaces for com_google_cloud_go and com_google_cloud_go_datastore, and com_google_cloud_go_datastore can't access the internal packages from @com_gogle_cloud_go.

**Comment by jayconrod** [comment] 2019-09-09 18:20
Duplicate of bazelbuild/bazel-gazelle#619

**Closed by jayconrod** 2019-09-09 18:20 UTC
